using Vertica.Data.VerticaClient;
using RepoDb.Vertica.BulkOperations.IntegrationTests.Models;
using System;

namespace RepoDb.IntegrationTests.Setup
{
    /// <summary>
    /// A class used as a startup setup for the RepoDb Vertica bulk-operations test database.
    /// </summary>
    public static class Database
    {
        #region Properties

        /// <summary>
        /// Gets the connection string to be used for the Vertica database.
        /// </summary>
        public static string ConnectionString { get; private set; }

        #endregion

        #region Methods

        /// <summary>
        /// Initialize the creation of the database.
        /// </summary>
        public static void Initialize()
        {
            ConnectionString = Environment.GetEnvironmentVariable("REPODB_VERTICA_CONSTR") ??
                @"DataSource=127.0.0.1;Port=3050;Database=/vertica/data/repodb.fdb;User=SYSDBA;Password=RepoDB2026;Charset=UTF8;Pooling=false;";

            GlobalConfiguration
                .Setup()
                .UseVertica();

            CreateTables();
        }

        /// <summary>
        /// Clean up all the table.
        /// </summary>
        public static void Cleanup()
        {
            using var connection = new VerticaConnection(ConnectionString);
            connection.Truncate<BulkOperationIdentityTable>();
            connection.Truncate<BulkOperationNonIdentityTable>();
        }

        #endregion

        #region CreateTables

        /// <summary>
        /// Create the necessary tables for testing.
        /// </summary>
        public static void CreateTables()
        {
            CreateBulkOperationIdentityTable();
            CreateBulkOperationNonIdentityTable();
        }

        /// <summary>
        /// 
        /// </summary>
        public static void CreateBulkOperationIdentityTable()
        {
            var commandText = @"
                RECREATE TABLE ""BulkOperationIdentityTable""
                (
                    ""Id"" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    ""RowGuid"" CHAR(16) CHARACTER SET OCTETS NOT NULL,
                    ""ColumnBit"" BOOLEAN,
                    ""ColumnDateTime"" TIMESTAMP,
                    ""ColumnDateTime2"" TIMESTAMP,
                    ""ColumnDecimal"" DECIMAL(18,2),
                    ""ColumnFloat"" DOUBLE PRECISION,
                    ""ColumnInt"" INTEGER,
                    ""ColumnNVarChar"" VARCHAR(2000),
                    CONSTRAINT ""BulkOperationIdentityTable_pk"" PRIMARY KEY (""Id"")
                )";
            using var connection = new VerticaConnection(ConnectionString);
            connection.ExecuteNonQuery(commandText);
        }

        /// <summary>
        /// 
        /// </summary>
        public static void CreateBulkOperationNonIdentityTable()
        {
            var commandText = @"
                RECREATE TABLE ""BulkOperationNonIdentityTable""
                (
                    ""Id"" BIGINT NOT NULL,
                    ""RowGuid"" CHAR(16) CHARACTER SET OCTETS NOT NULL,
                    ""ColumnBit"" BOOLEAN,
                    ""ColumnDateTime"" TIMESTAMP,
                    ""ColumnDateTime2"" TIMESTAMP,
                    ""ColumnDecimal"" DECIMAL(18,2),
                    ""ColumnFloat"" DOUBLE PRECISION,
                    ""ColumnInt"" INTEGER,
                    ""ColumnNVarChar"" VARCHAR(2000),
                    CONSTRAINT ""BulkOperationNonIdentityTable_pk"" PRIMARY KEY (""Id"")
                )";
            using var connection = new VerticaConnection(ConnectionString);
            connection.ExecuteNonQuery(commandText);
        }

        #endregion
    }
}
