name: repodb
version: '3.8'

services:

  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2025-latest
    ports:
      - 127.0.0.1:1433:1433
    networks:
      - repodb
    environment:
      ACCEPT_EULA: true
      MSSQL_SA_PASSWORD: RepoDB2026

  postgresql:
    container_name: pgsql
    image: postgres:latest
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - repodb
    environment:
      POSTGRES_PASSWORD: RepoDB2026

  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - 127.0.0.1:3306:3306
    networks:
      - repodb
    environment:
      MYSQL_ROOT_PASSWORD: RepoDB2026


  oracle:
    container_name: oracle
    image: container-registry.oracle.com/database/free:latest
    ports:
      - 127.0.0.1:1521:1521
    networks:
      - repodb
    environment:
      ORACLE_PWD: RepoDB2026

networks:
  repodb:
    driver: bridge