#region Copyright Attributions

// Copyright (c) 2026 Michael Camara Pendon.
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for full license information.

#endregion

using Sap.Data.Hana;
using RepoDb.SapHana.BulkOperations.IntegrationTests.Models;
using System;
using System.Text.RegularExpressions;

namespace RepoDb.IntegrationTests.Setup
{
    /// <summary>
    /// A class used as a startup setup for the RepoDb SAP HANA bulk-operations test database.
    /// </summary>
    public static class Database
    {
        #region Properties

        /// <summary>
        /// Gets the connection string to be used for the SAP HANA database.
        /// </summary>
        public static string ConnectionString { get; private set; }

        #endregion

        #region Methods

        /// <summary>
        /// Initialize the creation of the database.
        /// </summary>
        public static void Initialize()
        {
            // RepoDb connection. Port 39041 is the HANA Express tenant ("HXE") database's own SQL port -
            // connecting there directly is required in a Docker setup like this repo's docker-compose.yml:
            // the SYSTEMDB port (39013) redirects clients to the tenant using the container's internal
            // Docker-network address, which isn't reachable from the host.
            ConnectionString =
                Environment.GetEnvironmentVariable("REPODB_SAPHANA_CONSTR_BULK") ??
                Environment.GetEnvironmentVariable("REPODB_SAPHANA_CONSTR") ??
                "Server=localhost:39041;UserID=SYSTEM;Password=RepoDB2026;Current Schema=REPODB;";

            // Initialize SAP HANA
            GlobalConfiguration
                .Setup()
                .UseSapHana();

            // HANA refuses to even open a connection whose "Current Schema" doesn't exist yet, so the
            // target schema has to be created (if missing) over a connection string with that clause
            // stripped, before ConnectionString itself can be used for anything else.
            EnsureSchema();

            // Create the tables
            CreateTables();
        }

        private static void EnsureSchema()
        {
            var schemaMatch = Regex.Match(ConnectionString, @"Current Schema\s*=\s*([^;]+)", RegexOptions.IgnoreCase);
            var schemaName = schemaMatch.Success ? schemaMatch.Groups[1].Value.Trim() : "REPODB";
            var bootstrapConnectionString = Regex.Replace(ConnectionString, @"Current Schema\s*=\s*[^;]*;?", "", RegexOptions.IgnoreCase);

            using var connection = new HanaConnection(bootstrapConnectionString);
            connection.Open();

            using var command = connection.CreateCommand();
            command.CommandText = $"SELECT COUNT(*) FROM SYS.SCHEMAS WHERE SCHEMA_NAME = '{schemaName}'";
            var exists = Convert.ToInt32(command.ExecuteScalar()) > 0;

            if (!exists)
            {
                command.CommandText = $"CREATE SCHEMA \"{schemaName}\"";
                command.ExecuteNonQuery();
            }
        }

        /// <summary>
        /// Clean up all the table.
        /// </summary>
        public static void Cleanup()
        {
            using var connection = new HanaConnection(ConnectionString);
            connection.Truncate<BulkOperationIdentityTable>();
            connection.Truncate<BulkOperationNonIdentityTable>();
        }

        /// <summary>
        /// HANA has no <c>CREATE TABLE IF NOT EXISTS</c> - unlike its <c>CREATE TABLE ... IF NOT EXISTS</c>
        /// claim, attempting it throws a syntax error - so callers must check for the table first.
        /// </summary>
        private static bool TableExists(HanaConnection connection,
            string tableName)
        {
            return connection.ExecuteScalar<int>(
                $"SELECT COUNT(*) FROM SYS.TABLES WHERE SCHEMA_NAME = CURRENT_SCHEMA AND TABLE_NAME = '{tableName}'") > 0;
        }

        #endregion

        #region CreateTables

        /// <summary>
        /// Create the necessary tables for testing.
        /// </summary>
        public static void CreateTables()
        {
            CreateBulkOperationIdentityTable();
            CreateBulkOperationNonIdentityTable();
        }

        /// <summary>
        /// Creates an identity table that has some important fields. All fields are nullable except
        /// <c>Id</c> and <c>RowGuid</c>. <c>Id</c> is <c>BIGINT GENERATED BY DEFAULT AS IDENTITY</c>;
        /// <c>RowGuid</c> is stored as a plain <c>NVARCHAR(36)</c> - SAP HANA has no native GUID type, so
        /// unlike SapHana's CHAR(36) (which binds directly to/from <see cref="Guid"/>), callers are
        /// expected to pass the string form (<c>Guid.ToString()</c>).
        /// </summary>
        public static void CreateBulkOperationIdentityTable()
        {
            using var connection = new HanaConnection(ConnectionString);

            if (TableExists(connection, "BulkOperationIdentityTable")) return;

            var commandText = @"
                CREATE TABLE ""BulkOperationIdentityTable""
                (
                    ""Id"" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    ""RowGuid"" NVARCHAR(36) NOT NULL,
                    ""ColumnBit"" TINYINT NULL,
                    ""ColumnDateTime"" TIMESTAMP NULL,
                    ""ColumnDateTime2"" TIMESTAMP NULL,
                    ""ColumnDecimal"" DECIMAL(18,2) NULL,
                    ""ColumnFloat"" DOUBLE NULL,
                    ""ColumnInt"" INTEGER NULL,
                    ""ColumnNVarChar"" NVARCHAR(2000) NULL,
                    PRIMARY KEY (""Id"")
                );";
            connection.ExecuteNonQuery(commandText);
        }

        /// <summary>
        /// Creates a non-identity table that has some important fields. All fields are nullable except
        /// the primary key. Unlike <see cref="CreateBulkOperationIdentityTable"/>, <c>Id</c> here is a
        /// plain <c>BIGINT</c> primary key (no <c>GENERATED ... AS IDENTITY</c>) - the caller's value is
        /// stored as-is. Used by tests that need to know a row's <c>Id</c> ahead of time (e.g. matching
        /// against a separately-built anonymous/expando object by primary key), which a HANA-generated
        /// identity value can't support.
        /// </summary>
        public static void CreateBulkOperationNonIdentityTable()
        {
            using var connection = new HanaConnection(ConnectionString);

            if (TableExists(connection, "BulkOperationNonIdentityTable")) return;

            var commandText = @"
                CREATE TABLE ""BulkOperationNonIdentityTable""
                (
                    ""Id"" BIGINT NOT NULL,
                    ""RowGuid"" NVARCHAR(36) NOT NULL,
                    ""ColumnBit"" TINYINT NULL,
                    ""ColumnDateTime"" TIMESTAMP NULL,
                    ""ColumnDateTime2"" TIMESTAMP NULL,
                    ""ColumnDecimal"" DECIMAL(18,2) NULL,
                    ""ColumnFloat"" DOUBLE NULL,
                    ""ColumnInt"" INTEGER NULL,
                    ""ColumnNVarChar"" NVARCHAR(2000) NULL,
                    PRIMARY KEY (""Id"")
                );";
            connection.ExecuteNonQuery(commandText);
        }

        #endregion
    }
}
