using System;
using System.Collections.Generic;
using Vertica.Data.VerticaClient;
using RepoDb.Vertica.IntegrationTests.Models;

namespace RepoDb.Vertica.IntegrationTests.Setup
{
    public static class Database
    {
        #region Properties

        /// <summary>
        /// Gets or sets the connection string to be used.
        /// </summary>
        public static string ConnectionString { get; private set; }

        #endregion

        #region Methods

        public static void Initialize()
        {
            // Pooling=false: RECREATE TABLE (see CreateCompleteTable/CreateNonIdentityCompleteTable
            // below) needs an exclusive metadata lock on the table. If a pooled physical connection
            // from an earlier test is handed back out still carrying an uncommitted implicit
            // transaction that touched the table (e.g. a test that threw before its normal commit
            // path ran), the very next RECREATE TABLE collides with that leftover transaction and
            // fails with "lock conflict on no wait transaction ... object TABLE is in use" - even
            // though every test runs sequentially. Disabling pooling means every VerticaConnection is a
            // genuinely fresh session with no transaction state carried over from a previous test.
            ConnectionString =
                Environment.GetEnvironmentVariable("REPODB_VERTICA_CONSTR") ??
                @"DataSource=127.0.0.1;Port=3050;Database=/vertica/data/repodb.fdb;User=SYSDBA;Password=RepoDB2026;Charset=UTF8;Pooling=false;";

            // Initialize Vertica
            GlobalConfiguration
                .Setup()
                .UseVertica();

            // Create tables
            CreateTables();
        }

        public static void Cleanup()
        {
            using (var connection = new VerticaConnection(ConnectionString))
            {
                connection.Truncate<CompleteTable>();
                connection.Truncate<NonIdentityCompleteTable>();
            }
        }

        #endregion

        #region CompleteTable

        public static IEnumerable<CompleteTable> CreateCompleteTables(int count)
        {
            using (var connection = new VerticaConnection(ConnectionString))
            {
                var tables = Helper.CreateCompleteTables(count);
                connection.InsertAll(tables);
                return tables;
            }
        }

        #endregion

        #region NonIdentityCompleteTable

        public static IEnumerable<NonIdentityCompleteTable> CreateNonIdentityCompleteTables(int count)
        {
            using (var connection = new VerticaConnection(ConnectionString))
            {
                var tables = Helper.CreateNonIdentityCompleteTables(count);
                connection.InsertAll(tables);
                return tables;
            }
        }

        #endregion

        #region CreateTables

        private static void CreateTables()
        {
            CreateCompleteTable();
            CreateNonIdentityCompleteTable();
        }

        private static void CreateCompleteTable()
        {
            using (var connection = new VerticaConnection(ConnectionString))
            {
                // ColumnBinary/ColumnVarBinary use BLOB SUB_TYPE 0 rather than CHAR/VARCHAR
                // CHARACTER SET OCTETS: VerticaDataReader reports the latter's CLR field type as
                // System.String even though the byte content itself is preserved, which breaks
                // RepoDb's compiled reader-to-entity mapping for a byte[] property ("No coercion
                // operator is defined between types 'System.String' and 'System.Byte[]'"). BLOB
                // SUB_TYPE 0 correctly reports as System.Byte[], matching every other binary column
                // here (ColumnBlob, ColumnLongBlob, etc.).
                connection.ExecuteNonQuery(@"RECREATE TABLE ""CompleteTable""
                    (
                        ""Id"" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                        ""ColumnVarchar"" VARCHAR(256),
                        ""ColumnInt"" INTEGER,
                        ""ColumnDecimal2"" DECIMAL(18,2),
                        ""ColumnDateTime"" TIMESTAMP,
                        ""ColumnBlob"" BLOB SUB_TYPE 0,
                        ""ColumnBlobAsArray"" BLOB SUB_TYPE 0,
                        ""ColumnBinary"" BLOB SUB_TYPE 0,
                        ""ColumnLongBlob"" BLOB SUB_TYPE 0,
                        ""ColumnMediumBlob"" BLOB SUB_TYPE 0,
                        ""ColumnTinyBlob"" BLOB SUB_TYPE 0,
                        ""ColumnVarBinary"" BLOB SUB_TYPE 0,
                        ""ColumnDate"" DATE,
                        ""ColumnDateTime2"" TIMESTAMP,
                        ""ColumnTime"" TIME,
                        ""ColumnTimeStamp"" TIMESTAMP,
                        ""ColumnYear"" SMALLINT,
                        ""ColumnBigint"" BIGINT,
                        ""ColumnDecimal"" DECIMAL(10,0),
                        ""ColumnDouble"" DOUBLE PRECISION,
                        ""ColumnFloat"" FLOAT,
                        ""ColumnInt2"" INTEGER,
                        ""ColumnMediumInt"" INTEGER,
                        ""ColumnReal"" DOUBLE PRECISION,
                        ""ColumnSmallInt"" SMALLINT,
                        ""ColumnTinyInt"" SMALLINT,
                        ""ColumnChar"" CHAR(1),
                        ""ColumnJson"" BLOB SUB_TYPE TEXT,
                        ""ColumnNChar"" NCHAR(16),
                        ""ColumnNVarChar"" NCHAR VARYING(256),
                        ""ColumnLongText"" BLOB SUB_TYPE TEXT,
                        ""ColumnMediumText"" BLOB SUB_TYPE TEXT,
                        ""ColumnText"" BLOB SUB_TYPE TEXT,
                        ""ColumnTinyText"" VARCHAR(255),
                        ""ColumnBit"" BOOLEAN,
                        PRIMARY KEY (""Id"")
                    );");
            }
        }

        private static void CreateNonIdentityCompleteTable()
        {
            using (var connection = new VerticaConnection(ConnectionString))
            {
                connection.ExecuteNonQuery(@"RECREATE TABLE ""NonIdentityCompleteTable""
                    (
                        ""Id"" BIGINT NOT NULL,
                        ""ColumnVarchar"" VARCHAR(256),
                        ""ColumnInt"" INTEGER,
                        ""ColumnDecimal2"" DECIMAL(18,2),
                        ""ColumnDateTime"" TIMESTAMP,
                        ""ColumnBlob"" BLOB SUB_TYPE 0,
                        ""ColumnBlobAsArray"" BLOB SUB_TYPE 0,
                        ""ColumnBinary"" BLOB SUB_TYPE 0,
                        ""ColumnLongBlob"" BLOB SUB_TYPE 0,
                        ""ColumnMediumBlob"" BLOB SUB_TYPE 0,
                        ""ColumnTinyBlob"" BLOB SUB_TYPE 0,
                        ""ColumnVarBinary"" BLOB SUB_TYPE 0,
                        ""ColumnDate"" DATE,
                        ""ColumnDateTime2"" TIMESTAMP,
                        ""ColumnTime"" TIME,
                        ""ColumnTimeStamp"" TIMESTAMP,
                        ""ColumnYear"" SMALLINT,
                        ""ColumnBigint"" BIGINT,
                        ""ColumnDecimal"" DECIMAL(10,0),
                        ""ColumnDouble"" DOUBLE PRECISION,
                        ""ColumnFloat"" FLOAT,
                        ""ColumnInt2"" INTEGER,
                        ""ColumnMediumInt"" INTEGER,
                        ""ColumnReal"" DOUBLE PRECISION,
                        ""ColumnSmallInt"" SMALLINT,
                        ""ColumnTinyInt"" SMALLINT,
                        ""ColumnChar"" CHAR(1),
                        ""ColumnJson"" BLOB SUB_TYPE TEXT,
                        ""ColumnNChar"" NCHAR(16),
                        ""ColumnNVarChar"" NCHAR VARYING(256),
                        ""ColumnLongText"" BLOB SUB_TYPE TEXT,
                        ""ColumnMediumText"" BLOB SUB_TYPE TEXT,
                        ""ColumnText"" BLOB SUB_TYPE TEXT,
                        ""ColumnTinyText"" VARCHAR(255),
                        ""ColumnBit"" BOOLEAN,
                        PRIMARY KEY (""Id"")
                    );");
            }
        }

        #endregion
    }
}
