using Oracle.ManagedDataAccess.Client;
using RepoDb.Oracle.IntegrationTests.Models;
using RepoDb.Oracle.PropertyHandlers;
using System;

namespace RepoDb.Oracle.IntegrationTests.Setup
{
    public static class Database
    {
        #region Properties

        /// <summary>
        /// Gets the connection string to be used for the Oracle database.
        /// </summary>
        public static string ConnectionString { get; private set; }

        #endregion

        #region Methods

        public static void Initialize()
        {
            // RepoDb connection. Defaults match the 'oracle' service in docker-compose.yml at the
            // repo root (container-registry.oracle.com/database/free, ORACLE_PWD=RepoDB2026),
            // which exposes the SYSTEM user against the FREEPDB1 pluggable database.
            ConnectionString =
                Environment.GetEnvironmentVariable("REPODB_ORACLE_CONSTR") ??
                "User Id=system;Password=RepoDB2026;Data Source=localhost:1521/FREEPDB1;";

            // Initialize Oracle
            GlobalConfiguration
                .Setup()
                .UseOracle();

            // Oracle has no native GUID type; "SessionId" is stored as RAW(16). Scope the Guid<->byte[]
            // conversion to this specific property rather than registering it globally for typeof(Guid),
            // since a global registration would also affect any other provider used in the same process.
            PropertyHandlerMapper.Add<CompleteTable, OracleGuidToByteArrayPropertyHandler>(
                e => e.SessionId, new OracleGuidToByteArrayPropertyHandler(), true);

            // Create tables
            CreateTables();
        }

        public static void Cleanup()
        {
            using var connection = new OracleConnection(ConnectionString);
            connection.Truncate<CompleteTable>();
        }

        #endregion

        #region CreateTables

        private static void CreateTables()
        {
            CreateCompleteTable();
        }

        private static void CreateCompleteTable()
        {
            // Oracle has no "CREATE TABLE IF NOT EXISTS"; guard with a PL/SQL block instead.
            var commandText = @"
                BEGIN
                    -- The 'system' user's default tablespace ('SYSTEM') doesn't support Automatic
                    -- Segment Space Management, which SecureFiles LOBs require (ORA-43853). The
                    -- explicit 'STORE AS BASICFILE' clauses below are the actual fix; this just
                    -- relaxes DB_SECUREFILE to PERMITTED for the session as a defensive measure in
                    -- case it's set more strictly than its documented PREFERRED/PERMITTED default.
                    EXECUTE IMMEDIATE 'ALTER SESSION SET DB_SECUREFILE = PERMITTED';

                    EXECUTE IMMEDIATE '
                        CREATE TABLE ""CompleteTable""
                        (
                            ""Id"" NUMBER GENERATED BY DEFAULT AS IDENTITY,
                            ""SessionId"" RAW(16) NOT NULL,
                            ""ColumnVarchar"" NVARCHAR2(256) NULL,
                            ""ColumnNumber"" NUMBER(18,12) NULL,
                            ""ColumnDate"" DATE NULL,
                            ""ColumnTimestamp"" TIMESTAMP(7) NULL,
                            ""ColumnVarchar2"" VARCHAR2(500) NULL,
                            ""ColumnChar"" CHAR(10) NULL,
                            ""ColumnNChar"" NCHAR(10) NULL,
                            ""ColumnInt"" NUMBER(10,0) NULL,
                            ""ColumnBigInt"" NUMBER(19,0) NULL,
                            ""ColumnSmallInt"" NUMBER(5,0) NULL,
                            ""ColumnTinyInt"" NUMBER(3,0) NULL,
                            ""ColumnBinaryFloat"" BINARY_FLOAT NULL,
                            ""ColumnBinaryDouble"" BINARY_DOUBLE NULL,
                            ""ColumnTimestampTz"" TIMESTAMP(7) WITH TIME ZONE NULL,
                            ""ColumnTimestampLtz"" TIMESTAMP(7) WITH LOCAL TIME ZONE NULL,
                            ""ColumnRaw"" RAW(500) NULL,
                            ""ColumnClob"" CLOB NULL,
                            ""ColumnNClob"" NCLOB NULL,
                            ""ColumnBlob"" BLOB NULL,
                            ""ColumnIntervalDs"" INTERVAL DAY(2) TO SECOND(6) NULL,
                            ""ColumnXml"" XMLTYPE NULL,
                            CONSTRAINT ""CompleteTable_Id"" PRIMARY KEY (""Id"")
                        )
                        LOB (""ColumnClob"") STORE AS BASICFILE,
                        LOB (""ColumnNClob"") STORE AS BASICFILE,
                        LOB (""ColumnBlob"") STORE AS BASICFILE,
                        XMLTYPE COLUMN ""ColumnXml"" STORE AS BASICFILE BINARY XML';
                EXCEPTION
                    WHEN OTHERS THEN
                        IF SQLCODE != -955 THEN -- ORA-00955: name is already used by an existing object
                            RAISE;
                        END IF;
                END;";
            using var connection = new OracleConnection(ConnectionString);
            connection.ExecuteNonQuery(commandText);
        }

        #endregion

        #region CompleteTable

        public static System.Collections.Generic.IEnumerable<CompleteTable> CreateCompleteTables(int count)
        {
            using var connection = new OracleConnection(ConnectionString);
            // Materialize eagerly - Helper.CreateCompleteTables is a lazy generator, and each
            // re-enumeration would otherwise produce fresh random rows that were never inserted.
            var tables = System.Linq.Enumerable.ToList(Helper.CreateCompleteTables(count));
            foreach (var table in tables)
            {
                connection.Insert(table);
            }
            return tables;
        }

        #endregion
    }
}
