using Oracle.ManagedDataAccess.Client;
using RepoDb.Oracle.IntegrationTests.Models;
using System;

namespace RepoDb.Oracle.IntegrationTests.Setup
{
    public static class Database
    {
        #region Properties

        /// <summary>
        /// Gets the connection string to be used for the Oracle database.
        /// </summary>
        public static string ConnectionString { get; private set; }

        #endregion

        #region Methods

        public static void Initialize()
        {
            // RepoDb connection. Defaults match the 'oracle' service in docker-compose.yml at the
            // repo root (container-registry.oracle.com/database/free, ORACLE_PWD=RepoDB2026),
            // which exposes the SYSTEM user against the FREEPDB1 pluggable database.
            ConnectionString =
                Environment.GetEnvironmentVariable("REPODB_ORACLE_CONSTR") ??
                "User Id=system;Password=RepoDB2026;Data Source=localhost:1521/FREEPDB1;";

            // Initialize Oracle
            GlobalConfiguration
                .Setup()
                .UseOracle();

            // Create tables
            CreateTables();
        }

        public static void Cleanup()
        {
            using var connection = new OracleConnection(ConnectionString);
            connection.Truncate<CompleteTable>();
        }

        #endregion

        #region CreateTables

        private static void CreateTables()
        {
            CreateCompleteTable();
        }

        private static void CreateCompleteTable()
        {
            // Oracle has no "CREATE TABLE IF NOT EXISTS"; guard with a PL/SQL block instead.
            var commandText = @"
                BEGIN
                    EXECUTE IMMEDIATE '
                        CREATE TABLE ""CompleteTable""
                        (
                            ""Id"" NUMBER GENERATED BY DEFAULT AS IDENTITY,
                            ""SessionId"" RAW(16) NOT NULL,
                            ""ColumnVarchar"" NVARCHAR2(256) NULL,
                            ""ColumnNumber"" NUMBER(18,2) NULL,
                            ""ColumnDate"" DATE NULL,
                            ""ColumnTimestamp"" TIMESTAMP NULL,
                            CONSTRAINT ""CompleteTable_Id"" PRIMARY KEY (""Id"")
                        )';
                EXCEPTION
                    WHEN OTHERS THEN
                        IF SQLCODE != -955 THEN -- ORA-00955: name is already used by an existing object
                            RAISE;
                        END IF;
                END;";
            using var connection = new OracleConnection(ConnectionString);
            connection.ExecuteNonQuery(commandText);
        }

        #endregion

        #region CompleteTable

        public static System.Collections.Generic.IEnumerable<CompleteTable> CreateCompleteTables(int count)
        {
            using var connection = new OracleConnection(ConnectionString);
            // Materialize eagerly - Helper.CreateCompleteTables is a lazy generator, and each
            // re-enumeration would otherwise produce fresh random rows that were never inserted.
            var tables = System.Linq.Enumerable.ToList(Helper.CreateCompleteTables(count));
            foreach (var table in tables)
            {
                connection.Insert(table);
            }
            return tables;
        }

        #endregion
    }
}
