#region Copyright Attributions

// Copyright (c) 2026 Michael Camara Pendon.
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for full license information.

#endregion

using System;
using System.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using RepoDb.Schema.Enumerations;
using RepoDb.Schema.Models;

namespace RepoDb.Schema.Firebird.UnitTests
{
    [TestClass]
    public class FirebirdSchemaComposerTest
    {
        #region Helpers

        private static ColumnInfo GetColumn(string name,
            string databaseType,
            Type type,
            int ordinal,
            bool isNullable = true,
            int? size = null,
            byte? precision = null,
            byte? scale = null) =>
            new ColumnInfo
            {
                Ordinal = ordinal,
                Field = new DbField(name, false, false, isNullable, type, size, precision, scale, databaseType)
            };

        private static string ComposeTypeName(string databaseType,
            Type type,
            int? size = null,
            byte? precision = null,
            byte? scale = null) =>
            new FirebirdSchemaComposer().ComposeTypeName(GetColumn("Column", databaseType, type, 1, true, size, precision, scale));

        private static TableSchema GetPersonSchema()
        {
            var schema = new TableSchema("Person", null);
            schema.Columns.Add(new ColumnInfo
            {
                Ordinal = 1,
                IdentitySeed = 10,
                IdentityIncrement = 5,
                Field = new DbField("Id", true, true, false, typeof(long), 8, 19, 0, "bigint")
            });
            schema.Columns.Add(new ColumnInfo
            {
                Ordinal = 2,
                Collation = "BINARY_CI",
                Field = new DbField("Name", false, false, false, typeof(string), 128, 0, 0, "varchar")
            });
            schema.Columns.Add(new ColumnInfo
            {
                Ordinal = 3,
                DefaultExpression = "0",
                Field = new DbField("Age", false, false, true, typeof(int), 4, 10, 0, "int", true)
            });
            schema.PrimaryKey = new PrimaryKeyInfo("PK_Person") { Columns = { "Id" } };
            schema.UniqueConstraints.Add(new UniqueConstraintInfo("UQ_Person_Name") { Columns = { "Name" } });
            schema.CheckConstraints.Add(new CheckConstraintInfo("CK_Person_Age") { Expression = "(\"Age\" >= 0)" });
            schema.Indexes.Add(new IndexInfo("IX_Person_Name") { Columns = { "Name" }, IncludedColumns = { "Age" } });
            schema.ForeignKeys.Add(new ForeignKeyInfo("FK_Person_Country")
            {
                Columns = { "Age" },
                ReferencedTable = new TableInfo("Country", null),
                ReferencedColumns = { "Id" }
            });
            return schema;
        }

        #endregion

        #region ComposeCreateTable

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeCreateTable()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var schema = GetPersonSchema();

            // Act
            var actual = composer.ComposeCreateTable(schema);
            var expected = string.Join(Environment.NewLine,
                "CREATE TABLE \"Person\" (",
                "    \"Id\" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10 INCREMENT BY 5) NOT NULL,",
                "    \"Name\" VARCHAR(128) NOT NULL,",
                "    \"Age\" INTEGER DEFAULT 0,",
                "    CONSTRAINT \"PK_Person\" PRIMARY KEY (\"Id\"),",
                "    CONSTRAINT \"UQ_Person_Name\" UNIQUE (\"Name\"),",
                "    CONSTRAINT \"CK_Person_Age\" CHECK ((\"Age\" >= 0))",
                ")");

            // Assert
            Assert.AreEqual(expected, actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeCreateTableWithoutSchemaName()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var schema = new TableSchema("Person", null);
            schema.Columns.Add(GetColumn("Name", "varchar", typeof(string), 1, false, 50));

            // Act
            var actual = composer.ComposeCreateTable(schema);
            var expected = string.Join(Environment.NewLine,
                "CREATE TABLE \"Person\" (",
                "    \"Name\" VARCHAR(50) NOT NULL",
                ")");

            // Assert
            Assert.AreEqual(expected, actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeCreateTableOrdersTheColumnsByOrdinal()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var schema = new TableSchema("Person", null);
            schema.Columns.Add(GetColumn("Second", "int", typeof(int), 2));
            schema.Columns.Add(GetColumn("First", "int", typeof(int), 1));

            // Act
            var actual = composer.ComposeCreateTable(schema);

            // Assert
            Assert.IsTrue(actual.IndexOf("\"First\"", StringComparison.Ordinal) < actual.IndexOf("\"Second\"", StringComparison.Ordinal));
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeCreateTableWithComputedColumn()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var schema = new TableSchema("Person", null);
            schema.Columns.Add(new ColumnInfo
            {
                Ordinal = 1,
                ComputedExpression = "upper(\"Name\")",
                Field = new DbField("NameUpper", false, false, true, typeof(string), 128, 0, 0, "varchar")
            });

            // Act
            var actual = composer.ComposeCreateTable(schema);

            // Assert
            StringAssert.Contains(actual, "\"NameUpper\" VARCHAR(128) GENERATED ALWAYS AS (upper(\"Name\"))", StringComparison.Ordinal);
            Assert.IsFalse(actual.Contains("DEFAULT", StringComparison.Ordinal));
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeCreateTableIgnoresTheDefaultOfAnIdentityColumn()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var schema = new TableSchema("Person", null);
            schema.Columns.Add(new ColumnInfo
            {
                Ordinal = 1,
                DefaultExpression = "0",
                Field = new DbField("Id", true, true, false, typeof(int), 4, 10, 0, "int")
            });

            // Act
            var actual = composer.ComposeCreateTable(schema);

            // Assert
            StringAssert.Contains(actual, "\"Id\" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL", StringComparison.Ordinal);
            Assert.IsFalse(actual.Contains("DEFAULT 0", StringComparison.Ordinal));
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeCreateTableIgnoresTheCollationOfTheColumn()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var schema = new TableSchema("Person", null);
            schema.Columns.Add(new ColumnInfo
            {
                Ordinal = 1,
                Collation = "BINARY_CI",
                Field = new DbField("Age", false, false, true, typeof(int), 4, 10, 0, "int")
            });

            // Act
            var actual = composer.ComposeCreateTable(schema);

            // Assert
            Assert.IsFalse(actual.Contains("COLLATE", StringComparison.Ordinal));
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeCreateTableWithUnnamedPrimaryKey()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var schema = new TableSchema("Person", null);
            schema.Columns.Add(GetColumn("Id", "int", typeof(int), 1, false));
            schema.PrimaryKey = new PrimaryKeyInfo(null) { Columns = { "Id" } };

            // Act
            var actual = composer.ComposeCreateTable(schema);

            // Assert
            StringAssert.Contains(actual, "    PRIMARY KEY (\"Id\")", StringComparison.Ordinal);
            Assert.IsFalse(actual.Contains("CONSTRAINT", StringComparison.Ordinal));
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeCreateTableWithCompositePrimaryKey()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var schema = new TableSchema("OrderLine", null);
            schema.Columns.Add(GetColumn("OrderId", "int", typeof(int), 1, false));
            schema.Columns.Add(GetColumn("LineNumber", "int", typeof(int), 2, false));
            schema.PrimaryKey = new PrimaryKeyInfo("PK_OrderLine") { Columns = { "OrderId", "LineNumber" } };

            // Act
            var actual = composer.ComposeCreateTable(schema);

            // Assert
            StringAssert.Contains(actual, "PRIMARY KEY (\"OrderId\", \"LineNumber\")", StringComparison.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeCreateTableWithoutPrimaryKey()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var schema = new TableSchema("NoKey", null);
            schema.Columns.Add(GetColumn("Value", "varchar", typeof(string), 1));

            // Act
            var actual = composer.ComposeCreateTable(schema);

            // Assert
            Assert.IsFalse(actual.Contains("PRIMARY KEY", StringComparison.Ordinal));
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeCreateTableQuotesTheIdentifiers()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var schema = new TableSchema("Odd\"Table", null);
            schema.Columns.Add(GetColumn("Odd\"Column", "int", typeof(int), 1));

            // Act
            var actual = composer.ComposeCreateTable(schema);

            // Assert
            StringAssert.Contains(actual, "\"Odd\"\"Table\"", StringComparison.Ordinal);
            StringAssert.Contains(actual, "\"Odd\"\"Column\"", StringComparison.Ordinal);
        }

        [TestMethod]
        public void ThrowExceptionOnFirebirdSchemaComposerComposeCreateTableIfTheSchemaIsNull()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();

            // Act/Assert
            Assert.Throws<ArgumentNullException>(() => composer.ComposeCreateTable(null));
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeCreateTableWithNamedPrimaryKey()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var schema = new TableSchema("Product", null);
            schema.Columns.Add(GetColumn("Id", "int", typeof(int), 1, false));
            schema.PrimaryKey = new PrimaryKeyInfo("PK_Product") { IsClustered = false, Columns = { "Id" } };

            // Act
            var actual = composer.ComposeCreateTable(schema);

            // Assert
            StringAssert.Contains(actual, "CONSTRAINT \"PK_Product\" PRIMARY KEY (\"Id\")", StringComparison.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeCreateTableWithClusteredPrimaryKeyByDefault()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var schema = new TableSchema("Product", null);
            schema.Columns.Add(GetColumn("Id", "int", typeof(int), 1, false));
            schema.PrimaryKey = new PrimaryKeyInfo("PK_Product") { Columns = { "Id" } };

            // Act
            var actual = composer.ComposeCreateTable(schema);

            // Assert
            StringAssert.Contains(actual, "CONSTRAINT \"PK_Product\" PRIMARY KEY (\"Id\")", StringComparison.Ordinal);
        }

        #endregion

        #region ComposeCreateIndex

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeCreateIndex()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var index = new IndexInfo("IX_Person_Name") { Columns = { "Name" } };

            // Act
            var actual = composer.ComposeCreateIndex("Person", index);

            // Assert
            Assert.AreEqual("CREATE INDEX \"IX_Person_Name\" ON \"Person\" (\"Name\")", actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeCreateIndexWithUniqueAndIncludedColumns()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var index = new IndexInfo("IX_Person_Name")
            {
                IsUnique = true,
                Columns = { "Name", "Age" },
                IncludedColumns = { "Salary", "CountryId" }
            };

            // Act
            var actual = composer.ComposeCreateIndex("\"Person\"", index);
            var expected = "CREATE UNIQUE INDEX \"IX_Person_Name\" ON \"Person\" (\"Name\", \"Age\")";

            // Assert
            Assert.AreEqual(expected, actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void ThrowExceptionOnFirebirdSchemaComposerComposeCreateIndexIfTheIndexIsNull()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();

            // Act/Assert
            Assert.Throws<ArgumentNullException>(() => composer.ComposeCreateIndex("Person", null));
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeCreateIndexWithClusteredIndex()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var index = new IndexInfo("CIX_Product_Code") { IsUnique = true, IsClustered = true, Columns = { "Code" } };

            // Act
            var actual = composer.ComposeCreateIndex("Product", index);

            // Assert
            Assert.AreEqual("CREATE UNIQUE INDEX \"CIX_Product_Code\" ON \"Product\" (\"Code\")", actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeCreateIndexWithNonUniqueClusteredIndex()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var index = new IndexInfo("CIX") { IsClustered = true, Columns = { "Code" } };

            // Act
            var actual = composer.ComposeCreateIndex("Product", index);

            // Assert
            Assert.AreEqual("CREATE INDEX \"CIX\" ON \"Product\" (\"Code\")", actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeCreateIndexIgnoresTheDirectionThatIsNotForTheWholeIndex()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var index = new IndexInfo("IX_Product_Category_Price")
            {
                Columns = { "Category", "Price" },
                DescendingColumns = { "Price" },
                IncludedColumns = { "Name" }
            };

            // Act
            var actual = composer.ComposeCreateIndex("Product", index);
            var expected = "CREATE INDEX \"IX_Product_Category_Price\" ON \"Product\" (\"Category\", \"Price\")";

            // Assert
            Assert.AreEqual(expected, actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeCreateIndexWithDescendingKey()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var index = new IndexInfo("IX_Product_Price") { Columns = { "Price" }, DescendingColumns = { "Price" } };

            // Act
            var actual = composer.ComposeCreateIndex("Product", index);

            // Assert
            Assert.AreEqual("CREATE DESCENDING INDEX \"IX_Product_Price\" ON \"Product\" (\"Price\")", actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeCreateIndexWithAllDescendingKeys()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var index = new IndexInfo("IX") { Columns = { "A", "B" }, DescendingColumns = { "A", "B" } };

            // Act
            var actual = composer.ComposeCreateIndex("T", index);

            // Assert
            Assert.AreEqual("CREATE DESCENDING INDEX \"IX\" ON \"T\" (\"A\", \"B\")", actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeCreateIndexWithFilter()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var index = new IndexInfo("IX_Product_Active_Name")
            {
                Columns = { "Name" },
                Filter = "(\"IsActive\"=(1))"
            };

            // Act
            var actual = composer.ComposeCreateIndex("Product", index);

            // Assert
            Assert.AreEqual("CREATE INDEX \"IX_Product_Active_Name\" ON \"Product\" (\"Name\")", actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeCreateIndexWithAllTheOptions()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var index = new IndexInfo("IX")
            {
                IsUnique = true,
                IsClustered = true,
                Columns = { "A", "B" },
                DescendingColumns = { "B" },
                IncludedColumns = { "C" },
                Filter = "(\"A\">(0))"
            };

            // Act
            var actual = composer.ComposeCreateIndex("T", index);

            // Assert
            Assert.AreEqual("CREATE UNIQUE INDEX \"IX\" ON \"T\" (\"A\", \"B\")", actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeCreateIndexIgnoresTheBlankFilter()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var index = new IndexInfo("IX") { Columns = { "A" }, Filter = "  " };

            // Act
            var actual = composer.ComposeCreateIndex("T", index);

            // Assert
            Assert.AreEqual("CREATE INDEX \"IX\" ON \"T\" (\"A\")", actual, StringComparer.Ordinal);
        }

        #endregion

        #region ComposeAddForeignKey

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeAddForeignKey()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var foreignKey = new ForeignKeyInfo("FK_Person_Country")
            {
                Columns = { "CountryId" },
                ReferencedTable = new TableInfo("Country", null),
                ReferencedColumns = { "Id" }
            };

            // Act
            var actual = composer.ComposeAddForeignKey("Person", foreignKey);
            var expected = "ALTER TABLE \"Person\" ADD CONSTRAINT \"FK_Person_Country\" FOREIGN KEY (\"CountryId\") REFERENCES \"Country\" (\"Id\")";

            // Assert
            Assert.AreEqual(expected, actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeAddForeignKeyWithRules()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var foreignKey = new ForeignKeyInfo("FK_Person_Country")
            {
                Columns = { "CountryId" },
                ReferencedTable = new TableInfo("Country", null),
                ReferencedColumns = { "Id" },
                DeleteRule = CopySchemaForeignKeyRule.SetNull,
                UpdateRule = CopySchemaForeignKeyRule.Cascade
            };

            // Act
            var actual = composer.ComposeAddForeignKey("Person", foreignKey);

            // Assert
            StringAssert.EndsWith(actual, "ON DELETE SET NULL ON UPDATE CASCADE", StringComparison.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeAddForeignKeyWithSetDefaultRule()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var foreignKey = new ForeignKeyInfo("FK")
            {
                Columns = { "CountryId" },
                ReferencedTable = new TableInfo("Country", null),
                ReferencedColumns = { "Id" },
                DeleteRule = CopySchemaForeignKeyRule.SetDefault
            };

            // Act
            var actual = composer.ComposeAddForeignKey("Person", foreignKey);

            // Assert
            StringAssert.EndsWith(actual, "ON DELETE SET DEFAULT", StringComparison.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeAddForeignKeyIgnoresTheRestrictRule()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var foreignKey = new ForeignKeyInfo("FK")
            {
                Columns = { "CountryId" },
                ReferencedTable = new TableInfo("Country", null),
                ReferencedColumns = { "Id" },
                DeleteRule = CopySchemaForeignKeyRule.Restrict,
                UpdateRule = CopySchemaForeignKeyRule.Restrict
            };

            // Act
            var actual = composer.ComposeAddForeignKey("Person", foreignKey);

            // Assert
            Assert.IsFalse(actual.Contains("ON DELETE", StringComparison.Ordinal));
            Assert.IsFalse(actual.Contains("ON UPDATE", StringComparison.Ordinal));
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeAddForeignKeyWithCompositeColumns()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var foreignKey = new ForeignKeyInfo("FK_Line_Order")
            {
                Columns = { "OrderId", "LineNumber" },
                ReferencedTable = new TableInfo("OrderLine", null),
                ReferencedColumns = { "OrderId", "LineNumber" }
            };

            // Act
            var actual = composer.ComposeAddForeignKey("Shipment", foreignKey);

            // Assert
            StringAssert.Contains(actual, "FOREIGN KEY (\"OrderId\", \"LineNumber\") REFERENCES \"OrderLine\" (\"OrderId\", \"LineNumber\")", StringComparison.Ordinal);
        }

        [TestMethod]
        public void ThrowExceptionOnFirebirdSchemaComposerComposeAddForeignKeyIfTheForeignKeyIsNull()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();

            // Act/Assert
            Assert.Throws<ArgumentNullException>(() => composer.ComposeAddForeignKey("Person", null));
        }

        #endregion

        #region ComposeAddColumn

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeAddColumn()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var column = GetColumn("Nickname", "varchar", typeof(string), 1, true, 50);

            // Act
            var actual = composer.ComposeAddColumn("Person", column);

            // Assert
            Assert.AreEqual("ALTER TABLE \"Person\" ADD \"Nickname\" VARCHAR(50)", actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeAddColumnWithDefault()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var column = GetColumn("Age", "int", typeof(int), 1, false);
            column.DefaultExpression = "0";

            // Act
            var actual = composer.ComposeAddColumn("Person", column);

            // Assert
            Assert.AreEqual("ALTER TABLE \"Person\" ADD \"Age\" INTEGER DEFAULT 0 NOT NULL", actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeAddColumnWithComputedColumn()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var column = GetColumn("NameUpper", "varchar", typeof(string), 1, true, 128);
            column.ComputedExpression = "upper(\"Name\")";

            // Act
            var actual = composer.ComposeAddColumn("Person", column);
            var expected = "ALTER TABLE \"Person\" ADD \"NameUpper\" VARCHAR(128) GENERATED ALWAYS AS (upper(\"Name\"))";

            // Assert
            Assert.AreEqual(expected, actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void ThrowExceptionOnFirebirdSchemaComposerComposeAddColumnIfTheColumnIsNull()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();

            // Act/Assert
            Assert.Throws<ArgumentNullException>(() => composer.ComposeAddColumn("Person", null));
        }

        #endregion

        #region ComposeDropTable

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeDropTable()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();

            // Act
            var actual = composer.ComposeDropTable("Person");

            // Assert
            Assert.AreEqual("EXECUTE BLOCK AS BEGIN IF (EXISTS (SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'Person')) THEN EXECUTE STATEMENT 'DROP TABLE \"Person\"'; END", actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeDropTableWithQuotedName()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();

            // Act
            var actual = composer.ComposeDropTable("\"Order Details\"");

            // Assert
            Assert.AreEqual("EXECUTE BLOCK AS BEGIN IF (EXISTS (SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'Order Details')) THEN EXECUTE STATEMENT 'DROP TABLE \"Order Details\"'; END", actual, StringComparer.Ordinal);
        }

        #endregion

        #region ComposeSchema

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeSchema()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var schema = GetPersonSchema();

            // Act
            var actual = composer.ComposeSchema(schema).ToList();

            // Assert
            Assert.AreEqual(3, actual.Count);
            StringAssert.StartsWith(actual[0], "CREATE TABLE \"Person\"", StringComparison.Ordinal);
            StringAssert.StartsWith(actual[1], "CREATE INDEX \"IX_Person_Name\" ON \"Person\"", StringComparison.Ordinal);
            StringAssert.StartsWith(actual[2], "ALTER TABLE \"Person\" ADD CONSTRAINT \"FK_Person_Country\"", StringComparison.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeSchemaWithOnlyColumns()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var schema = new TableSchema("NoKey", null);
            schema.Columns.Add(GetColumn("Value", "varchar", typeof(string), 1));

            // Act
            var actual = composer.ComposeSchema(schema).ToList();

            // Assert
            Assert.AreEqual(1, actual.Count);
        }

        [TestMethod]
        public void ThrowExceptionOnFirebirdSchemaComposerComposeSchemaIfTheSchemaIsNull()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();

            // Act/Assert
            Assert.Throws<ArgumentNullException>(() => composer.ComposeSchema(null));
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeSchemas()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var first = GetPersonSchema();
            var second = new TableSchema("Country", null);
            second.Columns.Add(GetColumn("Id", "int", typeof(int), 1, false));
            second.Indexes.Add(new IndexInfo("IX_Country_Id") { Columns = { "Id" } });

            // Act
            var actual = composer.ComposeSchemas(new[] { first, second }).ToList();

            // Assert
            Assert.AreEqual(5, actual.Count);
            StringAssert.StartsWith(actual[0], "CREATE TABLE \"Person\"", StringComparison.Ordinal);
            StringAssert.StartsWith(actual[1], "CREATE TABLE \"Country\"", StringComparison.Ordinal);
            StringAssert.StartsWith(actual[2], "CREATE INDEX \"IX_Person_Name\" ON \"Person\"", StringComparison.Ordinal);
            StringAssert.StartsWith(actual[3], "CREATE INDEX \"IX_Country_Id\" ON \"Country\"", StringComparison.Ordinal);
            StringAssert.StartsWith(actual[4], "ALTER TABLE \"Person\" ADD CONSTRAINT \"FK_Person_Country\"", StringComparison.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeSchemasCreatesTheForeignKeysAfterAllTheTables()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var a = new TableSchema("CycleA", null);
            a.Columns.Add(GetColumn("Id", "int", typeof(int), 1, false));
            a.Columns.Add(GetColumn("BId", "int", typeof(int), 2));
            a.ForeignKeys.Add(new ForeignKeyInfo("FK_CycleA_CycleB") { Columns = { "BId" }, ReferencedTable = new TableInfo("CycleB", null), ReferencedColumns = { "Id" } });
            var b = new TableSchema("CycleB", null);
            b.Columns.Add(GetColumn("Id", "int", typeof(int), 1, false));
            b.Columns.Add(GetColumn("AId", "int", typeof(int), 2));
            b.ForeignKeys.Add(new ForeignKeyInfo("FK_CycleB_CycleA") { Columns = { "AId" }, ReferencedTable = new TableInfo("CycleA", null), ReferencedColumns = { "Id" } });

            // Act
            var actual = composer.ComposeSchemas(new[] { a, b }).ToList();

            // Assert
            Assert.AreEqual(4, actual.Count);
            StringAssert.StartsWith(actual[0], "CREATE TABLE \"CycleA\"", StringComparison.Ordinal);
            StringAssert.StartsWith(actual[1], "CREATE TABLE \"CycleB\"", StringComparison.Ordinal);
            StringAssert.StartsWith(actual[2], "ALTER TABLE \"CycleA\" ADD CONSTRAINT \"FK_CycleA_CycleB\"", StringComparison.Ordinal);
            StringAssert.StartsWith(actual[3], "ALTER TABLE \"CycleB\" ADD CONSTRAINT \"FK_CycleB_CycleA\"", StringComparison.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeSchemasWithoutTables()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();

            // Act
            var actual = composer.ComposeSchemas(Enumerable.Empty<TableSchema>()).ToList();

            // Assert
            Assert.AreEqual(0, actual.Count);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeSchemasOfOneTableIsTheSameAsComposeSchema()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var schema = GetPersonSchema();

            // Act
            var actual = composer.ComposeSchemas(new[] { schema }).ToList();
            var expected = composer.ComposeSchema(schema).ToList();

            // Assert
            CollectionAssert.AreEqual(expected, actual);
        }

        [TestMethod]
        public void ThrowExceptionOnFirebirdSchemaComposerComposeSchemasIfTheSchemasAreNull()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();

            // Act/Assert
            Assert.Throws<ArgumentNullException>(() => composer.ComposeSchemas(null));
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeCreateTableWithNameThatNeedsQuoting()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var schema = new TableSchema("Odd.Name", null);
            schema.Columns.Add(GetColumn("Unit Price", "decimal", typeof(decimal), 1, false, null, 10, 2));

            // Act
            var actual = composer.ComposeCreateTable(schema);

            // Assert
            StringAssert.StartsWith(actual, "CREATE TABLE \"Odd.Name\" (", StringComparison.Ordinal);
            StringAssert.Contains(actual, "\"Unit Price\" DECIMAL(10,2) NOT NULL", StringComparison.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeCreateTableWithDoubleQuoteInTheNames()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var schema = new TableSchema("Weird\"Name", null);
            schema.Columns.Add(GetColumn("Id", "int", typeof(int), 1, false));

            // Act
            var actual = composer.ComposeCreateTable(schema);

            // Assert
            StringAssert.StartsWith(actual, "CREATE TABLE \"Weird\"\"Name\" (", StringComparison.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeAddForeignKeyWithNamesThatNeedQuoting()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var foreignKey = new ForeignKeyInfo("FK_OddChild_OddName")
            {
                Columns = { "ParentId" },
                ReferencedTable = new TableInfo("Odd.Name", null),
                ReferencedColumns = { "Id" }
            };

            // Act
            var actual = composer.ComposeAddForeignKey("\"Odd.Child\"", foreignKey);
            var expected = "ALTER TABLE \"Odd.Child\" ADD CONSTRAINT \"FK_OddChild_OddName\" FOREIGN KEY (\"ParentId\") REFERENCES \"Odd.Name\" (\"Id\")";

            // Assert
            Assert.AreEqual(expected, actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeSchemasWithNamesThatNeedQuoting()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var parent = new TableSchema("Odd.Name", null);
            parent.Columns.Add(GetColumn("Id", "int", typeof(int), 1, false));
            parent.Indexes.Add(new IndexInfo("IX_OddName_Id") { Columns = { "Id" } });
            var child = new TableSchema("Odd.Child", null);
            child.Columns.Add(GetColumn("ParentId", "int", typeof(int), 1, false));
            child.ForeignKeys.Add(new ForeignKeyInfo("FK_OddChild_OddName")
            {
                Columns = { "ParentId" },
                ReferencedTable = new TableInfo("Odd.Name", null),
                ReferencedColumns = { "Id" }
            });

            // Act
            var actual = composer.ComposeSchemas(new[] { child, parent }).ToList();

            // Assert
            Assert.AreEqual(4, actual.Count);
            StringAssert.StartsWith(actual[0], "CREATE TABLE \"Odd.Child\"", StringComparison.Ordinal);
            StringAssert.StartsWith(actual[1], "CREATE TABLE \"Odd.Name\"", StringComparison.Ordinal);
            Assert.AreEqual("CREATE INDEX \"IX_OddName_Id\" ON \"Odd.Name\" (\"Id\")", actual[2], StringComparer.Ordinal);
            StringAssert.Contains(actual[3], "ALTER TABLE \"Odd.Child\" ADD CONSTRAINT \"FK_OddChild_OddName\"", StringComparison.Ordinal);
            StringAssert.Contains(actual[3], "REFERENCES \"Odd.Name\" (\"Id\")", StringComparison.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeDropTableWithDoubleQuoteInTheName()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();

            // Act
            var actual = composer.ComposeDropTable("\"Weird\"\"Name\"");

            // Assert
            Assert.AreEqual("EXECUTE BLOCK AS BEGIN IF (EXISTS (SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'Weird\"Name')) THEN EXECUTE STATEMENT 'DROP TABLE \"Weird\"\"Name\"'; END", actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeCreateIndexWithTableNameThatNeedsQuoting()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();
            var index = new IndexInfo("IX") { Columns = { "Id" } };

            // Act
            var actual = composer.ComposeCreateIndex("\"Odd.Name\"", index);

            // Assert
            Assert.AreEqual("CREATE INDEX \"IX\" ON \"Odd.Name\" (\"Id\")", actual, StringComparer.Ordinal);
        }

        #endregion

        #region ComposeTypeName

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeTypeNameForSizedUnicodeString()
        {
            Assert.AreEqual("VARCHAR(128)", ComposeTypeName("varchar", typeof(string), 128), StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeTypeNameForUnicodeStringWithMaxSize()
        {
            Assert.AreEqual("BLOB SUB_TYPE TEXT", ComposeTypeName("varchar", typeof(string), -1), StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeTypeNameForUnicodeStringWithoutSize()
        {
            Assert.AreEqual("BLOB SUB_TYPE TEXT", ComposeTypeName("varchar", typeof(string)), StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeTypeNameForVarChar()
        {
            Assert.AreEqual("VARCHAR(50)", ComposeTypeName("varchar", typeof(string), 50), StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeTypeNameForFixedLengthCharacters()
        {
            Assert.AreEqual("CHAR(10)", ComposeTypeName("char", typeof(string), 10), StringComparer.Ordinal);
            Assert.AreEqual("CHAR(4)", ComposeTypeName("char", typeof(string), 4), StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeTypeNameForFixedLengthCharactersWithoutSize()
        {
            Assert.AreEqual("CHAR(1)", ComposeTypeName("char", typeof(string)), StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeTypeNameForBinary()
        {
            Assert.AreEqual("BINARY(16)", ComposeTypeName("binary", typeof(byte[]), 16), StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeTypeNameForVarBinary()
        {
            Assert.AreEqual("VARBINARY(256)", ComposeTypeName("varbinary", typeof(byte[]), 256), StringComparer.Ordinal);
            Assert.AreEqual("BLOB SUB_TYPE BINARY", ComposeTypeName("varbinary", typeof(byte[]), -1), StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeTypeNameForDecimal()
        {
            Assert.AreEqual("DECIMAL(18,2)", ComposeTypeName("decimal", typeof(decimal), 9, 18, 2), StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeTypeNameForNumericWithoutPrecision()
        {
            Assert.AreEqual("DECIMAL(18,6)", ComposeTypeName("decimal", typeof(decimal)), StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeTypeNameForTemporalTypesWithScale()
        {
            Assert.AreEqual("TIMESTAMP", ComposeTypeName("datetime", typeof(DateTime), scale: 3), StringComparer.Ordinal);
            Assert.AreEqual("TIMESTAMP", ComposeTypeName("timestamp", typeof(DateTime), scale: 9), StringComparer.Ordinal);
            Assert.AreEqual("TIME", ComposeTypeName("time", typeof(TimeSpan), scale: 5), StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeTypeNameForTemporalTypesWithoutScale()
        {
            Assert.AreEqual("TIMESTAMP", ComposeTypeName("datetime", typeof(DateTime)), StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeTypeNameForSimpleTypes()
        {
            Assert.AreEqual("INTEGER", ComposeTypeName("int", typeof(int)), StringComparer.Ordinal);
            Assert.AreEqual("BIGINT", ComposeTypeName("bigint", typeof(long)), StringComparer.Ordinal);
            Assert.AreEqual("BOOLEAN", ComposeTypeName("bit", typeof(bool)), StringComparer.Ordinal);
            Assert.AreEqual("BINARY(16)", ComposeTypeName("uuid", typeof(Guid)), StringComparer.Ordinal);
            Assert.AreEqual("DOUBLE PRECISION", ComposeTypeName("double", typeof(double)), StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeTypeNameIsCaseInsensitive()
        {
            Assert.AreEqual("INTEGER", ComposeTypeName("INT", typeof(int)), StringComparer.Ordinal);
            Assert.AreEqual("VARCHAR(20)", ComposeTypeName("VarChar", typeof(string), 20), StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeTypeNameForTheTypesOfOtherDatabaseEngines()
        {
            Assert.AreEqual("BOOLEAN", ComposeTypeName("boolean", typeof(bool)), StringComparer.Ordinal);
            Assert.AreEqual("BINARY(16)", ComposeTypeName("uuid", typeof(Guid)), StringComparer.Ordinal);
            Assert.AreEqual("BLOB SUB_TYPE TEXT", ComposeTypeName("varchar", typeof(string)), StringComparer.Ordinal);
            Assert.AreEqual("BLOB SUB_TYPE BINARY", ComposeTypeName("varbinary", typeof(byte[])), StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeTypeNameFallsBackToTheClientTypeIfThereIsNoDatabaseType()
        {
            Assert.AreEqual("BIGINT", ComposeTypeName(null, typeof(long)), StringComparer.Ordinal);
            Assert.AreEqual("TIMESTAMP", ComposeTypeName(null, typeof(DateTime)), StringComparer.Ordinal);
            Assert.AreEqual("VARCHAR(20)", ComposeTypeName(null, typeof(string), 20), StringComparer.Ordinal);
            Assert.AreEqual("BLOB SUB_TYPE TEXT", ComposeTypeName(null, typeof(object)), StringComparer.Ordinal);
        }

        [TestMethod]
        public void ThrowExceptionOnFirebirdSchemaComposerComposeTypeNameIfTheColumnIsNull()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();

            // Act/Assert
            Assert.Throws<ArgumentNullException>(() => composer.ComposeTypeName(null));
        }

        [TestMethod]
        public void ThrowExceptionOnFirebirdSchemaComposerComposeTypeNameIfTheColumnHasNoField()
        {
            // Setup
            var composer = new FirebirdSchemaComposer();

            // Act/Assert
            Assert.Throws<ArgumentException>(() => composer.ComposeTypeName(new ColumnInfo()));
        }

        #endregion

        #region Interface

        [TestMethod]
        public void TestFirebirdSchemaComposerIsASchemaComposer()
        {
            // Act
            var composer = new FirebirdSchemaComposer();

            // Assert
            Assert.IsInstanceOfType<ISchemaComposer>(composer);
        }

        #endregion

        #region ComposeName / Exists

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeName()
        {
            // Act/Assert
            var composer = new FirebirdSchemaComposer();
            Assert.AreEqual("Person", composer.ComposeName(new TableInfo("Person", null)));
            Assert.AreEqual("\"Odd.Name\"", composer.ComposeName(new TableInfo("Odd.Name", null)));
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeNameWithoutSchema()
        {
            // Act/Assert
            Assert.AreEqual("Person", new FirebirdSchemaComposer().ComposeName(new TableInfo("Person", null)));
        }

        [TestMethod]
        public void ThrowExceptionOnFirebirdSchemaComposerComposeNameIfTheTableIsNull()
        {
            // Act/Assert
            Assert.Throws<ArgumentNullException>(() => new FirebirdSchemaComposer().ComposeName(null));
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeTableExists()
        {
            // Act/Assert
            Assert.AreEqual("SELECT CASE WHEN EXISTS (SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'Person') THEN 1 ELSE 0 END FROM RDB$DATABASE", new FirebirdSchemaComposer().ComposeTableExists("Person"));
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeColumnExists()
        {
            // Act/Assert
            Assert.AreEqual("SELECT CASE WHEN EXISTS (SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'Person' AND RDB$FIELD_NAME = 'Name') THEN 1 ELSE 0 END FROM RDB$DATABASE", new FirebirdSchemaComposer().ComposeColumnExists("Person", "Name"));
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeIndexExists()
        {
            // Act/Assert
            Assert.AreEqual("SELECT CASE WHEN EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$RELATION_NAME = 'Person' AND RDB$INDEX_NAME = 'IX_Person_Name') THEN 1 ELSE 0 END FROM RDB$DATABASE", new FirebirdSchemaComposer().ComposeIndexExists("Person", "IX_Person_Name"));
        }

        [TestMethod]
        public void TestFirebirdSchemaComposerComposeExistsEscapesTheSingleQuotes()
        {
            // Act
            var composer = new FirebirdSchemaComposer();

            // Assert
            StringAssert.Contains(composer.ComposeColumnExists("Person", "O'Brien"), "O''Brien", StringComparison.Ordinal);
            StringAssert.Contains(composer.ComposeIndexExists("Person", "IX_O'Brien"), "IX_O''Brien", StringComparison.Ordinal);
            StringAssert.Contains(composer.ComposeTableExists("\"O'Brien\""), "O''Brien", StringComparison.Ordinal);
        }

        #endregion
    }
}
