using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.IO;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using MySql.Data.MySqlClient;

namespace RepoDb.MySql.BulkOperations
{
    // This is totally generated by AI - 2026/08/08 10:33 CET
    // Used Claude Sonnet 5.0

    /// <summary>
    /// Describes a single source-ordinal-to-destination-column pairing for <see cref="MySqlBulkCopy"/>.
    /// Mirrors MySqlConnector's own <c>MySqlBulkCopyColumnMapping</c> shape (constructor and property names)
    /// closely enough that <c>Base/WriteToServer.cs</c> - originally written against that MySqlConnector-only
    /// type - needed no changes at all beyond the unqualified <c>MySqlBulkCopyColumnMapping</c>/<c>MySqlBulkCopy</c>
    /// references now resolving to this file's types instead (both are already in scope there via the
    /// existing <c>using RepoDb.MySql.BulkOperations;</c>).
    /// </summary>
    internal sealed class MySqlBulkCopyColumnMapping
    {
        /// <summary>
        /// Creates a new instance of <see cref="MySqlBulkCopyColumnMapping"/>.
        /// </summary>
        /// <param name="sourceOrdinal">The ordinal of the source column - within whatever <see cref="IDataReader"/>/<see cref="DataRow"/> is handed to <see cref="MySqlBulkCopy"/> - that supplies this mapping's value.</param>
        /// <param name="destinationColumn">
        /// The raw (unquoted) destination column name. <see cref="MySqlBulkCopy"/> back-tick-quotes this
        /// itself before handing it to <see cref="MySqlBulkLoader"/> - same contract as MySqlConnector's own
        /// <c>MySqlBulkCopy</c>, which callers in <c>WriteToServer.cs</c> already rely on (see its "MySqlBulkCopy
        /// back-tick-quotes DestinationColumn itself" remarks).
        /// </param>
        public MySqlBulkCopyColumnMapping(int sourceOrdinal,
            string destinationColumn)
        {
            SourceOrdinal = sourceOrdinal;
            DestinationColumn = destinationColumn;
        }

        /// <summary>
        /// Gets the ordinal of the source column that supplies this mapping's value.
        /// </summary>
        public int SourceOrdinal { get; }

        /// <summary>
        /// Gets the raw (unquoted) destination column name.
        /// </summary>
        public string DestinationColumn { get; }
    }

    /// <summary>
    /// A drop-in stand-in for MySqlConnector's <c>MySqlBulkCopy</c>, built on top of <c>MySql.Data</c>'s
    /// <see cref="MySqlBulkLoader"/> - the only genuine bulk-load primitive <c>MySql.Data</c> ships. Exists
    /// purely so <c>Base/WriteToServer.cs</c> (a near-verbatim copy of the MySqlConnector provider's own
    /// <c>WriteToServer.cs</c>) keeps compiling and behaving the same way against <c>MySql.Data</c>, without
    /// any of the calling code above it (<c>BulkInsert.cs</c>/<c>BulkMerge.cs</c>/<c>BulkUpdate.cs</c>/etc.,
    /// or any of RepoDB's other DB-provider bulk packages) needing to know the difference.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>Why a temp file.</b> <see cref="MySqlBulkLoader"/> only knows how to load from a file
    /// (<see cref="MySqlBulkLoader.FileName"/> + <see cref="MySqlBulkLoader.Local"/> for
    /// <c>LOAD DATA LOCAL INFILE</c>) - unlike MySqlConnector's real <c>MySqlBulkCopy</c>, it has no
    /// reader-streaming <c>WriteToServer(IDataReader)</c> overload. So every write here first serializes its
    /// rows to a temporary, tab-delimited file, hands that file to <see cref="MySqlBulkLoader"/>, then deletes
    /// it in a <c>finally</c> block. Tab was chosen over comma as the field terminator specifically to avoid
    /// CSV-style quoting: an <c>NVARCHAR</c> value containing a literal comma is common, a literal tab in
    /// ordinary text is rare, so a plain backslash-escape of the handful of characters that matter (backslash
    /// itself, tab, CR, LF) is enough - no quoted-field parsing needed on either side.
    /// </para>
    /// <para>
    /// <b>Why no "ignored source column" handling.</b> MySqlConnector's real <c>MySqlBulkCopy</c> must walk
    /// every ordinal of whatever reader it's given up to that reader's own <see cref="IDataReader.FieldCount"/>
    /// - even ones with no entry in <see cref="ColumnMappings"/> - because it streams the wire protocol
    /// positionally and can't simply skip a field mid-packet (see the remarks on <c>ColumnFilteredDataReader</c>
    /// for what happens when a caller doesn't route around that). This class has no such constraint: it builds
    /// the entire temp file itself before <see cref="MySqlBulkLoader"/> ever touches it, so it only ever reads
    /// the exact ordinals named in <see cref="ColumnMappings"/> - an unmapped source column is simply never
    /// read, not walked-and-ignored.
    /// </para>
    /// <para>
    /// <b>Transactions.</b> Like MySqlConnector's real <c>MySqlBulkCopy</c> as used by this package (every
    /// call site here only ever does <c>new MySqlBulkCopy(connection)</c>, never the transaction-accepting
    /// overload), this class does not associate itself with any ambient <see cref="MySqlTransaction"/> either
    /// - <c>LOAD DATA LOCAL INFILE</c> commits independently, consistent with the rest of this package's
    /// documented transaction-boundary behavior.
    /// </para>
    /// </remarks>
    internal sealed class MySqlBulkCopy
    {
        private readonly MySqlConnection connection;

        /// <summary>
        /// Creates a new instance of <see cref="MySqlBulkCopy"/> bound to <paramref name="connection"/>.
        /// </summary>
        /// <param name="connection">The connection <see cref="MySqlBulkLoader"/> will load through.</param>
        public MySqlBulkCopy(MySqlConnection connection)
        {
            this.connection = connection;
        }

        /// <summary>
        /// Gets or sets the destination table name. Expected to already be correctly quoted by the caller
        /// (every call site in <c>WriteToServer.cs</c> sets this from <c>tableName.AsQuoted(true, dbSetting)</c>)
        /// - passed straight through to <see cref="MySqlBulkLoader.TableName"/> unmodified.
        /// </summary>
        public string DestinationTableName { get; set; }

        /// <summary>
        /// Gets or sets the bulk-load timeout, in seconds. Mapped directly to <see cref="MySqlBulkLoader.Timeout"/>.
        /// </summary>
        public int BulkCopyTimeout { get; set; } = 30;

        /// <summary>
        /// Gets the source-ordinal-to-destination-column mappings that determine both which columns get
        /// written and the column order of the temp file built for <see cref="MySqlBulkLoader"/>.
        /// </summary>
        public List<MySqlBulkCopyColumnMapping> ColumnMappings { get; } = new();

        /// <summary>
        /// The character used to separate fields in the temp file. Kept out of CSV-comma territory
        /// deliberately - see the remarks on <see cref="MySqlBulkCopy"/> for why.
        /// </summary>
        private const string FieldTerminator = "\t";

        /// <summary>
        /// The character used to separate rows (lines) in the temp file. Deliberately a bare <c>\n</c>
        /// (rather than <see cref="Environment.NewLine"/>) so the file's actual bytes are identical
        /// regardless of the OS this code happens to run on.
        /// </summary>
        private const string LineTerminator = "\n";

        #region WriteToServer

        /// <summary>
        /// Writes every remaining row of <paramref name="reader"/> to <see cref="DestinationTableName"/>.
        /// </summary>
        /// <param name="reader">
        /// The source reader. Read positionally via each mapping's <see cref="MySqlBulkCopyColumnMapping.SourceOrdinal"/> -
        /// see the remarks on <see cref="MySqlBulkCopy"/> for why no other ordinal of this reader is ever touched.
        /// </param>
        /// <returns>The number of rows <see cref="MySqlBulkLoader"/> reports having loaded.</returns>
        public int WriteToServer(IDataReader reader) =>
            WriteToServerAsync(reader, CancellationToken.None).GetAwaiter().GetResult();

        /// <summary>
        /// Asynchronous counterpart of <see cref="WriteToServer(IDataReader)"/>.
        /// </summary>
        public async Task<int> WriteToServerAsync(IDataReader reader,
            CancellationToken cancellationToken = default)
        {
            var filePath = GetTempFilePath();
            try
            {
                using (var writer = CreateFileWriter(filePath))
                {
                    while (reader.Read())
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        WriteRow(writer, ordinal => reader.IsDBNull(ordinal) ? null : reader.GetValue(ordinal));
                    }
                }
                return await LoadAsync(filePath, cancellationToken);
            }
            finally
            {
                DeleteTempFile(filePath);
            }
        }

        /// <summary>
        /// Writes <paramref name="rows"/> to <see cref="DestinationTableName"/>.
        /// </summary>
        /// <param name="rows">The source rows, read positionally via each mapping's <see cref="MySqlBulkCopyColumnMapping.SourceOrdinal"/> - i.e. the real <see cref="DataTable"/> column index, not the mapping's position in <see cref="ColumnMappings"/> (those can legitimately diverge - see <c>WriteToServer.cs</c>'s remarks on why the ordinal must come from <c>DataTable.Columns.IndexOf</c>).</param>
        /// <param name="columnCount">Unused beyond a defensive bounds check - <see cref="ColumnMappings"/> alone already determines exactly which columns get written.</param>
        /// <returns>The number of rows <see cref="MySqlBulkLoader"/> reports having loaded.</returns>
        public int WriteToServer(DataRow[] rows,
            int columnCount) =>
            WriteToServerAsync(rows, columnCount, CancellationToken.None).GetAwaiter().GetResult();

        /// <summary>
        /// Asynchronous counterpart of <see cref="WriteToServer(DataRow[], int)"/>.
        /// </summary>
        public async Task<int> WriteToServerAsync(DataRow[] rows,
            int columnCount,
            CancellationToken cancellationToken = default)
        {
            var filePath = GetTempFilePath();
            try
            {
                using (var writer = CreateFileWriter(filePath))
                {
                    foreach (var row in rows ?? Array.Empty<DataRow>())
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        WriteRow(writer, ordinal => ordinal < columnCount && ordinal < row.Table.Columns.Count && !row.IsNull(ordinal) ? row[ordinal] : null);
                    }
                }
                return await LoadAsync(filePath, cancellationToken);
            }
            finally
            {
                DeleteTempFile(filePath);
            }
        }

        #endregion

        #region Helpers

        /// <summary>
        /// Writes one row to <paramref name="writer"/> - one tab-separated field per entry in
        /// <see cref="ColumnMappings"/>, in that order, terminated by <see cref="LineTerminator"/>.
        /// </summary>
        /// <param name="writer">The temp file writer.</param>
        /// <param name="getValue">Resolves a source ordinal to its raw CLR value (or <see langword="null"/> for a database <c>NULL</c>).</param>
        private void WriteRow(StreamWriter writer,
            Func<int, object> getValue)
        {
            for (var i = 0; i < ColumnMappings.Count; i++)
            {
                if (i > 0)
                {
                    writer.Write(FieldTerminator);
                }
                writer.Write(FormatValue(getValue(ColumnMappings[i].SourceOrdinal)));
            }
            writer.Write(LineTerminator);
        }

        /// <summary>
        /// Formats a single CLR value for the temp file, using <c>LOAD DATA</c>'s own documented escape
        /// sequences (<c>\N</c> for <c>NULL</c>, <c>\\</c>/<c>\t</c>/<c>\n</c>/<c>\r</c> for the literal
        /// characters that would otherwise be misread as field/line structure).
        /// </summary>
        private static string FormatValue(object value)
        {
            if (value == null || value is DBNull)
            {
                // LOAD DATA's documented marker for SQL NULL - only recognized when unquoted, which every
                // field written by this class already is (no field-quotation character is configured).
                return "\\N";
            }

            return value switch
            {
                Guid guid => guid.ToString("D", CultureInfo.InvariantCulture),
                DateTime dateTime => dateTime.ToString("yyyy-MM-dd HH:mm:ss.ffffff", CultureInfo.InvariantCulture),
                bool boolean => boolean ? "1" : "0",
                // No BLOB/BINARY column is exercised by this package's current entities/tests - a hex string
                // is a reasonable, if incomplete, best effort (a real binary round-trip would additionally
                // need a `SET destCol = UNHEX(@destCol)` expression, which MySqlBulkLoader.Expressions
                // supports but this class does not currently wire up).
                byte[] bytes => Convert.ToHexString(bytes),
                IFormattable formattable => Escape(formattable.ToString(null, CultureInfo.InvariantCulture)),
                _ => Escape(value.ToString()),
            };
        }

        /// <summary>
        /// Backslash-escapes the handful of characters <c>LOAD DATA</c> would otherwise misinterpret as field
        /// structure: a literal backslash, tab (the field terminator), and CR/LF (the line terminator).
        /// </summary>
        private static string Escape(string value)
        {
            if (string.IsNullOrEmpty(value))
            {
                return value ?? string.Empty;
            }

            StringBuilder builder = null;
            for (var i = 0; i < value.Length; i++)
            {
                var ch = value[i];
                var escaped = ch switch
                {
                    '\\' => "\\\\",
                    '\t' => "\\t",
                    '\n' => "\\n",
                    '\r' => "\\r",
                    _ => null,
                };
                if (escaped != null)
                {
                    builder ??= new StringBuilder(value, 0, i, value.Length + 8);
                    builder.Append(escaped);
                }
                else
                {
                    builder?.Append(ch);
                }
            }
            return builder?.ToString() ?? value;
        }

        /// <summary>
        /// Runs the configured <see cref="MySqlBulkLoader"/> against the temp file built by
        /// <see cref="WriteRow"/>, back-tick-quoting each mapped destination column along the way - the
        /// counterpart to <see cref="DestinationTableName"/> already arriving pre-quoted (see its remarks).
        /// </summary>
        private async Task<int> LoadAsync(string filePath,
            CancellationToken cancellationToken)
        {
            var bulkLoader = new MySqlBulkLoader(connection)
            {
                TableName = DestinationTableName,
                FileName = filePath,
                Local = true,
                FieldTerminator = FieldTerminator,
                LineTerminator = LineTerminator,
                NumberOfLinesToSkip = 0,
                CharacterSet = "utf8mb4",
                Timeout = BulkCopyTimeout,
            };
            foreach (var mapping in ColumnMappings)
            {
                bulkLoader.Columns.Add(QuoteIdentifier(mapping.DestinationColumn));
            }

            cancellationToken.ThrowIfCancellationRequested();
            return await bulkLoader.LoadAsync();
        }

        /// <summary>
        /// Back-tick-quotes a raw identifier, doubling any embedded back-tick per MySQL's identifier-quoting
        /// escape rule.
        /// </summary>
        private static string QuoteIdentifier(string identifier) =>
            $"`{identifier?.Replace("`", "``")}`";

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        private static string GetTempFilePath() => Path.GetTempFileName();

        /// <summary>
        /// 
        /// </summary>
        /// <param name="filePath"></param>
        /// <returns></returns>
        private static StreamWriter CreateFileWriter(string filePath) =>
            new(filePath, false, new UTF8Encoding(false));

        /// <summary>
        /// 
        /// </summary>
        /// <param name="filePath"></param>
        private static void DeleteTempFile(string filePath)
        {
            try
            {
                File.Delete(filePath);
            }
            catch (IOException)
            {
                // Best-effort cleanup - a lingering temp file is a minor annoyance, not worth failing an
                // otherwise-successful (or already-failed) bulk load over.
            }
        }

        #endregion
    }
}
