<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>RepoDb.Benchmarks.SqlServer</AssemblyName>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <LangVersion>preview</LangVersion>
    <Nullable>annotations</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8"/>
    <PackageReference Include="Dapper" Version="2.1.79"/>
    <PackageReference Include="Dapper.Contrib" Version="2.0.78"/>
    <PackageReference Include="NHibernate" Version="5.7.0"/>
    <PackageReference Include="System.Linq.Async" Version="7.0.1"/>
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11"/>
    <PackageReference Remove="System.Linq.Async" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Providers\RepoDb.SqlServer.BulkOperations\RepoDb.SqlServer.BulkOperations\RepoDb.SqlServer.BulkOperations.csproj" />
    <ProjectReference Include="..\..\..\Providers\RepoDb.PostgreSql\RepoDb.PostgreSql\RepoDb.PostgreSql.csproj" />
    <ProjectReference Include="..\..\..\Providers\RepoDb.SqlServer\RepoDb.SqlServer\RepoDb.SqlServer.csproj" />
  </ItemGroup>
</Project>