<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Title>RepoDb.Turso</Title>
    <AssemblyName>RepoDb.Turso</AssemblyName>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <LangVersion>preview</LangVersion>
    <Nullable>annotations</Nullable>
    <Description>A hybrid .NET ORM library for Turso (using Turso.Data.Sqlite.Provider).</Description>
    <PackageTags>orm hybrid-orm micro-orm sqlite turso libsql</PackageTags>
    <RepositoryUrl>https://github.com/mamoreau-devolutions/RepoDB/tree/master/src/Providers/RepoDb.Turso</RepositoryUrl>
    <PackageProjectUrl>https://github.com/mamoreau-devolutions/RepoDB/tree/master/src/Providers/RepoDb.Turso</PackageProjectUrl>
    <PackageIcon>SQLite.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Properties\**" />
    <EmbeddedResource Remove="Properties\**" />
    <None Remove="Properties\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Turso.Data.Sqlite.Provider" Version="0.8.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\RepoDb.Core\RepoDb\RepoDb.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\..\..\LICENSE.txt" Pack="True" PackagePath="\" />
    <None Include="..\README.md" Pack="True" PackagePath="\" />
    <None Include="..\SQLite.png" Pack="True" PackagePath="\" />
  </ItemGroup>
</Project>