<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>RepoDb.Vertica.BulkOperations.IntegrationTests</AssemblyName>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <EnableMSTestRunner>true</EnableMSTestRunner>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.2.3" />
    <PackageReference Include="Vertica.Data" Version="24.3.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\RepoDb.Core\RepoDb\RepoDb.csproj" />
    <ProjectReference Include="..\..\RepoDb.Vertica\RepoDb.Vertica\RepoDb.Vertica.csproj" />
    <ProjectReference Include="..\RepoDb.Vertica.BulkOperations\RepoDb.Vertica.BulkOperations.csproj" />
  </ItemGroup>
</Project>
