#region Copyright Attributions

// Copyright (c) 2026 Michael Camara Pendon.
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for full license information.

#endregion

using System;
using System.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using RepoDb.Schema.Enumerations;
using RepoDb.Schema.Models;

namespace RepoDb.Schema.SapHana.UnitTests
{
    [TestClass]
    public class SapHanaSchemaComposerTest
    {
        #region Helpers

        private static ColumnInfo GetColumn(string name,
            string databaseType,
            Type type,
            int ordinal,
            bool isNullable = true,
            int? size = null,
            byte? precision = null,
            byte? scale = null) =>
            new ColumnInfo
            {
                Ordinal = ordinal,
                Field = new DbField(name, false, false, isNullable, type, size, precision, scale, databaseType)
            };

        private static string ComposeTypeName(string databaseType,
            Type type,
            int? size = null,
            byte? precision = null,
            byte? scale = null) =>
            new SapHanaSchemaComposer().ComposeTypeName(GetColumn("Column", databaseType, type, 1, true, size, precision, scale));

        private static TableSchema GetPersonSchema()
        {
            var schema = new TableSchema("Person", "dbo");
            schema.Columns.Add(new ColumnInfo
            {
                Ordinal = 1,
                IdentitySeed = 10,
                IdentityIncrement = 5,
                Field = new DbField("Id", true, true, false, typeof(long), 8, 19, 0, "bigint")
            });
            schema.Columns.Add(new ColumnInfo
            {
                Ordinal = 2,
                Collation = "BINARY_CI",
                Field = new DbField("Name", false, false, false, typeof(string), 128, 0, 0, "varchar")
            });
            schema.Columns.Add(new ColumnInfo
            {
                Ordinal = 3,
                DefaultExpression = "0",
                Field = new DbField("Age", false, false, true, typeof(int), 4, 10, 0, "int", true)
            });
            schema.PrimaryKey = new PrimaryKeyInfo("PK_Person") { Columns = { "Id" } };
            schema.UniqueConstraints.Add(new UniqueConstraintInfo("UQ_Person_Name") { Columns = { "Name" } });
            schema.CheckConstraints.Add(new CheckConstraintInfo("CK_Person_Age") { Expression = "(\"Age\" >= 0)" });
            schema.Indexes.Add(new IndexInfo("IX_Person_Name") { Columns = { "Name" }, IncludedColumns = { "Age" } });
            schema.ForeignKeys.Add(new ForeignKeyInfo("FK_Person_Country")
            {
                Columns = { "Age" },
                ReferencedTable = new TableInfo("Country", "dbo"),
                ReferencedColumns = { "Id" }
            });
            return schema;
        }

        #endregion

        #region ComposeCreateTable

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeCreateTable()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var schema = GetPersonSchema();

            // Act
            var actual = composer.ComposeCreateTable(schema);
            var expected = string.Join(Environment.NewLine,
                "CREATE TABLE \"dbo\".\"Person\" (",
                "    \"Id\" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10 INCREMENT BY 5) NOT NULL,",
                "    \"Name\" VARCHAR(128) NOT NULL,",
                "    \"Age\" INTEGER DEFAULT 0,",
                "    CONSTRAINT \"PK_Person\" PRIMARY KEY (\"Id\"),",
                "    CONSTRAINT \"UQ_Person_Name\" UNIQUE (\"Name\"),",
                "    CONSTRAINT \"CK_Person_Age\" CHECK ((\"Age\" >= 0))",
                ")");

            // Assert
            Assert.AreEqual(expected, actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeCreateTableWithoutSchemaName()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var schema = new TableSchema("Person", null);
            schema.Columns.Add(GetColumn("Name", "varchar", typeof(string), 1, false, 50));

            // Act
            var actual = composer.ComposeCreateTable(schema);
            var expected = string.Join(Environment.NewLine,
                "CREATE TABLE \"Person\" (",
                "    \"Name\" VARCHAR(50) NOT NULL",
                ")");

            // Assert
            Assert.AreEqual(expected, actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeCreateTableOrdersTheColumnsByOrdinal()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var schema = new TableSchema("Person", null);
            schema.Columns.Add(GetColumn("Second", "int", typeof(int), 2));
            schema.Columns.Add(GetColumn("First", "int", typeof(int), 1));

            // Act
            var actual = composer.ComposeCreateTable(schema);

            // Assert
            Assert.IsTrue(actual.IndexOf("\"First\"", StringComparison.Ordinal) < actual.IndexOf("\"Second\"", StringComparison.Ordinal));
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeCreateTableWithComputedColumn()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var schema = new TableSchema("Person", null);
            schema.Columns.Add(new ColumnInfo
            {
                Ordinal = 1,
                ComputedExpression = "upper(\"Name\")",
                Field = new DbField("NameUpper", false, false, true, typeof(string), 128, 0, 0, "varchar")
            });

            // Act
            var actual = composer.ComposeCreateTable(schema);

            // Assert
            StringAssert.Contains(actual, "\"NameUpper\" VARCHAR(128) GENERATED ALWAYS AS (upper(\"Name\"))", StringComparison.Ordinal);
            Assert.IsFalse(actual.Contains("DEFAULT", StringComparison.Ordinal));
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeCreateTableIgnoresTheDefaultOfAnIdentityColumn()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var schema = new TableSchema("Person", null);
            schema.Columns.Add(new ColumnInfo
            {
                Ordinal = 1,
                DefaultExpression = "0",
                Field = new DbField("Id", true, true, false, typeof(int), 4, 10, 0, "int")
            });

            // Act
            var actual = composer.ComposeCreateTable(schema);

            // Assert
            StringAssert.Contains(actual, "\"Id\" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL", StringComparison.Ordinal);
            Assert.IsFalse(actual.Contains("DEFAULT 0", StringComparison.Ordinal));
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeCreateTableIgnoresTheCollationOfTheColumn()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var schema = new TableSchema("Person", null);
            schema.Columns.Add(new ColumnInfo
            {
                Ordinal = 1,
                Collation = "BINARY_CI",
                Field = new DbField("Age", false, false, true, typeof(int), 4, 10, 0, "int")
            });

            // Act
            var actual = composer.ComposeCreateTable(schema);

            // Assert
            Assert.IsFalse(actual.Contains("COLLATE", StringComparison.Ordinal));
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeCreateTableWithUnnamedPrimaryKey()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var schema = new TableSchema("Person", null);
            schema.Columns.Add(GetColumn("Id", "int", typeof(int), 1, false));
            schema.PrimaryKey = new PrimaryKeyInfo(null) { Columns = { "Id" } };

            // Act
            var actual = composer.ComposeCreateTable(schema);

            // Assert
            StringAssert.Contains(actual, "    PRIMARY KEY (\"Id\")", StringComparison.Ordinal);
            Assert.IsFalse(actual.Contains("CONSTRAINT", StringComparison.Ordinal));
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeCreateTableWithCompositePrimaryKey()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var schema = new TableSchema("OrderLine", null);
            schema.Columns.Add(GetColumn("OrderId", "int", typeof(int), 1, false));
            schema.Columns.Add(GetColumn("LineNumber", "int", typeof(int), 2, false));
            schema.PrimaryKey = new PrimaryKeyInfo("PK_OrderLine") { Columns = { "OrderId", "LineNumber" } };

            // Act
            var actual = composer.ComposeCreateTable(schema);

            // Assert
            StringAssert.Contains(actual, "PRIMARY KEY (\"OrderId\", \"LineNumber\")", StringComparison.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeCreateTableWithoutPrimaryKey()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var schema = new TableSchema("NoKey", null);
            schema.Columns.Add(GetColumn("Value", "varchar", typeof(string), 1));

            // Act
            var actual = composer.ComposeCreateTable(schema);

            // Assert
            Assert.IsFalse(actual.Contains("PRIMARY KEY", StringComparison.Ordinal));
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeCreateTableQuotesTheIdentifiers()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var schema = new TableSchema("Odd\"Table", null);
            schema.Columns.Add(GetColumn("Odd\"Column", "int", typeof(int), 1));

            // Act
            var actual = composer.ComposeCreateTable(schema);

            // Assert
            StringAssert.Contains(actual, "\"Odd\"\"Table\"", StringComparison.Ordinal);
            StringAssert.Contains(actual, "\"Odd\"\"Column\"", StringComparison.Ordinal);
        }

        [TestMethod]
        public void ThrowExceptionOnSapHanaSchemaComposerComposeCreateTableIfTheSchemaIsNull()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();

            // Act/Assert
            Assert.Throws<ArgumentNullException>(() => composer.ComposeCreateTable(null));
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeCreateTableWithNamedPrimaryKey()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var schema = new TableSchema("Product", null);
            schema.Columns.Add(GetColumn("Id", "int", typeof(int), 1, false));
            schema.PrimaryKey = new PrimaryKeyInfo("PK_Product") { IsClustered = false, Columns = { "Id" } };

            // Act
            var actual = composer.ComposeCreateTable(schema);

            // Assert
            StringAssert.Contains(actual, "CONSTRAINT \"PK_Product\" PRIMARY KEY (\"Id\")", StringComparison.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeCreateTableWithClusteredPrimaryKeyByDefault()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var schema = new TableSchema("Product", null);
            schema.Columns.Add(GetColumn("Id", "int", typeof(int), 1, false));
            schema.PrimaryKey = new PrimaryKeyInfo("PK_Product") { Columns = { "Id" } };

            // Act
            var actual = composer.ComposeCreateTable(schema);

            // Assert
            StringAssert.Contains(actual, "CONSTRAINT \"PK_Product\" PRIMARY KEY (\"Id\")", StringComparison.Ordinal);
        }

        #endregion

        #region ComposeCreateIndex

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeCreateIndex()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var index = new IndexInfo("IX_Person_Name") { Columns = { "Name" } };

            // Act
            var actual = composer.ComposeCreateIndex("dbo.Person", index);

            // Assert
            Assert.AreEqual("CREATE INDEX \"dbo\".\"IX_Person_Name\" ON \"dbo\".\"Person\" (\"Name\")", actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeCreateIndexWithUniqueAndIncludedColumns()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var index = new IndexInfo("IX_Person_Name")
            {
                IsUnique = true,
                Columns = { "Name", "Age" },
                IncludedColumns = { "Salary", "CountryId" }
            };

            // Act
            var actual = composer.ComposeCreateIndex("\"dbo\".\"Person\"", index);
            var expected = "CREATE UNIQUE INDEX \"dbo\".\"IX_Person_Name\" ON \"dbo\".\"Person\" (\"Name\", \"Age\")";

            // Assert
            Assert.AreEqual(expected, actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void ThrowExceptionOnSapHanaSchemaComposerComposeCreateIndexIfTheIndexIsNull()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();

            // Act/Assert
            Assert.Throws<ArgumentNullException>(() => composer.ComposeCreateIndex("Person", null));
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeCreateIndexWithClusteredIndex()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var index = new IndexInfo("CIX_Product_Code") { IsUnique = true, IsClustered = true, Columns = { "Code" } };

            // Act
            var actual = composer.ComposeCreateIndex("dbo.Product", index);

            // Assert
            Assert.AreEqual("CREATE UNIQUE INDEX \"dbo\".\"CIX_Product_Code\" ON \"dbo\".\"Product\" (\"Code\")", actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeCreateIndexWithNonUniqueClusteredIndex()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var index = new IndexInfo("CIX") { IsClustered = true, Columns = { "Code" } };

            // Act
            var actual = composer.ComposeCreateIndex("Product", index);

            // Assert
            Assert.AreEqual("CREATE INDEX \"CIX\" ON \"Product\" (\"Code\")", actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeCreateIndexWithDescendingKey()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var index = new IndexInfo("IX_Product_Category_Price")
            {
                Columns = { "Category", "Price" },
                DescendingColumns = { "Price" },
                IncludedColumns = { "Name" }
            };

            // Act
            var actual = composer.ComposeCreateIndex("dbo.Product", index);
            var expected = "CREATE INDEX \"dbo\".\"IX_Product_Category_Price\" ON \"dbo\".\"Product\" (\"Category\", \"Price\" DESC)";

            // Assert
            Assert.AreEqual(expected, actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeCreateIndexWithAllDescendingKeys()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var index = new IndexInfo("IX") { Columns = { "A", "B" }, DescendingColumns = { "A", "B" } };

            // Act
            var actual = composer.ComposeCreateIndex("T", index);

            // Assert
            Assert.AreEqual("CREATE INDEX \"IX\" ON \"T\" (\"A\" DESC, \"B\" DESC)", actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeCreateIndexWithFilter()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var index = new IndexInfo("IX_Product_Active_Name")
            {
                Columns = { "Name" },
                Filter = "(\"IsActive\"=(1))"
            };

            // Act
            var actual = composer.ComposeCreateIndex("dbo.Product", index);

            // Assert
            Assert.AreEqual("CREATE INDEX \"dbo\".\"IX_Product_Active_Name\" ON \"dbo\".\"Product\" (\"Name\")", actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeCreateIndexWithAllTheOptions()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var index = new IndexInfo("IX")
            {
                IsUnique = true,
                IsClustered = true,
                Columns = { "A", "B" },
                DescendingColumns = { "B" },
                IncludedColumns = { "C" },
                Filter = "(\"A\">(0))"
            };

            // Act
            var actual = composer.ComposeCreateIndex("T", index);

            // Assert
            Assert.AreEqual("CREATE UNIQUE INDEX \"IX\" ON \"T\" (\"A\", \"B\" DESC)", actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeCreateIndexIgnoresTheBlankFilter()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var index = new IndexInfo("IX") { Columns = { "A" }, Filter = "  " };

            // Act
            var actual = composer.ComposeCreateIndex("T", index);

            // Assert
            Assert.AreEqual("CREATE INDEX \"IX\" ON \"T\" (\"A\")", actual, StringComparer.Ordinal);
        }

        #endregion

        #region ComposeAddForeignKey

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeAddForeignKey()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var foreignKey = new ForeignKeyInfo("FK_Person_Country")
            {
                Columns = { "CountryId" },
                ReferencedTable = new TableInfo("Country", "dbo"),
                ReferencedColumns = { "Id" }
            };

            // Act
            var actual = composer.ComposeAddForeignKey("dbo.Person", foreignKey);
            var expected = "ALTER TABLE \"dbo\".\"Person\" ADD CONSTRAINT \"FK_Person_Country\" FOREIGN KEY (\"CountryId\") REFERENCES \"dbo\".\"Country\" (\"Id\")";

            // Assert
            Assert.AreEqual(expected, actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeAddForeignKeyWithRules()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var foreignKey = new ForeignKeyInfo("FK_Person_Country")
            {
                Columns = { "CountryId" },
                ReferencedTable = new TableInfo("Country", "dbo"),
                ReferencedColumns = { "Id" },
                DeleteRule = CopySchemaForeignKeyRule.SetNull,
                UpdateRule = CopySchemaForeignKeyRule.Cascade
            };

            // Act
            var actual = composer.ComposeAddForeignKey("dbo.Person", foreignKey);

            // Assert
            StringAssert.EndsWith(actual, "ON UPDATE CASCADE ON DELETE SET NULL", StringComparison.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeAddForeignKeyWithSetDefaultRule()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var foreignKey = new ForeignKeyInfo("FK")
            {
                Columns = { "CountryId" },
                ReferencedTable = new TableInfo("Country", null),
                ReferencedColumns = { "Id" },
                DeleteRule = CopySchemaForeignKeyRule.SetDefault
            };

            // Act
            var actual = composer.ComposeAddForeignKey("Person", foreignKey);

            // Assert
            StringAssert.EndsWith(actual, "ON DELETE SET DEFAULT", StringComparison.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeAddForeignKeyWithRestrictRule()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var foreignKey = new ForeignKeyInfo("FK")
            {
                Columns = { "CountryId" },
                ReferencedTable = new TableInfo("Country", null),
                ReferencedColumns = { "Id" },
                DeleteRule = CopySchemaForeignKeyRule.Restrict,
                UpdateRule = CopySchemaForeignKeyRule.Restrict
            };

            // Act
            var actual = composer.ComposeAddForeignKey("Person", foreignKey);

            // Assert
            StringAssert.Contains(actual, "ON DELETE RESTRICT", StringComparison.Ordinal);
            StringAssert.Contains(actual, "ON UPDATE RESTRICT", StringComparison.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeAddForeignKeyWithCompositeColumns()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var foreignKey = new ForeignKeyInfo("FK_Line_Order")
            {
                Columns = { "OrderId", "LineNumber" },
                ReferencedTable = new TableInfo("OrderLine", "dbo"),
                ReferencedColumns = { "OrderId", "LineNumber" }
            };

            // Act
            var actual = composer.ComposeAddForeignKey("dbo.Shipment", foreignKey);

            // Assert
            StringAssert.Contains(actual, "FOREIGN KEY (\"OrderId\", \"LineNumber\") REFERENCES \"dbo\".\"OrderLine\" (\"OrderId\", \"LineNumber\")", StringComparison.Ordinal);
        }

        [TestMethod]
        public void ThrowExceptionOnSapHanaSchemaComposerComposeAddForeignKeyIfTheForeignKeyIsNull()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();

            // Act/Assert
            Assert.Throws<ArgumentNullException>(() => composer.ComposeAddForeignKey("Person", null));
        }

        #endregion

        #region ComposeAddColumn

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeAddColumn()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var column = GetColumn("Nickname", "varchar", typeof(string), 1, true, 50);

            // Act
            var actual = composer.ComposeAddColumn("dbo.Person", column);

            // Assert
            Assert.AreEqual("ALTER TABLE \"dbo\".\"Person\" ADD (\"Nickname\" VARCHAR(50))", actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeAddColumnWithDefault()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var column = GetColumn("Age", "int", typeof(int), 1, false);
            column.DefaultExpression = "0";

            // Act
            var actual = composer.ComposeAddColumn("Person", column);

            // Assert
            Assert.AreEqual("ALTER TABLE \"Person\" ADD (\"Age\" INTEGER DEFAULT 0 NOT NULL)", actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeAddColumnWithComputedColumn()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var column = GetColumn("NameUpper", "varchar", typeof(string), 1, true, 128);
            column.ComputedExpression = "upper(\"Name\")";

            // Act
            var actual = composer.ComposeAddColumn("dbo.Person", column);
            var expected = "ALTER TABLE \"dbo\".\"Person\" ADD (\"NameUpper\" VARCHAR(128) GENERATED ALWAYS AS (upper(\"Name\")))";

            // Assert
            Assert.AreEqual(expected, actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void ThrowExceptionOnSapHanaSchemaComposerComposeAddColumnIfTheColumnIsNull()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();

            // Act/Assert
            Assert.Throws<ArgumentNullException>(() => composer.ComposeAddColumn("Person", null));
        }

        #endregion

        #region ComposeDropTable

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeDropTable()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();

            // Act
            var actual = composer.ComposeDropTable("dbo.Person");

            // Assert
            Assert.AreEqual("DO BEGIN IF EXISTS (SELECT 1 FROM SYS.TABLES WHERE SCHEMA_NAME = 'dbo' AND TABLE_NAME = 'Person') THEN EXECUTE IMMEDIATE 'DROP TABLE \"dbo\".\"Person\" CASCADE'; END IF; END", actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeDropTableWithQuotedName()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();

            // Act
            var actual = composer.ComposeDropTable("\"Sales\".\"Invoice\"");

            // Assert
            Assert.AreEqual("DO BEGIN IF EXISTS (SELECT 1 FROM SYS.TABLES WHERE SCHEMA_NAME = 'Sales' AND TABLE_NAME = 'Invoice') THEN EXECUTE IMMEDIATE 'DROP TABLE \"Sales\".\"Invoice\" CASCADE'; END IF; END", actual, StringComparer.Ordinal);
        }

        #endregion

        #region ComposeSchema

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeSchema()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var schema = GetPersonSchema();

            // Act
            var actual = composer.ComposeSchema(schema).ToList();

            // Assert
            Assert.AreEqual(3, actual.Count);
            StringAssert.StartsWith(actual[0], "CREATE TABLE \"dbo\".\"Person\"", StringComparison.Ordinal);
            StringAssert.StartsWith(actual[1], "CREATE INDEX \"dbo\".\"IX_Person_Name\" ON \"dbo\".\"Person\"", StringComparison.Ordinal);
            StringAssert.StartsWith(actual[2], "ALTER TABLE \"dbo\".\"Person\" ADD CONSTRAINT \"FK_Person_Country\"", StringComparison.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeSchemaWithOnlyColumns()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var schema = new TableSchema("NoKey", null);
            schema.Columns.Add(GetColumn("Value", "varchar", typeof(string), 1));

            // Act
            var actual = composer.ComposeSchema(schema).ToList();

            // Assert
            Assert.AreEqual(1, actual.Count);
        }

        [TestMethod]
        public void ThrowExceptionOnSapHanaSchemaComposerComposeSchemaIfTheSchemaIsNull()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();

            // Act/Assert
            Assert.Throws<ArgumentNullException>(() => composer.ComposeSchema(null));
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeSchemas()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var first = GetPersonSchema();
            var second = new TableSchema("Country", "dbo");
            second.Columns.Add(GetColumn("Id", "int", typeof(int), 1, false));
            second.Indexes.Add(new IndexInfo("IX_Country_Id") { Columns = { "Id" } });

            // Act
            var actual = composer.ComposeSchemas(new[] { first, second }).ToList();

            // Assert
            Assert.AreEqual(5, actual.Count);
            StringAssert.StartsWith(actual[0], "CREATE TABLE \"dbo\".\"Person\"", StringComparison.Ordinal);
            StringAssert.StartsWith(actual[1], "CREATE TABLE \"dbo\".\"Country\"", StringComparison.Ordinal);
            StringAssert.StartsWith(actual[2], "CREATE INDEX \"dbo\".\"IX_Person_Name\" ON \"dbo\".\"Person\"", StringComparison.Ordinal);
            StringAssert.StartsWith(actual[3], "CREATE INDEX \"dbo\".\"IX_Country_Id\" ON \"dbo\".\"Country\"", StringComparison.Ordinal);
            StringAssert.StartsWith(actual[4], "ALTER TABLE \"dbo\".\"Person\" ADD CONSTRAINT \"FK_Person_Country\"", StringComparison.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeSchemasCreatesTheForeignKeysAfterAllTheTables()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var a = new TableSchema("CycleA", "dbo");
            a.Columns.Add(GetColumn("Id", "int", typeof(int), 1, false));
            a.Columns.Add(GetColumn("BId", "int", typeof(int), 2));
            a.ForeignKeys.Add(new ForeignKeyInfo("FK_CycleA_CycleB") { Columns = { "BId" }, ReferencedTable = new TableInfo("CycleB", "dbo"), ReferencedColumns = { "Id" } });
            var b = new TableSchema("CycleB", "dbo");
            b.Columns.Add(GetColumn("Id", "int", typeof(int), 1, false));
            b.Columns.Add(GetColumn("AId", "int", typeof(int), 2));
            b.ForeignKeys.Add(new ForeignKeyInfo("FK_CycleB_CycleA") { Columns = { "AId" }, ReferencedTable = new TableInfo("CycleA", "dbo"), ReferencedColumns = { "Id" } });

            // Act
            var actual = composer.ComposeSchemas(new[] { a, b }).ToList();

            // Assert
            Assert.AreEqual(4, actual.Count);
            StringAssert.StartsWith(actual[0], "CREATE TABLE \"dbo\".\"CycleA\"", StringComparison.Ordinal);
            StringAssert.StartsWith(actual[1], "CREATE TABLE \"dbo\".\"CycleB\"", StringComparison.Ordinal);
            StringAssert.StartsWith(actual[2], "ALTER TABLE \"dbo\".\"CycleA\" ADD CONSTRAINT \"FK_CycleA_CycleB\"", StringComparison.Ordinal);
            StringAssert.StartsWith(actual[3], "ALTER TABLE \"dbo\".\"CycleB\" ADD CONSTRAINT \"FK_CycleB_CycleA\"", StringComparison.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeSchemasWithoutTables()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();

            // Act
            var actual = composer.ComposeSchemas(Enumerable.Empty<TableSchema>()).ToList();

            // Assert
            Assert.AreEqual(0, actual.Count);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeSchemasOfOneTableIsTheSameAsComposeSchema()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var schema = GetPersonSchema();

            // Act
            var actual = composer.ComposeSchemas(new[] { schema }).ToList();
            var expected = composer.ComposeSchema(schema).ToList();

            // Assert
            CollectionAssert.AreEqual(expected, actual);
        }

        [TestMethod]
        public void ThrowExceptionOnSapHanaSchemaComposerComposeSchemasIfTheSchemasAreNull()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();

            // Act/Assert
            Assert.Throws<ArgumentNullException>(() => composer.ComposeSchemas(null));
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeCreateTableWithNameThatNeedsQuoting()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var schema = new TableSchema("Odd.Name", "dbo");
            schema.Columns.Add(GetColumn("Unit Price", "decimal", typeof(decimal), 1, false, null, 10, 2));

            // Act
            var actual = composer.ComposeCreateTable(schema);

            // Assert
            StringAssert.StartsWith(actual, "CREATE TABLE \"dbo\".\"Odd.Name\" (", StringComparison.Ordinal);
            StringAssert.Contains(actual, "\"Unit Price\" DECIMAL(10,2) NOT NULL", StringComparison.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeCreateTableWithDoubleQuoteInTheNames()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var schema = new TableSchema("Weird\"Name", "dbo");
            schema.Columns.Add(GetColumn("Id", "int", typeof(int), 1, false));

            // Act
            var actual = composer.ComposeCreateTable(schema);

            // Assert
            StringAssert.StartsWith(actual, "CREATE TABLE \"dbo\".\"Weird\"\"Name\" (", StringComparison.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeAddForeignKeyWithNamesThatNeedQuoting()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var foreignKey = new ForeignKeyInfo("FK_OddChild_OddName")
            {
                Columns = { "ParentId" },
                ReferencedTable = new TableInfo("Odd.Name", "dbo"),
                ReferencedColumns = { "Id" }
            };

            // Act
            var actual = composer.ComposeAddForeignKey("\"dbo\".\"Odd.Child\"", foreignKey);
            var expected = "ALTER TABLE \"dbo\".\"Odd.Child\" ADD CONSTRAINT \"FK_OddChild_OddName\" FOREIGN KEY (\"ParentId\") REFERENCES \"dbo\".\"Odd.Name\" (\"Id\")";

            // Assert
            Assert.AreEqual(expected, actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeSchemasWithNamesThatNeedQuoting()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var parent = new TableSchema("Odd.Name", "dbo");
            parent.Columns.Add(GetColumn("Id", "int", typeof(int), 1, false));
            parent.Indexes.Add(new IndexInfo("IX_OddName_Id") { Columns = { "Id" } });
            var child = new TableSchema("Odd.Child", "dbo");
            child.Columns.Add(GetColumn("ParentId", "int", typeof(int), 1, false));
            child.ForeignKeys.Add(new ForeignKeyInfo("FK_OddChild_OddName")
            {
                Columns = { "ParentId" },
                ReferencedTable = new TableInfo("Odd.Name", "dbo"),
                ReferencedColumns = { "Id" }
            });

            // Act
            var actual = composer.ComposeSchemas(new[] { child, parent }).ToList();

            // Assert
            Assert.AreEqual(4, actual.Count);
            StringAssert.StartsWith(actual[0], "CREATE TABLE \"dbo\".\"Odd.Child\"", StringComparison.Ordinal);
            StringAssert.StartsWith(actual[1], "CREATE TABLE \"dbo\".\"Odd.Name\"", StringComparison.Ordinal);
            Assert.AreEqual("CREATE INDEX \"dbo\".\"IX_OddName_Id\" ON \"dbo\".\"Odd.Name\" (\"Id\")", actual[2], StringComparer.Ordinal);
            StringAssert.Contains(actual[3], "ALTER TABLE \"dbo\".\"Odd.Child\" ADD CONSTRAINT \"FK_OddChild_OddName\"", StringComparison.Ordinal);
            StringAssert.Contains(actual[3], "REFERENCES \"dbo\".\"Odd.Name\" (\"Id\")", StringComparison.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeDropTableWithDoubleQuoteInTheName()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();

            // Act
            var actual = composer.ComposeDropTable("\"dbo\".\"Weird\"\"Name\"");

            // Assert
            Assert.AreEqual("DO BEGIN IF EXISTS (SELECT 1 FROM SYS.TABLES WHERE SCHEMA_NAME = 'dbo' AND TABLE_NAME = 'Weird\"Name') THEN EXECUTE IMMEDIATE 'DROP TABLE \"dbo\".\"Weird\"\"Name\" CASCADE'; END IF; END", actual, StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeCreateIndexWithTableNameThatNeedsQuoting()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();
            var index = new IndexInfo("IX") { Columns = { "Id" } };

            // Act
            var actual = composer.ComposeCreateIndex("dbo.\"Odd.Name\"", index);

            // Assert
            Assert.AreEqual("CREATE INDEX \"dbo\".\"IX\" ON \"dbo\".\"Odd.Name\" (\"Id\")", actual, StringComparer.Ordinal);
        }

        #endregion

        #region ComposeTypeName

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeTypeNameForSizedUnicodeString()
        {
            Assert.AreEqual("VARCHAR(128)", ComposeTypeName("varchar", typeof(string), 128), StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeTypeNameForUnicodeStringWithMaxSize()
        {
            Assert.AreEqual("CLOB", ComposeTypeName("varchar", typeof(string), -1), StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeTypeNameForUnicodeStringWithoutSize()
        {
            Assert.AreEqual("CLOB", ComposeTypeName("varchar", typeof(string)), StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeTypeNameForVarChar()
        {
            Assert.AreEqual("VARCHAR(50)", ComposeTypeName("varchar", typeof(string), 50), StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeTypeNameForFixedLengthCharacters()
        {
            Assert.AreEqual("NVARCHAR(10)", ComposeTypeName("char", typeof(string), 10), StringComparer.Ordinal);
            Assert.AreEqual("NVARCHAR(4)", ComposeTypeName("char", typeof(string), 4), StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeTypeNameForFixedLengthCharactersWithoutSize()
        {
            Assert.AreEqual("NVARCHAR(1)", ComposeTypeName("char", typeof(string)), StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeTypeNameForBinary()
        {
            Assert.AreEqual("VARBINARY(16)", ComposeTypeName("binary", typeof(byte[]), 16), StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeTypeNameForVarBinary()
        {
            Assert.AreEqual("VARBINARY(256)", ComposeTypeName("varbinary", typeof(byte[]), 256), StringComparer.Ordinal);
            Assert.AreEqual("BLOB", ComposeTypeName("varbinary", typeof(byte[]), -1), StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeTypeNameForDecimal()
        {
            Assert.AreEqual("DECIMAL(18,2)", ComposeTypeName("decimal", typeof(decimal), 9, 18, 2), StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeTypeNameForNumericWithoutPrecision()
        {
            Assert.AreEqual("DECIMAL", ComposeTypeName("decimal", typeof(decimal)), StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeTypeNameForTemporalTypesWithScale()
        {
            Assert.AreEqual("TIMESTAMP", ComposeTypeName("datetime", typeof(DateTime), scale: 3), StringComparer.Ordinal);
            Assert.AreEqual("TIMESTAMP", ComposeTypeName("timestamp", typeof(DateTime), scale: 9), StringComparer.Ordinal);
            Assert.AreEqual("TIME", ComposeTypeName("time", typeof(TimeSpan), scale: 5), StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeTypeNameForTemporalTypesWithoutScale()
        {
            Assert.AreEqual("TIMESTAMP", ComposeTypeName("datetime", typeof(DateTime)), StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeTypeNameForSimpleTypes()
        {
            Assert.AreEqual("INTEGER", ComposeTypeName("int", typeof(int)), StringComparer.Ordinal);
            Assert.AreEqual("BIGINT", ComposeTypeName("bigint", typeof(long)), StringComparer.Ordinal);
            Assert.AreEqual("BOOLEAN", ComposeTypeName("bit", typeof(bool)), StringComparer.Ordinal);
            Assert.AreEqual("VARBINARY(16)", ComposeTypeName("uuid", typeof(Guid)), StringComparer.Ordinal);
            Assert.AreEqual("DOUBLE", ComposeTypeName("double", typeof(double)), StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeTypeNameIsCaseInsensitive()
        {
            Assert.AreEqual("INTEGER", ComposeTypeName("INT", typeof(int)), StringComparer.Ordinal);
            Assert.AreEqual("VARCHAR(20)", ComposeTypeName("VarChar", typeof(string), 20), StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeTypeNameForTheTypesOfOtherDatabaseEngines()
        {
            Assert.AreEqual("BOOLEAN", ComposeTypeName("boolean", typeof(bool)), StringComparer.Ordinal);
            Assert.AreEqual("VARBINARY(16)", ComposeTypeName("uuid", typeof(Guid)), StringComparer.Ordinal);
            Assert.AreEqual("CLOB", ComposeTypeName("varchar", typeof(string)), StringComparer.Ordinal);
            Assert.AreEqual("BLOB", ComposeTypeName("varbinary", typeof(byte[])), StringComparer.Ordinal);
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeTypeNameFallsBackToTheClientTypeIfThereIsNoDatabaseType()
        {
            Assert.AreEqual("BIGINT", ComposeTypeName(null, typeof(long)), StringComparer.Ordinal);
            Assert.AreEqual("TIMESTAMP", ComposeTypeName(null, typeof(DateTime)), StringComparer.Ordinal);
            Assert.AreEqual("NVARCHAR(20)", ComposeTypeName(null, typeof(string), 20), StringComparer.Ordinal);
            Assert.AreEqual("NCLOB", ComposeTypeName(null, typeof(object)), StringComparer.Ordinal);
        }

        [TestMethod]
        public void ThrowExceptionOnSapHanaSchemaComposerComposeTypeNameIfTheColumnIsNull()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();

            // Act/Assert
            Assert.Throws<ArgumentNullException>(() => composer.ComposeTypeName(null));
        }

        [TestMethod]
        public void ThrowExceptionOnSapHanaSchemaComposerComposeTypeNameIfTheColumnHasNoField()
        {
            // Setup
            var composer = new SapHanaSchemaComposer();

            // Act/Assert
            Assert.Throws<ArgumentException>(() => composer.ComposeTypeName(new ColumnInfo()));
        }

        #endregion

        #region Interface

        [TestMethod]
        public void TestSapHanaSchemaComposerIsASchemaComposer()
        {
            // Act
            var composer = new SapHanaSchemaComposer();

            // Assert
            Assert.IsInstanceOfType<ISchemaComposer>(composer);
        }

        #endregion

        #region ComposeName / Exists

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeName()
        {
            // Act/Assert
            var composer = new SapHanaSchemaComposer();
            Assert.AreEqual("dbo.Person", composer.ComposeName(new TableInfo("Person", "dbo")));
            Assert.AreEqual("dbo.\"Odd.Name\"", composer.ComposeName(new TableInfo("Odd.Name", "dbo")));
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeNameWithoutSchema()
        {
            // Act/Assert
            Assert.AreEqual("Person", new SapHanaSchemaComposer().ComposeName(new TableInfo("Person", null)));
        }

        [TestMethod]
        public void ThrowExceptionOnSapHanaSchemaComposerComposeNameIfTheTableIsNull()
        {
            // Act/Assert
            Assert.Throws<ArgumentNullException>(() => new SapHanaSchemaComposer().ComposeName(null));
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeTableExists()
        {
            // Act/Assert
            Assert.AreEqual("SELECT CASE WHEN EXISTS (SELECT 1 FROM SYS.TABLES WHERE SCHEMA_NAME = 'dbo' AND TABLE_NAME = 'Person') THEN 1 ELSE 0 END FROM DUMMY", new SapHanaSchemaComposer().ComposeTableExists("dbo.Person"));
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeColumnExists()
        {
            // Act/Assert
            Assert.AreEqual("SELECT CASE WHEN EXISTS (SELECT 1 FROM SYS.TABLE_COLUMNS WHERE SCHEMA_NAME = 'dbo' AND TABLE_NAME = 'Person' AND COLUMN_NAME = 'Name') THEN 1 ELSE 0 END FROM DUMMY", new SapHanaSchemaComposer().ComposeColumnExists("dbo.Person", "Name"));
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeIndexExists()
        {
            // Act/Assert
            Assert.AreEqual("SELECT CASE WHEN EXISTS (SELECT 1 FROM SYS.INDEXES WHERE SCHEMA_NAME = 'dbo' AND TABLE_NAME = 'Person' AND INDEX_NAME = 'IX_Person_Name') THEN 1 ELSE 0 END FROM DUMMY", new SapHanaSchemaComposer().ComposeIndexExists("dbo.Person", "IX_Person_Name"));
        }

        [TestMethod]
        public void TestSapHanaSchemaComposerComposeExistsEscapesTheSingleQuotes()
        {
            // Act
            var composer = new SapHanaSchemaComposer();

            // Assert
            StringAssert.Contains(composer.ComposeColumnExists("dbo.Person", "O'Brien"), "O''Brien", StringComparison.Ordinal);
            StringAssert.Contains(composer.ComposeIndexExists("dbo.Person", "IX_O'Brien"), "IX_O''Brien", StringComparison.Ordinal);
            StringAssert.Contains(composer.ComposeTableExists("dbo.\"O'Brien\""), "O''Brien", StringComparison.Ordinal);
        }

        #endregion
    }
}
