using System;
using System.Collections.Generic;
using FirebirdSql.Data.FirebirdClient;
using RepoDb.Firebird.IntegrationTests.Models;

namespace RepoDb.Firebird.IntegrationTests.Setup
{
    public static class Database
    {
        #region Properties

        /// <summary>
        /// Gets or sets the connection string to be used.
        /// </summary>
        public static string ConnectionString { get; private set; }

        #endregion

        #region Methods

        public static void Initialize()
        {
            ConnectionString =
                Environment.GetEnvironmentVariable("REPODB_FIREBIRD_CONSTR") ??
                @"DataSource=127.0.0.1;Port=3050;Database=/firebird/data/repodb.fdb;User=SYSDBA;Password=RepoDB2026;Charset=UTF8;";

            // Initialize Firebird
            GlobalConfiguration
                .Setup()
                .UseFirebird();

            // Create tables
            CreateTables();
        }

        public static void Cleanup()
        {
            using (var connection = new FbConnection(ConnectionString))
            {
                connection.Truncate<CompleteTable>();
                connection.Truncate<NonIdentityCompleteTable>();
            }
        }

        #endregion

        #region CompleteTable

        public static IEnumerable<CompleteTable> CreateCompleteTables(int count)
        {
            using (var connection = new FbConnection(ConnectionString))
            {
                var tables = Helper.CreateCompleteTables(count);
                connection.InsertAll(tables);
                return tables;
            }
        }

        #endregion

        #region NonIdentityCompleteTable

        public static IEnumerable<NonIdentityCompleteTable> CreateNonIdentityCompleteTables(int count)
        {
            using (var connection = new FbConnection(ConnectionString))
            {
                var tables = Helper.CreateNonIdentityCompleteTables(count);
                connection.InsertAll(tables);
                return tables;
            }
        }

        #endregion

        #region CreateTables

        private static void CreateTables()
        {
            CreateCompleteTable();
            CreateNonIdentityCompleteTable();
        }

        private static void CreateCompleteTable()
        {
            using (var connection = new FbConnection(ConnectionString))
            {
                // RECREATE TABLE is Firebird's idiomatic "drop if exists, then create" - there is no
                // "CREATE TABLE IF NOT EXISTS" in Firebird DDL. Identifiers are quoted to preserve the
                // exact mixed case used by the C# model, since FirebirdDbSetting always quotes
                // identifiers when generating SQL (unquoted identifiers fold to UPPERCASE in Firebird).
                connection.ExecuteNonQuery(@"RECREATE TABLE ""CompleteTable""
                    (
                        ""Id"" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                        ""ColumnVarchar"" VARCHAR(256),
                        ""ColumnInt"" INTEGER,
                        ""ColumnDecimal2"" DECIMAL(18,2),
                        ""ColumnDateTime"" TIMESTAMP,
                        ""ColumnBlob"" BLOB SUB_TYPE 0,
                        ""ColumnBlobAsArray"" BLOB SUB_TYPE 0,
                        ""ColumnBinary"" CHAR(255) CHARACTER SET OCTETS,
                        ""ColumnLongBlob"" BLOB SUB_TYPE 0,
                        ""ColumnMediumBlob"" BLOB SUB_TYPE 0,
                        ""ColumnTinyBlob"" BLOB SUB_TYPE 0,
                        ""ColumnVarBinary"" VARCHAR(256) CHARACTER SET OCTETS,
                        ""ColumnDate"" DATE,
                        ""ColumnDateTime2"" TIMESTAMP,
                        ""ColumnTime"" TIME,
                        ""ColumnTimeStamp"" TIMESTAMP,
                        ""ColumnYear"" SMALLINT,
                        ""ColumnBigint"" BIGINT,
                        ""ColumnDecimal"" DECIMAL(10,0),
                        ""ColumnDouble"" DOUBLE PRECISION,
                        ""ColumnFloat"" FLOAT,
                        ""ColumnInt2"" INTEGER,
                        ""ColumnMediumInt"" INTEGER,
                        ""ColumnReal"" DOUBLE PRECISION,
                        ""ColumnSmallInt"" SMALLINT,
                        ""ColumnTinyInt"" SMALLINT,
                        ""ColumnChar"" CHAR(1),
                        ""ColumnJson"" BLOB SUB_TYPE TEXT,
                        ""ColumnNChar"" NCHAR(16),
                        ""ColumnNVarChar"" NCHAR VARYING(256),
                        ""ColumnLongText"" BLOB SUB_TYPE TEXT,
                        ""ColumnMediumText"" BLOB SUB_TYPE TEXT,
                        ""ColumnText"" BLOB SUB_TYPE TEXT,
                        ""ColumnTinyText"" VARCHAR(255),
                        ""ColumnBit"" BOOLEAN,
                        PRIMARY KEY (""Id"")
                    );");
            }
        }

        private static void CreateNonIdentityCompleteTable()
        {
            using (var connection = new FbConnection(ConnectionString))
            {
                connection.ExecuteNonQuery(@"RECREATE TABLE ""NonIdentityCompleteTable""
                    (
                        ""Id"" BIGINT NOT NULL,
                        ""ColumnVarchar"" VARCHAR(256),
                        ""ColumnInt"" INTEGER,
                        ""ColumnDecimal2"" DECIMAL(18,2),
                        ""ColumnDateTime"" TIMESTAMP,
                        ""ColumnBlob"" BLOB SUB_TYPE 0,
                        ""ColumnBlobAsArray"" BLOB SUB_TYPE 0,
                        ""ColumnBinary"" CHAR(255) CHARACTER SET OCTETS,
                        ""ColumnLongBlob"" BLOB SUB_TYPE 0,
                        ""ColumnMediumBlob"" BLOB SUB_TYPE 0,
                        ""ColumnTinyBlob"" BLOB SUB_TYPE 0,
                        ""ColumnVarBinary"" VARCHAR(256) CHARACTER SET OCTETS,
                        ""ColumnDate"" DATE,
                        ""ColumnDateTime2"" TIMESTAMP,
                        ""ColumnTime"" TIME,
                        ""ColumnTimeStamp"" TIMESTAMP,
                        ""ColumnYear"" SMALLINT,
                        ""ColumnBigint"" BIGINT,
                        ""ColumnDecimal"" DECIMAL(10,0),
                        ""ColumnDouble"" DOUBLE PRECISION,
                        ""ColumnFloat"" FLOAT,
                        ""ColumnInt2"" INTEGER,
                        ""ColumnMediumInt"" INTEGER,
                        ""ColumnReal"" DOUBLE PRECISION,
                        ""ColumnSmallInt"" SMALLINT,
                        ""ColumnTinyInt"" SMALLINT,
                        ""ColumnChar"" CHAR(1),
                        ""ColumnJson"" BLOB SUB_TYPE TEXT,
                        ""ColumnNChar"" NCHAR(16),
                        ""ColumnNVarChar"" NCHAR VARYING(256),
                        ""ColumnLongText"" BLOB SUB_TYPE TEXT,
                        ""ColumnMediumText"" BLOB SUB_TYPE TEXT,
                        ""ColumnText"" BLOB SUB_TYPE TEXT,
                        ""ColumnTinyText"" VARCHAR(255),
                        ""ColumnBit"" BOOLEAN,
                        PRIMARY KEY (""Id"")
                    );");
            }
        }

        #endregion
    }
}
