using IBM.Data.Db2;
using RepoDb.Attributes.Parameter.Db2;

namespace RepoDb.Db2.IntegrationTests.Models
{
    /// <summary>
    /// Same physical shape as <see cref="CompleteTable"/> (see Setup/Database.cs), except "Id" is a
    /// plain, caller-supplied primary key rather than a "GENERATED BY DEFAULT AS IDENTITY" column -
    /// used to exercise operations against a non-identity table, mirroring the
    /// CompleteTable/NonIdentityCompleteTable split used by the other providers in this repo.
    /// </summary>
    public class NonIdentityCompleteTable
    {
        public System.Int32 Id { get; set; }

        // Db2 has no native GUID/UNIQUEIDENTIFIER type; "SessionId" is stored as a 16-byte
        // "CHAR(16) FOR BIT DATA" column and converted via the Guid<->byte[] PropertyHandler
        // registered in Setup/Database.cs.
        public System.Guid SessionId { get; set; }

        public System.String ColumnVarchar { get; set; }
        public System.Decimal ColumnNumber { get; set; }
        public System.DateTime ColumnDate { get; set; }
        public System.DateTime ColumnTimestamp { get; set; }

        public System.String ColumnVarchar2 { get; set; }
        public System.String ColumnChar { get; set; }

        [Db2Type(DB2Type.Graphic)]
        public System.String ColumnNChar { get; set; }

        public System.Int32 ColumnInt { get; set; }
        public System.Int64 ColumnBigInt { get; set; }
        public System.Int16 ColumnSmallInt { get; set; }

        [Db2Type(DB2Type.SmallInt)]
        public System.Byte ColumnTinyInt { get; set; }

        [Db2Type(DB2Type.Real)]
        public System.Single ColumnBinaryFloat { get; set; }

        [Db2Type(DB2Type.Double)]
        public System.Double ColumnBinaryDouble { get; set; }

        [Db2Type(DB2Type.Binary)]
        public System.Byte[] ColumnRaw { get; set; }

        [Db2Type(DB2Type.Clob)]
        public System.String ColumnClob { get; set; }

        [Db2Type(DB2Type.DbClob)]
        public System.String ColumnNClob { get; set; }

        [Db2Type(DB2Type.Blob)]
        public System.Byte[] ColumnBlob { get; set; }

        [Db2Type(DB2Type.Xml)]
        public System.String ColumnXml { get; set; }
    }
}
