using MySqlConnector;
using RepoDb.MySqlConnector.BulkOperations.IntegrationTests.Models;
using System;

namespace RepoDb.IntegrationTests.Setup
{
    /// <summary>
    /// A class used as a startup setup for the RepoDb MySqlConnector bulk-operations test database.
    /// </summary>
    public static class Database
    {
        #region Properties

        /// <summary>
        /// Gets the connection string to be used for the MySqlConnector database.
        /// </summary>
        public static string ConnectionString { get; private set; }

        #endregion

        #region Methods

        /// <summary>
        /// Initialize the creation of the database.
        /// </summary>
        public static void Initialize()
        {
            ConnectionString =
                Environment.GetEnvironmentVariable("REPODB_MYSQL_CONSTR_SYSTEM") ??
                Environment.GetEnvironmentVariable("REPODB_MYSQL_CONSTR") ??
                "Server=127.0.0.1;Port=3306;Database=RepoDb;User ID=root;Password=RepoDB2026;";

            // Initialize MySqlConnector
            GlobalConfiguration
                .Setup()
                .UseMySqlConnector();

            // Create the tables
            CreateTables();
        }

        /// <summary>
        /// Clean up all the table.
        /// </summary>
        public static void Cleanup()
        {
            using var connection = new MySqlConnection(ConnectionString);
            connection.Truncate<BulkOperationIdentityTable>();
            connection.Truncate<BulkOperationNonIdentityTable>();
        }

        #endregion

        #region CreateTables

        /// <summary>
        /// Create the necessary tables for testing.
        /// </summary>
        public static void CreateTables()
        {
            CreateBulkOperationIdentityTable();
            CreateBulkOperationNonIdentityTable();
        }

        /// <summary>
        /// Creates an identity table that has some important fields. All fields are nullable.
        /// </summary>
        public static void CreateBulkOperationIdentityTable()
        {
            // MySqlConnector has no "CREATE TABLE IF NOT EXISTS"; guard with a PL/SQL block instead, the
            // same pattern used by RepoDb.MySqlConnector.IntegrationTests/Setup/Database.cs.
            var commandText = @"
                BEGIN
                    EXECUTE IMMEDIATE '
                        CREATE TABLE ""BulkOperationIdentityTable""
                        (
                            ""Id"" NUMBER GENERATED BY DEFAULT AS IDENTITY,
                            ""RowGuid"" RAW(16) NOT NULL,
                            ""ColumnBit"" NUMBER(1,0) NULL,
                            ""ColumnDateTime"" DATE NULL,
                            ""ColumnDateTime2"" TIMESTAMP(7) NULL,
                            ""ColumnDecimal"" NUMBER(18,2) NULL,
                            ""ColumnFloat"" BINARY_DOUBLE NULL,
                            ""ColumnInt"" NUMBER(10,0) NULL,
                            ""ColumnNVarChar"" NVARCHAR2(2000) NULL,
                            CONSTRAINT ""BulkOperationIdentityTable_Id"" PRIMARY KEY (""Id"")
                        )';
                EXCEPTION
                    WHEN OTHERS THEN
                        IF SQLCODE != -955 THEN -- ORA-00955: name is already used by an existing object
                            RAISE;
                        END IF;
                END;";
            using var connection = new MySqlConnection(ConnectionString);
            connection.ExecuteNonQuery(commandText);
        }

        /// <summary>
        /// Creates a non-identity table that has some important fields. All fields are nullable except
        /// the primary key. Unlike <see cref="CreateBulkOperationIdentityTable"/>, <c>"Id"</c> here is a
        /// plain <c>NUMBER</c> primary key (no <c>GENERATED ... AS IDENTITY</c>) - the caller's value is
        /// stored as-is. Used by tests that need to know a row's <c>Id</c> ahead of time (e.g. matching
        /// against a separately-built anonymous/expando object by primary key), which an
        /// MySqlConnector-generated identity value can't support.
        /// </summary>
        public static void CreateBulkOperationNonIdentityTable()
        {
            var commandText = @"
                BEGIN
                    EXECUTE IMMEDIATE '
                        CREATE TABLE ""BulkOperationNonIdentityTable""
                        (
                            ""Id"" NUMBER NOT NULL,
                            ""RowGuid"" RAW(16) NOT NULL,
                            ""ColumnBit"" NUMBER(1,0) NULL,
                            ""ColumnDateTime"" DATE NULL,
                            ""ColumnDateTime2"" TIMESTAMP(7) NULL,
                            ""ColumnDecimal"" NUMBER(18,2) NULL,
                            ""ColumnFloat"" BINARY_DOUBLE NULL,
                            ""ColumnInt"" NUMBER(10,0) NULL,
                            ""ColumnNVarChar"" NVARCHAR2(2000) NULL,
                            CONSTRAINT ""BulkOperationNonIdentityTable_Id"" PRIMARY KEY (""Id"")
                        )';
                EXCEPTION
                    WHEN OTHERS THEN
                        IF SQLCODE != -955 THEN -- ORA-00955: name is already used by an existing object
                            RAISE;
                        END IF;
                END;";
            using var connection = new MySqlConnection(ConnectionString);
            connection.ExecuteNonQuery(commandText);
        }

        #endregion
    }
}
