using Oracle.ManagedDataAccess.Client;
using RepoDb.Oracle.BulkOperations.IntegrationTests.Models;
using RepoDb.Oracle.PropertyHandlers;
using System;

namespace RepoDb.IntegrationTests.Setup
{
    /// <summary>
    /// A class used as a startup setup for the RepoDb Oracle bulk-operations test database.
    /// </summary>
    public static class Database
    {
        #region Properties

        /// <summary>
        /// Gets the connection string to be used for the Oracle database.
        /// </summary>
        public static string ConnectionString { get; private set; }

        #endregion

        #region Methods

        /// <summary>
        /// Initialize the creation of the database.
        /// </summary>
        public static void Initialize()
        {
            // RepoDb connection. Defaults match the 'oracle' service in docker-compose.yml at the
            // repo root (container-registry.oracle.com/database/free, ORACLE_PWD=RepoDB2026),
            // which exposes the SYSTEM user against the FREEPDB1 pluggable database - the same
            // convention used by RepoDb.Oracle.IntegrationTests.
            ConnectionString =
                Environment.GetEnvironmentVariable("REPODB_ORACLE_CONSTR_BULK") ??
                Environment.GetEnvironmentVariable("REPODB_ORACLE_CONSTR") ??
                "User Id=system;Password=RepoDB2026;Data Source=localhost:1521/FREEPDB1;";

            // Initialize Oracle
            GlobalConfiguration
                .Setup()
                .UseOracle();

            // Oracle has no native GUID type; "RowGuid"/"RowGuidMapped" are stored as RAW(16). Scope
            // the Guid<->byte[] conversion to each specific entity/property rather than registering it
            // globally for typeof(Guid), matching RepoDb.Oracle.IntegrationTests/Setup/Database.cs.
            PropertyHandlerMapper.Add<BulkOperationIdentityTable, OracleGuidToByteArrayPropertyHandler>(
                e => e.RowGuid, new OracleGuidToByteArrayPropertyHandler(), true);
            PropertyHandlerMapper.Add<BulkOperationMappedIdentityTable, OracleGuidToByteArrayPropertyHandler>(
                e => e.RowGuidMapped, new OracleGuidToByteArrayPropertyHandler(), true);
            PropertyHandlerMapper.Add<WithExtraFieldsBulkOperationIdentityTable, OracleGuidToByteArrayPropertyHandler>(
                e => e.RowGuid, new OracleGuidToByteArrayPropertyHandler(), true);
            PropertyHandlerMapper.Add<BulkOperationNonIdentityTable, OracleGuidToByteArrayPropertyHandler>(
                e => e.RowGuid, new OracleGuidToByteArrayPropertyHandler(), true);
            PropertyHandlerMapper.Add<BulkOperationMappedNonIdentityTable, OracleGuidToByteArrayPropertyHandler>(
                e => e.RowGuidMapped, new OracleGuidToByteArrayPropertyHandler(), true);
            PropertyHandlerMapper.Add<WithExtraFieldsBulkOperationNonIdentityTable, OracleGuidToByteArrayPropertyHandler>(
                e => e.RowGuid, new OracleGuidToByteArrayPropertyHandler(), true);

            // Create the tables
            CreateTables();
        }

        /// <summary>
        /// Clean up all the table.
        /// </summary>
        public static void Cleanup()
        {
            using var connection = new OracleConnection(ConnectionString);
            connection.Truncate<BulkOperationIdentityTable>();
            connection.Truncate<BulkOperationNonIdentityTable>();
        }

        #endregion

        #region CreateTables

        /// <summary>
        /// Create the necessary tables for testing.
        /// </summary>
        public static void CreateTables()
        {
            CreateBulkOperationIdentityTable();
            CreateBulkOperationNonIdentityTable();
        }

        /// <summary>
        /// Creates an identity table that has some important fields. All fields are nullable.
        /// </summary>
        public static void CreateBulkOperationIdentityTable()
        {
            // Oracle has no "CREATE TABLE IF NOT EXISTS"; guard with a PL/SQL block instead, the
            // same pattern used by RepoDb.Oracle.IntegrationTests/Setup/Database.cs.
            var commandText = @"
                BEGIN
                    EXECUTE IMMEDIATE '
                        CREATE TABLE ""BulkOperationIdentityTable""
                        (
                            ""Id"" NUMBER GENERATED BY DEFAULT AS IDENTITY,
                            ""RowGuid"" RAW(16) NOT NULL,
                            ""ColumnBit"" NUMBER(1,0) NULL,
                            ""ColumnDateTime"" DATE NULL,
                            ""ColumnDateTime2"" TIMESTAMP(7) NULL,
                            ""ColumnDecimal"" NUMBER(18,2) NULL,
                            ""ColumnFloat"" BINARY_DOUBLE NULL,
                            ""ColumnInt"" NUMBER(10,0) NULL,
                            ""ColumnNVarChar"" NVARCHAR2(2000) NULL,
                            CONSTRAINT ""BulkOperationIdentityTable_Id"" PRIMARY KEY (""Id"")
                        )';
                EXCEPTION
                    WHEN OTHERS THEN
                        IF SQLCODE != -955 THEN -- ORA-00955: name is already used by an existing object
                            RAISE;
                        END IF;
                END;";
            using var connection = new OracleConnection(ConnectionString);
            connection.ExecuteNonQuery(commandText);
        }

        /// <summary>
        /// Creates a non-identity table that has some important fields. All fields are nullable except
        /// the primary key. Unlike <see cref="CreateBulkOperationIdentityTable"/>, <c>"Id"</c> here is a
        /// plain <c>NUMBER</c> primary key (no <c>GENERATED ... AS IDENTITY</c>) - the caller's value is
        /// stored as-is. Used by tests that need to know a row's <c>Id</c> ahead of time (e.g. matching
        /// against a separately-built anonymous/expando object by primary key), which an
        /// Oracle-generated identity value can't support.
        /// </summary>
        public static void CreateBulkOperationNonIdentityTable()
        {
            var commandText = @"
                BEGIN
                    EXECUTE IMMEDIATE '
                        CREATE TABLE ""BulkOperationNonIdentityTable""
                        (
                            ""Id"" NUMBER NOT NULL,
                            ""RowGuid"" RAW(16) NOT NULL,
                            ""ColumnBit"" NUMBER(1,0) NULL,
                            ""ColumnDateTime"" DATE NULL,
                            ""ColumnDateTime2"" TIMESTAMP(7) NULL,
                            ""ColumnDecimal"" NUMBER(18,2) NULL,
                            ""ColumnFloat"" BINARY_DOUBLE NULL,
                            ""ColumnInt"" NUMBER(10,0) NULL,
                            ""ColumnNVarChar"" NVARCHAR2(2000) NULL,
                            CONSTRAINT ""BulkOperationNonIdentityTable_Id"" PRIMARY KEY (""Id"")
                        )';
                EXCEPTION
                    WHEN OTHERS THEN
                        IF SQLCODE != -955 THEN -- ORA-00955: name is already used by an existing object
                            RAISE;
                        END IF;
                END;";
            using var connection = new OracleConnection(ConnectionString);
            connection.ExecuteNonQuery(commandText);
        }

        #endregion
    }
}
