<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Title>RepoDb.Schema.Core</Title>
    <AssemblyName>RepoDb.Schema.Core</AssemblyName>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Description>The schema productivity core package of RepoDB library.</Description>
    <LangVersion>preview</LangVersion>
    <Nullable>annotations</Nullable>
    <PackageTags>orm hybrid-orm micro-orm</PackageTags>
    <PackageIcon>RepoDbCore.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageProjectUrl>https://repodb.net/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/mikependon/RepoDB/tree/master/src/Productivity/RepoDb.Schema.Core</RepositoryUrl>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\..\..\LICENSE.txt" Pack="True" PackagePath="\" />
    <None Include="..\README.md" Pack="True" PackagePath="\" />
    <None Include="..\RepoDbCore.png" Pack="True" PackagePath="\" />
    <None Include="..\..\..\..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="RepoDb.Schema.Core.UnitTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.SqlServer" />
    <InternalsVisibleTo Include="RepoDb.Schema.PostgreSql" />
    <InternalsVisibleTo Include="RepoDb.Schema.SqlServer.UnitTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.SqlServer.IntegrationTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.PostgreSql.UnitTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.PostgreSql.IntegrationTests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Providers\RepoDb.Core\RepoDb\RepoDb.csproj" />
  </ItemGroup>
</Project>
