<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Title>RepoDb.Schema.Core</Title>
    <AssemblyName>RepoDb.Schema.Core</AssemblyName>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Description>The schema productivity core package of RepoDB library.</Description>
    <LangVersion>preview</LangVersion>
    <Nullable>annotations</Nullable>
    <PackageTags>orm hybrid-orm micro-orm</PackageTags>
    <PackageIcon>RepoDbCore.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageProjectUrl>https://repodb.net/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/mikependon/RepoDB/tree/master/src/Productivity/RepoDb.Schema.Core</RepositoryUrl>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\..\..\LICENSE.txt" Pack="True" PackagePath="\" />
    <None Include="..\README.md" Pack="True" PackagePath="\" />
    <None Include="..\RepoDbCore.png" Pack="True" PackagePath="\" />
    <None Include="..\..\..\..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="RepoDb.Schema.Core.UnitTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.SqlServer" />
    <InternalsVisibleTo Include="RepoDb.Schema.PostgreSql" />
    <InternalsVisibleTo Include="RepoDb.Schema.SqlServer.UnitTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.SqlServer.IntegrationTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.PostgreSql.UnitTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.PostgreSql.IntegrationTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.CockroachDb" />
    <InternalsVisibleTo Include="RepoDb.Schema.CockroachDb.UnitTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.CockroachDb.IntegrationTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.MySql" />
    <InternalsVisibleTo Include="RepoDb.Schema.MySql.UnitTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.MySql.IntegrationTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.Oracle" />
    <InternalsVisibleTo Include="RepoDb.Schema.Oracle.UnitTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.Oracle.IntegrationTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.Db2" />
    <InternalsVisibleTo Include="RepoDb.Schema.Db2.UnitTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.Db2.IntegrationTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.Firebird" />
    <InternalsVisibleTo Include="RepoDb.Schema.Firebird.UnitTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.Firebird.IntegrationTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.MariaDbConnector" />
    <InternalsVisibleTo Include="RepoDb.Schema.MariaDbConnector.UnitTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.MariaDbConnector.IntegrationTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.SapHana" />
    <InternalsVisibleTo Include="RepoDb.Schema.SapHana.UnitTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.SapHana.IntegrationTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.Vertica" />
    <InternalsVisibleTo Include="RepoDb.Schema.Vertica.UnitTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.Vertica.IntegrationTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.DuckDb" />
    <InternalsVisibleTo Include="RepoDb.Schema.DuckDb.UnitTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.DuckDb.IntegrationTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.AuroraDbMySqlConnector" />
    <InternalsVisibleTo Include="RepoDb.Schema.AuroraDbMySqlConnector.UnitTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.AuroraDbMySqlConnector.IntegrationTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.AuroraDbPostgreSql" />
    <InternalsVisibleTo Include="RepoDb.Schema.AuroraDbPostgreSql.UnitTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.AuroraDbPostgreSql.IntegrationTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.ClickHouse" />
    <InternalsVisibleTo Include="RepoDb.Schema.ClickHouse.UnitTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.ClickHouse.IntegrationTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.Ahtola" />
    <InternalsVisibleTo Include="RepoDb.Schema.Ahtola.UnitTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.Ahtola.IntegrationTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.Turso" />
    <InternalsVisibleTo Include="RepoDb.Schema.Turso.UnitTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.Turso.IntegrationTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.MySqlConnector" />
    <InternalsVisibleTo Include="RepoDb.Schema.MySqlConnector.UnitTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.MySqlConnector.IntegrationTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.MariaDb" />
    <InternalsVisibleTo Include="RepoDb.Schema.MariaDb.UnitTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.MariaDb.IntegrationTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.Sqlite" />
    <InternalsVisibleTo Include="RepoDb.Schema.Sqlite.UnitTests" />
    <InternalsVisibleTo Include="RepoDb.Schema.Sqlite.IntegrationTests" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Bcl.HashCode" Version="6.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Providers\RepoDb.Core\RepoDb\RepoDb.csproj" />
  </ItemGroup>
</Project>
