#region Copyright Attributions

// Copyright (c) 2026 Michael Camara Pendon.
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for full license information.

#endregion

using System;
using System.Collections.Generic;
using System.Linq;
using RepoDb.Enumerations.SapHana;
using RepoDb.Extensions;
using RepoDb.Interfaces;

namespace RepoDb
{
    /// <summary>
    /// Builds every SQL text used by the SapHana bulk-operations pseudo-table pipeline.
    /// </summary>
    internal static class SapHanaText
    {
        private const string RowOrderColumnName = "__RepoDbBulkRowOrder__";
        private const string QualifierIndexName = "__RepoDbBulkQualifierIndex__";

        #region Shared

        /// <summary>
        /// 
        /// </summary>
        /// <param name="tableName"></param>
        /// <param name="pseudoTableName"></param>
        /// <param name="pseudoTableType"></param>
        /// <param name="dbSetting"></param>
        /// <param name="qualifierField"></param>
        /// <returns></returns>
        public static string GetCreatePseudoTableSql(string tableName,
            string pseudoTableName,
            SapHanaBulkImportPseudoTableType pseudoTableType,
            IDbSetting dbSetting,
            Field qualifierField = null)
        {
            var quotedTableName = tableName.AsQuoted(true, dbSetting);
            var quotedPseudoTableName = pseudoTableName.AsQuoted(true, dbSetting);
            var columnList = qualifierField != null ? qualifierField.Name.AsQuoted(true, dbSetting) : "*";
            var temporaryKeyword = pseudoTableType == SapHanaBulkImportPseudoTableType.Physical
                ? string.Empty
                : "LOCAL TEMPORARY ";

            return string.Concat(
                "CREATE ", temporaryKeyword, "TABLE ", quotedPseudoTableName, " AS ",
                "(SELECT ", columnList, " FROM ", quotedTableName, " WHERE (1 = 0))");
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="pseudoTableName"></param>
        /// <param name="dbSetting"></param>
        /// <returns></returns>
        public static string GetAddPseudoTableRowOrderColumnSql(string pseudoTableName,
            IDbSetting dbSetting)
        {
            var quotedPseudoTableName = pseudoTableName.AsQuoted(true, dbSetting);
            var quotedRowOrderColumn = RowOrderColumnName.AsQuoted(true, dbSetting);

            return $"ALTER TABLE {quotedPseudoTableName} ADD ({quotedRowOrderColumn} BIGINT GENERATED BY DEFAULT AS IDENTITY)";
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="pseudoTableName"></param>
        /// <param name="qualifiers"></param>
        /// <param name="dbSetting"></param>
        /// <returns></returns>
        public static string GetCreatePseudoTableIndexSql(string pseudoTableName,
            IEnumerable<Field> qualifiers,
            IDbSetting dbSetting)
        {
            var quotedPseudoTableName = pseudoTableName.AsQuoted(true, dbSetting);
            var quotedIndexName = QualifierIndexName.AsQuoted(true, dbSetting);
            var columnList = qualifiers
                .Select(f => f.Name.AsQuoted(true, dbSetting))
                .Join(", ");

            return $"CREATE INDEX {quotedIndexName} ON {quotedPseudoTableName} ({columnList})";
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="pseudoTableName"></param>
        /// <param name="dbSetting"></param>
        /// <returns></returns>
        public static string GetTruncatePseudoTableSql(string pseudoTableName,
            IDbSetting dbSetting) =>
            $"TRUNCATE TABLE {pseudoTableName.AsQuoted(true, dbSetting)}";

        /// <summary>
        /// 
        /// </summary>
        /// <param name="pseudoTableName"></param>
        /// <param name="dbSetting"></param>
        /// <returns></returns>
        public static string GetDropPseudoTableSql(string pseudoTableName,
            IDbSetting dbSetting) =>
            $"DROP TABLE {pseudoTableName.AsQuoted(true, dbSetting)}";

        #endregion

        #region Insert

        /// <summary>
        /// 
        /// </summary>
        /// <param name="tableName"></param>
        /// <param name="pseudoTableType"></param>
        /// <param name="dbSetting"></param>
        /// <returns></returns>
        public static string GetPseudoTableNameForInsert(string tableName,
            SapHanaBulkImportPseudoTableType pseudoTableType,
            IDbSetting dbSetting) => $"{pseudoTableType}{tableName.AsUnquoted(dbSetting)}Insert";

        /// <summary>
        /// 
        /// </summary>
        /// <param name="tableName"></param>
        /// <param name="columnName"></param>
        /// <param name="dbSetting"></param>
        /// <returns></returns>
        public static string GetColumnMetadataSql(string tableName,
            string columnName,
            IDbSetting dbSetting)
        {
            var unquotedTableName = tableName.AsUnquoted(true, dbSetting);
            var unquotedColumnName = columnName.AsUnquoted(true, dbSetting);

            return
                "SELECT DATA_TYPE_NAME, LENGTH, SCALE FROM SYS.TABLE_COLUMNS " +
                $"WHERE SCHEMA_NAME = CURRENT_SCHEMA AND TABLE_NAME = '{unquotedTableName}' AND COLUMN_NAME = '{unquotedColumnName}'";
        }

        /// <summary>
        /// 
        /// </summary>
        private static readonly HashSet<string> ColumnTypeNamesRequiringLength = new(StringComparer.OrdinalIgnoreCase)
        {
            "VARCHAR", "NVARCHAR", "ALPHANUM", "SHORTTEXT", "CHAR", "NCHAR", "VARBINARY", "BINARY"
        };

        /// <summary>
        /// 
        /// </summary>
        /// <param name="pseudoTableName"></param>
        /// <param name="columnName"></param>
        /// <param name="dataTypeName"></param>
        /// <param name="length"></param>
        /// <param name="scale"></param>
        /// <param name="dbSetting"></param>
        /// <returns></returns>
        public static string GetAllowNullForColumnSql(string pseudoTableName,
            string columnName,
            string dataTypeName,
            int? length,
            int? scale,
            IDbSetting dbSetting)
        {
            var quotedPseudoTableName = pseudoTableName.AsQuoted(true, dbSetting);
            var quotedColumnName = columnName.AsQuoted(true, dbSetting);

            var typeDefinition = string.Equals(dataTypeName, "DECIMAL", StringComparison.OrdinalIgnoreCase) && length.HasValue && scale.HasValue
                ? $"{dataTypeName}({length}, {scale})"
                : ColumnTypeNamesRequiringLength.Contains(dataTypeName) && length.HasValue
                    ? $"{dataTypeName}({length})"
                    : dataTypeName;

            return $"ALTER TABLE {quotedPseudoTableName} ALTER ({quotedColumnName} {typeDefinition} NULL)";
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="tableName"></param>
        /// <param name="identityField"></param>
        /// <param name="dbSetting"></param>
        /// <returns></returns>
        public static string GetIdentitySequenceMetadataSql(string tableName,
            Field identityField,
            IDbSetting dbSetting)
        {
            var quotedTableName = tableName.AsQuoted(true, dbSetting);
            var quotedIdentityColumn = identityField.Name.AsQuoted(true, dbSetting);

            return string.Concat(
                "SELECT CAST(COALESCE(MAX(", quotedIdentityColumn, "), 0) + 1 AS VARCHAR(38)) AS ",
                "SequenceName".AsQuoted(dbSetting), ", ",
                "'NO' AS ", "GenerationType".AsQuoted(dbSetting), " FROM ", quotedTableName);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="pseudoTableName"></param>
        /// <param name="identityField"></param>
        /// <param name="sequenceName"></param>
        /// <param name="isAlwaysGenerated"></param>
        /// <param name="dbSetting"></param>
        /// <returns></returns>
        public static string GetPreAssignPseudoTableIdentitySql(string pseudoTableName,
            Field identityField,
            string sequenceName,
            bool isAlwaysGenerated,
            IDbSetting dbSetting)
        {
            var quotedPseudoTableName = pseudoTableName.AsQuoted(true, dbSetting);
            var quotedIdentityColumn = identityField.Name.AsQuoted(true, dbSetting);
            var quotedRowOrderColumn = RowOrderColumnName.AsQuoted(true, dbSetting);
            var nextIdentityValue = string.IsNullOrWhiteSpace(sequenceName) ? "1" : sequenceName;

            return $"UPDATE {quotedPseudoTableName} SET {quotedIdentityColumn} = {quotedRowOrderColumn} + ({nextIdentityValue} - 1)";
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="tableName"></param>
        /// <param name="pseudoTableName"></param>
        /// <param name="fields"></param>
        /// <param name="dbSetting"></param>
        /// <returns></returns>
        public static string GetInsertIntoTableFromPseudoTableSql(string tableName,
            string pseudoTableName,
            IEnumerable<Field> fields,
            IDbSetting dbSetting)
        {
            var quotedTableName = tableName.AsQuoted(true, dbSetting);
            var quotedPseudoTableName = pseudoTableName.AsQuoted(true, dbSetting);

            var columnList = fields
                .Select(f => f.Name.AsQuoted(true, dbSetting))
                .Join(", ");

            return $"INSERT INTO {quotedTableName} ({columnList}) SELECT {columnList} FROM {quotedPseudoTableName}";
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="pseudoTableName"></param>
        /// <param name="identityField"></param>
        /// <param name="dbSetting"></param>
        /// <returns></returns>
        public static string GetSelectPseudoTableIdentityValuesSql(string pseudoTableName,
            Field identityField,
            IDbSetting dbSetting)
        {
            var quotedPseudoTableName = pseudoTableName.AsQuoted(true, dbSetting);
            var quotedIdentityColumn = identityField.Name.AsQuoted(true, dbSetting);
            var quotedRowOrderColumn = RowOrderColumnName.AsQuoted(true, dbSetting);
            var resultAlias = "Result".AsQuoted(dbSetting);

            return $"SELECT {quotedIdentityColumn} AS {resultAlias} FROM {quotedPseudoTableName} ORDER BY {quotedRowOrderColumn}";
        }

        #endregion

        #region Merge

        /// <summary>
        /// 
        /// </summary>
        /// <param name="tableName"></param>
        /// <param name="pseudoTableType"></param>
        /// <param name="dbSetting"></param>
        /// <returns></returns>
        public static string GetPseudoTableNameForMerge(string tableName,
            SapHanaBulkImportPseudoTableType pseudoTableType,
            IDbSetting dbSetting) => $"{pseudoTableType}{tableName.AsUnquoted(dbSetting)}Merge";

        /// <summary>
        /// 
        /// </summary>
        /// <param name="tableName"></param>
        /// <param name="pseudoTableName"></param>
        /// <param name="fields"></param>
        /// <param name="qualifiers"></param>
        /// <param name="identityField"></param>
        /// <param name="dbSetting"></param>
        /// <returns></returns>
        public static string GetMergeFromPseudoTableSql(string tableName,
            string pseudoTableName,
            IEnumerable<Field> fields,
            IEnumerable<Field> qualifiers,
            Field identityField,
            IDbSetting dbSetting)
        {
            var quotedTableName = tableName.AsQuoted(true, dbSetting);
            var quotedPseudoTableName = pseudoTableName.AsQuoted(true, dbSetting);

            var fieldList = fields.AsList();
            var qualifierList = qualifiers.AsList();

            var onClause = qualifierList
                .Select(f => $"T.{f.Name.AsQuoted(true, dbSetting)} = S.{f.Name.AsQuoted(true, dbSetting)}")
                .Join(" AND ");

            var updateableFields = fieldList
                .Where(f => qualifierList.Any(q => string.Equals(q.Name, f.Name, StringComparison.OrdinalIgnoreCase)) == false)
                .AsList();

            var insertableFields = fieldList
                .Where(f => identityField == null || !string.Equals(f.Name, identityField.Name, StringComparison.OrdinalIgnoreCase))
                .AsList();

            var insertColumns = insertableFields
                .Select(f => f.Name.AsQuoted(true, dbSetting))
                .Join(", ");

            var insertValues = insertableFields
                .Select(f => $"S.{f.Name.AsQuoted(true, dbSetting)}")
                .Join(", ");

            var updateSetClause = updateableFields
                .Select(f => $"{f.Name.AsQuoted(true, dbSetting)} = S.{f.Name.AsQuoted(true, dbSetting)}")
                .Join(", ");

            var whenMatched = updateableFields.Count > 0
                ? $"WHEN MATCHED THEN UPDATE SET {updateSetClause} "
                : string.Empty;

            return string.Concat(
                "MERGE INTO ", quotedTableName, " T USING ", quotedPseudoTableName, " S ON (", onClause, ") ",
                whenMatched,
                "WHEN NOT MATCHED THEN INSERT (", insertColumns, ") VALUES (", insertValues, ");");
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="tableName"></param>
        /// <param name="pseudoTableName"></param>
        /// <param name="identityField"></param>
        /// <param name="qualifiers"></param>
        /// <param name="dbSetting"></param>
        /// <returns></returns>
        public static string GetAssignMatchedIdentityToPseudoTableRowsSql(string tableName,
            string pseudoTableName,
            Field identityField,
            IEnumerable<Field> qualifiers,
            IDbSetting dbSetting)
        {
            var quotedTableName = tableName.AsQuoted(true, dbSetting);
            var quotedPseudoTableName = pseudoTableName.AsQuoted(true, dbSetting);
            var quotedIdentityColumn = identityField.Name.AsQuoted(true, dbSetting);

            var onClauseTP = qualifiers
                .Select(f => $"T.{f.Name.AsQuoted(true, dbSetting)} = P.{f.Name.AsQuoted(true, dbSetting)}")
                .Join(" AND ");

            return
                $"UPDATE {quotedPseudoTableName} P SET {quotedIdentityColumn} = " +
                $"(SELECT T.{quotedIdentityColumn} FROM {quotedTableName} T WHERE {onClauseTP}) " +
                $"WHERE EXISTS (SELECT 1 FROM {quotedTableName} T WHERE {onClauseTP})";
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="tableName"></param>
        /// <param name="pseudoTableName"></param>
        /// <param name="identityField"></param>
        /// <param name="qualifiers"></param>
        /// <param name="sequenceName"></param>
        /// <param name="dbSetting"></param>
        /// <returns></returns>
        public static string GetAssignFreshIdentityToUnmatchedPseudoTableRowsSql(string tableName,
            string pseudoTableName,
            Field identityField,
            IEnumerable<Field> qualifiers,
            string sequenceName,
            IDbSetting dbSetting)
        {
            var quotedTableName = tableName.AsQuoted(true, dbSetting);
            var quotedPseudoTableName = pseudoTableName.AsQuoted(true, dbSetting);
            var quotedIdentityColumn = identityField.Name.AsQuoted(true, dbSetting);
            var quotedRowOrderColumn = RowOrderColumnName.AsQuoted(true, dbSetting);
            var nextIdentityValue = string.IsNullOrWhiteSpace(sequenceName) ? "1" : sequenceName;

            var onClauseTP = qualifiers
                .Select(f => $"T.{f.Name.AsQuoted(true, dbSetting)} = P.{f.Name.AsQuoted(true, dbSetting)}")
                .Join(" AND ");
            var onClauseTP2 = qualifiers
                .Select(f => $"T.{f.Name.AsQuoted(true, dbSetting)} = P2.{f.Name.AsQuoted(true, dbSetting)}")
                .Join(" AND ");

            return
                $"UPDATE {quotedPseudoTableName} P SET {quotedIdentityColumn} = ({nextIdentityValue} - 1) + " +
                $"(SELECT COUNT(*) FROM {quotedPseudoTableName} P2 " +
                $"WHERE P2.{quotedRowOrderColumn} <= P.{quotedRowOrderColumn} " +
                $"AND NOT EXISTS (SELECT 1 FROM {quotedTableName} T WHERE {onClauseTP2})) " +
                $"WHERE NOT EXISTS (SELECT 1 FROM {quotedTableName} T WHERE {onClauseTP})";
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="tableName"></param>
        /// <param name="pseudoTableName"></param>
        /// <param name="fields"></param>
        /// <param name="identityField"></param>
        /// <param name="qualifiers"></param>
        /// <param name="dbSetting"></param>
        /// <returns></returns>
        public static string GetMergeFromPseudoTableForReturnIdentitySql(string tableName,
            string pseudoTableName,
            IEnumerable<Field> fields,
            Field identityField,
            IEnumerable<Field> qualifiers,
            IDbSetting dbSetting)
        {
            var quotedTableName = tableName.AsQuoted(true, dbSetting);
            var quotedPseudoTableName = pseudoTableName.AsQuoted(true, dbSetting);

            var fieldList = fields.AsList();
            var qualifierList = qualifiers.AsList();

            var onClauseTS = qualifierList
                .Select(f => $"T.{f.Name.AsQuoted(true, dbSetting)} = S.{f.Name.AsQuoted(true, dbSetting)}")
                .Join(" AND ");

            var updateableFields = fieldList
                .Where(f => !string.Equals(f.Name, identityField.Name, StringComparison.OrdinalIgnoreCase) &&
                    qualifierList.Any(q => string.Equals(q.Name, f.Name, StringComparison.OrdinalIgnoreCase)) == false)
                .AsList();

            var insertColumns = fieldList
                .Select(f => f.Name.AsQuoted(true, dbSetting))
                .Join(", ");

            var insertValues = fieldList
                .Select(f => $"S.{f.Name.AsQuoted(true, dbSetting)}")
                .Join(", ");

            var updateSetClause = updateableFields
                .Select(f => $"{f.Name.AsQuoted(true, dbSetting)} = S.{f.Name.AsQuoted(true, dbSetting)}")
                .Join(", ");

            var whenMatched = updateableFields.Count > 0
                ? $"WHEN MATCHED THEN UPDATE SET {updateSetClause} "
                : string.Empty;

            return
                $"MERGE INTO {quotedTableName} T USING {quotedPseudoTableName} S ON ({onClauseTS}) " +
                whenMatched +
                $"WHEN NOT MATCHED THEN INSERT ({insertColumns}) VALUES ({insertValues})";
        }

        #endregion

        #region Update

        /// <summary>
        /// 
        /// </summary>
        /// <param name="tableName"></param>
        /// <param name="pseudoTableType"></param>
        /// <param name="dbSetting"></param>
        /// <returns></returns>
        public static string GetPseudoTableNameForUpdate(string tableName,
            SapHanaBulkImportPseudoTableType pseudoTableType,
            IDbSetting dbSetting) => $"{pseudoTableType}{tableName.AsUnquoted(dbSetting)}Update";

        /// <summary>
        /// 
        /// </summary>
        /// <param name="tableName"></param>
        /// <param name="pseudoTableName"></param>
        /// <param name="fields"></param>
        /// <param name="qualifiers"></param>
        /// <param name="dbSetting"></param>
        /// <returns></returns>
        public static string GetUpdateFromPseudoTableSql(string tableName,
            string pseudoTableName,
            IEnumerable<Field> fields,
            IEnumerable<Field> qualifiers,
            IDbSetting dbSetting)
        {
            var quotedTableName = tableName.AsQuoted(true, dbSetting);
            var quotedPseudoTableName = pseudoTableName.AsQuoted(true, dbSetting);

            var fieldList = fields.AsList();
            var qualifierList = qualifiers.AsList();

            var onClause = qualifierList
                .Select(f => $"{tableName.AsQuoted(true, dbSetting)}.{f.Name.AsQuoted(true, dbSetting)} = S.{f.Name.AsQuoted(true, dbSetting)}")
                .Join(" AND ");

            var updateableFields = fieldList
                .Where(f => qualifierList.Any(q => string.Equals(q.Name, f.Name, StringComparison.OrdinalIgnoreCase)) == false)
                .AsList();

            var setColumns = updateableFields
                .Select(f => f.Name.AsQuoted(true, dbSetting))
                .Join(", ");

            var selectColumns = updateableFields
                .Select(f => $"S.{f.Name.AsQuoted(true, dbSetting)}")
                .Join(", ");

            return string.Concat(
                "UPDATE ", quotedTableName, " SET (", setColumns, ") = (",
                "SELECT ", selectColumns, " FROM ", quotedPseudoTableName, " S WHERE ", onClause, ") ",
                "WHERE EXISTS (SELECT 1 FROM ", quotedPseudoTableName, " S WHERE ", onClause, ")");
        }

        #endregion

        #region Delete

        /// <summary>
        /// 
        /// </summary>
        /// <param name="tableName"></param>
        /// <param name="pseudoTableType"></param>
        /// <param name="dbSetting"></param>
        /// <returns></returns>
        public static string GetPseudoTableNameForDelete(string tableName,
            SapHanaBulkImportPseudoTableType pseudoTableType,
            IDbSetting dbSetting) => $"{pseudoTableType}{tableName.AsUnquoted(dbSetting)}Delete";

        /// <summary>
        /// 
        /// </summary>
        /// <param name="tableName"></param>
        /// <param name="pseudoTableType"></param>
        /// <param name="dbSetting"></param>
        /// <returns></returns>
        public static string GetPseudoTableNameForDeleteByKey(string tableName,
            SapHanaBulkImportPseudoTableType pseudoTableType,
            IDbSetting dbSetting) => $"{pseudoTableType}{tableName.AsUnquoted(dbSetting)}DeleteByKey";

        /// <summary>
        /// 
        /// </summary>
        /// <param name="tableName"></param>
        /// <param name="pseudoTableName"></param>
        /// <param name="qualifiers"></param>
        /// <param name="dbSetting"></param>
        /// <returns></returns>
        public static string GetDeleteFromPseudoTableSql(string tableName,
            string pseudoTableName,
            IEnumerable<Field> qualifiers,
            IDbSetting dbSetting)
        {
            var quotedTableName = tableName.AsQuoted(true, dbSetting);
            var quotedPseudoTableName = pseudoTableName.AsQuoted(true, dbSetting);

            var onClause = qualifiers
                .Select(f => $"{tableName.AsQuoted(true, dbSetting)}.{f.Name.AsQuoted(true, dbSetting)} = S.{f.Name.AsQuoted(true, dbSetting)}")
                .Join(" AND ");

            return string.Concat(
                "DELETE FROM ", quotedTableName, " WHERE EXISTS (",
                "SELECT 1 FROM ", quotedPseudoTableName, " S WHERE ", onClause, ")");
        }

        #endregion
    }
}
