<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>RepoDb.Options</Title>
    <AssemblyName>RepoDb.Options</AssemblyName>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <LangVersion>preview</LangVersion>
    <Nullable>annotations</Nullable>
	<Description>A set of options for RepoDB.</Description>
    <LangVersion>preview</LangVersion>
    <Nullable>annotations</Nullable>
    <PackageTags>orm hybrid-orm micro-orm options</PackageTags>
    <RepositoryUrl>https://github.com/mikependon/RepoDB/tree/master/src/Options/RepoDb.Options</RepositoryUrl>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageReleaseNotes>http://repodb.net/release/options</PackageReleaseNotes>
    <PackageProjectUrl>https://repodb.net/tutorial/get-started-options</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Providers\RepoDb.Core\RepoDb\RepoDb.csproj" />
  </ItemGroup>

</Project>
