<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Title>RepoDb.Schema.Sqlite.Turso</Title>
    <AssemblyName>RepoDb.Schema.Sqlite.Turso</AssemblyName>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <Description>The Turso schema reader and composer of RepoDB library.</Description>
    <LangVersion>preview</LangVersion>
    <Nullable>annotations</Nullable>
    <PackageTags>orm hybrid-orm micro-orm schema sqlite turso</PackageTags>
    <PackageIcon>SQLite.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageProjectUrl>https://repodb.net/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/mikependon/RepoDB/tree/master/src/Schema/RepoDb.Schema.Sqlite.Turso</RepositoryUrl>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\..\..\LICENSE.txt" Pack="True" PackagePath="\" />
    <None Include="..\README.md" Pack="True" PackagePath="\" />
    <None Include="..\SQLite.png" Pack="True" PackagePath="\" />
    <None Include="..\..\..\..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="RepoDb.Schema.Sqlite.Turso.UnitTests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\RepoDb.Schema.Core\RepoDb.Schema.Core\RepoDb.Schema.Core.csproj" />
    <ProjectReference Include="..\..\..\Providers\RepoDb.Sqlite.Turso\RepoDb.Sqlite.Turso\RepoDb.Sqlite.Turso.csproj" />
  </ItemGroup>
</Project>
