using IBM.Data.Db2;
using RepoDb.Db2.IntegrationTests.Models;
using RepoDb.Db2.PropertyHandlers;
using System;
using System.Collections.Generic;
using System.Linq;

namespace RepoDb.Db2.IntegrationTests.Setup
{
    public static class Database
    {
        #region Properties

        /// <summary>
        /// Gets the connection string to be used for the Db2 database.
        /// </summary>
        public static string ConnectionString { get; private set; }

        #endregion

        #region Methods

        public static void Initialize()
        {
            // RepoDb connection. Defaults match the 'db2' service in docker-compose.yml at the
            // repo root (a Db2 community/Db2Connect image, Db2INST1_PASSWORD=RepoDB2026), which
            // exposes the "db2inst1" user against the "REPODB" database on the default port 50000.
            // "HostVarParameters=True;" is required: every RepoDb.Db2 statement/query (see
            // Db2StatementBuilder and Db2DbHelper) binds using ":Name"-style host variables, but
            // IBM.Data.Db2's support for that syntax is OFF by default - without this flag the
            // driver doesn't recognize ":Name" as a parameter marker at all, so any parameter count
            // it computes for a prepared statement comes out as 0/mismatched, and every parameterized
            // call fails with DB2Exception SQL0313N ("the number of variables in the EXECUTE
            // statement ... is not equal to the number of values required"). If you override this via
            // REPODB_Db2_CONSTR, make sure your connection string also includes this flag.
            ConnectionString =
                Environment.GetEnvironmentVariable("REPODB_Db2_CONSTR") ??
                "Server=localhost:50000;Database=REPODB;UID=db2inst1;PWD=RepoDB2026;HostVarParameters=True;";

            // Initialize Db2
            GlobalConfiguration
                .Setup()
                .UseDb2();

            // Db2 has no native GUID type; "SessionId" is stored as a 16-byte "CHAR(16) FOR BIT
            // DATA" column. Scope the Guid<->byte[] conversion to this specific property rather than
            // registering it globally for typeof(Guid), since a global registration would also affect
            // any other provider used in the same process. CompleteTable and NonIdentityCompleteTable
            // are distinct CLR types, so each needs its own registration even though "SessionId" maps
            // to the same physical column shape on both tables.
            PropertyHandlerMapper.Add<CompleteTable, Db2GuidToByteArrayPropertyHandler>(
                e => e.SessionId, new Db2GuidToByteArrayPropertyHandler(), true);
            PropertyHandlerMapper.Add<NonIdentityCompleteTable, Db2GuidToByteArrayPropertyHandler>(
                e => e.SessionId, new Db2GuidToByteArrayPropertyHandler(), true);

            // Db2 has no native TINYINT type; "ColumnTinyInt" is stored as a SMALLINT column. The
            // IBM Data Server .NET Provider does not marshal a raw, boxed System.Byte parameter value
            // cleanly against it (InvalidCastException: "Unable to cast object of type 'System.Byte'
            // to type 'System.Byte[]'" at execution time, regardless of the DB2Type/DbType already
            // being correctly resolved to SmallInt/Int16) - convert to System.Int16 first, same
            // scoping rationale as the Guid<->byte[] handler above.
            PropertyHandlerMapper.Add<CompleteTable, Db2ByteToInt16PropertyHandler>(
                e => e.ColumnTinyInt, new Db2ByteToInt16PropertyHandler(), true);
            PropertyHandlerMapper.Add<NonIdentityCompleteTable, Db2ByteToInt16PropertyHandler>(
                e => e.ColumnTinyInt, new Db2ByteToInt16PropertyHandler(), true);

            // Create tables
            CreateTables();
        }

        public static void Cleanup()
        {
            using var connection = new DB2Connection(ConnectionString);
            connection.Truncate<CompleteTable>();
            connection.Truncate<NonIdentityCompleteTable>();
        }

        #endregion

        #region CreateTables

        private static void CreateTables()
        {
            CreateCompleteTable();
            CreateNonIdentityCompleteTable();
        }

        private static void CreateCompleteTable()
        {
            var commandText = @"
                CREATE TABLE ""CompleteTable""
                (
                    ""Id"" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
                    ""SessionId"" CHAR(16) FOR BIT DATA NOT NULL,
                    ""ColumnVarchar"" VARCHAR(256),
                    ""ColumnNumber"" DECIMAL(18,12),
                    ""ColumnDate"" DATE,
                    ""ColumnTimestamp"" TIMESTAMP,
                    ""ColumnVarchar2"" VARCHAR(500),
                    ""ColumnChar"" CHAR(10),
                    ""ColumnNChar"" GRAPHIC(10),
                    ""ColumnInt"" INTEGER,
                    ""ColumnBigInt"" BIGINT,
                    ""ColumnSmallInt"" SMALLINT,
                    ""ColumnTinyInt"" SMALLINT,
                    ""ColumnBinaryFloat"" REAL,
                    ""ColumnBinaryDouble"" DOUBLE,
                    ""ColumnRaw"" VARCHAR(500) FOR BIT DATA,
                    CONSTRAINT ""CompleteTable_pk"" PRIMARY KEY (""Id"")
                )";
            using var connection = new DB2Connection(ConnectionString);
            ExecuteCreateTableIfNotExists(connection, commandText);
        }

        private static void CreateNonIdentityCompleteTable()
        {
            var commandText = @"
                CREATE TABLE ""NonIdentityCompleteTable""
                (
                    ""Id"" INTEGER NOT NULL,
                    ""SessionId"" CHAR(16) FOR BIT DATA NOT NULL,
                    ""ColumnVarchar"" VARCHAR(256),
                    ""ColumnNumber"" DECIMAL(18,12),
                    ""ColumnDate"" DATE,
                    ""ColumnTimestamp"" TIMESTAMP,
                    ""ColumnVarchar2"" VARCHAR(500),
                    ""ColumnChar"" CHAR(10),
                    ""ColumnNChar"" GRAPHIC(10),
                    ""ColumnInt"" INTEGER,
                    ""ColumnBigInt"" BIGINT,
                    ""ColumnSmallInt"" SMALLINT,
                    ""ColumnTinyInt"" SMALLINT,
                    ""ColumnBinaryFloat"" REAL,
                    ""ColumnBinaryDouble"" DOUBLE,
                    ""ColumnRaw"" VARCHAR(500) FOR BIT DATA,
                    CONSTRAINT ""NonIdentityCompleteTable_pk"" PRIMARY KEY (""Id"")
                )";
            using var connection = new DB2Connection(ConnectionString);
            ExecuteCreateTableIfNotExists(connection, commandText);
        }

        /// <summary>
        /// Db2 has no "CREATE TABLE IF NOT EXISTS" clause, unlike SQL Server/PostgreSql/MySql - guard
        /// against re-running this against an already-initialized database by catching SQL0601N
        /// ("the name of the object to be created is identical to the existing name of the same
        /// object type") instead, analogous to how the Oracle provider catches ORA-00955 for the
        /// same reason.
        /// </summary>
        private static void ExecuteCreateTableIfNotExists(DB2Connection connection,
            string commandText) =>
            ExecuteDdlIfObjectDoesNotAlreadyExist(connection, commandText);

        /// <summary>
        /// Same "already exists" guard as <see cref="ExecuteCreateTableIfNotExists"/>, generalized
        /// for any CREATE-style DDL - SQL0601N/-601 is Db2's one "the object I'm creating already
        /// has this name" error, independent of the object type being created.
        /// </summary>
        private static void ExecuteDdlIfObjectDoesNotAlreadyExist(DB2Connection connection,
            string commandText)
        {
            const int ObjectAlreadyExistsSqlCode = -601; // SQL0601N/-601
            try
            {
                connection.ExecuteNonQuery(commandText);
            }
            catch (DB2Exception ex) when (ex.Errors?.Cast<DB2Error>().Any(e => e.NativeError == ObjectAlreadyExistsSqlCode) == true)
            {
                // Object already exists from a prior run - nothing to do.
            }
        }

        #endregion

        #region CompleteTable

        public static IEnumerable<CompleteTable> CreateCompleteTables(int count)
        {
            using var connection = new DB2Connection(ConnectionString);
            // Materialize eagerly - Helper.CreateCompleteTables is a lazy generator, and each
            // re-enumeration would otherwise produce fresh random rows that were never inserted.
            var tables = Helper.CreateCompleteTables(count).ToList();
            foreach (var table in tables)
            {
                connection.Insert(table);
            }
            return tables;
        }

        #endregion

        #region NonIdentityCompleteTable

        public static IEnumerable<NonIdentityCompleteTable> CreateNonIdentityCompleteTables(int count)
        {
            using var connection = new DB2Connection(ConnectionString);
            var tables = Helper.CreateNonIdentityCompleteTables(count).ToList();
            foreach (var table in tables)
            {
                connection.Insert(table);
            }
            return tables;
        }

        #endregion
    }
}
