#region Copyright Attributions

// Copyright (c) 2026 Michael Camara Pendon.
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for full license information.

#endregion

using System;
using Npgsql;
using RepoDb.Connector.AuroraDb.Npgsql;
using RepoDb.Schema.AuroraDbPostgreSql;

namespace RepoDb.Schema.AuroraDbPostgreSql.IntegrationTests.Setup
{
    public static class Database
    {
        #region Properties

        /// <summary>
        /// Gets or sets the connection string to be used for the PostgreSQL maintenance database.
        /// </summary>
        public static string ConnectionStringForMaster { get; private set; }

        /// <summary>
        /// Gets or sets the connection string to be used for the source database (the schema is read from here).
        /// </summary>
        public static string ConnectionStringForSource { get; private set; }

        /// <summary>
        /// Gets or sets the connection string to be used for the target database (the schema is created here).
        /// </summary>
        public static string ConnectionStringForTarget { get; private set; }

        #endregion

        #region Methods

        public static void Initialize()
        {
            // Maintenance connection
            ConnectionStringForMaster =
                Environment.GetEnvironmentVariable("REPODB_PGSQL_SCHEMA_CONSTR_MASTER") ??
                "Server=127.0.0.1;Port=5435;Database=postgres;User Id=postgres;Password=RepoDB2026;";

            // Source connection
            ConnectionStringForSource =
                Environment.GetEnvironmentVariable("REPODB_PGSQL_SCHEMA_CONSTR_SOURCE") ??
                "Server=127.0.0.1;Port=5435;Database=repodb_schema_source;User Id=postgres;Password=RepoDB2026;Pooling=false;";

            // Target connection
            ConnectionStringForTarget =
                Environment.GetEnvironmentVariable("REPODB_PGSQL_SCHEMA_CONSTR_TARGET") ??
                "Server=127.0.0.1;Port=5435;Database=repodb_schema_target;User Id=postgres;Password=RepoDB2026;Pooling=false;";

            // Initialize the AuroraDbPostgreSql
            GlobalConfiguration
                .Setup()
                .UseAuroraDbPostgreSqlSchema();

            // Create databases, the source tables and the target schemas
            CreateDatabases();
            CreateSourceTables();
            Cleanup();
        }

        public static void Cleanup()
        {
            // The target database is dedicated to the tests, so everything in it is dropped
            using (var connection = new AuroraDbConnection(ConnectionStringForTarget))
            {
                ResetSchemas(connection);
            }
        }

        #endregion

        #region Helpers

        private static void ResetSchemas(AuroraDbConnection connection) =>
            connection.ExecuteNonQuery(@"DROP SCHEMA IF EXISTS public CASCADE;
                DROP SCHEMA IF EXISTS sales CASCADE;
                CREATE SCHEMA public;
                CREATE SCHEMA sales;");

        private static void CreateDatabases()
        {
            using (var connection = new AuroraDbConnection(ConnectionStringForMaster).EnsureOpen())
            {
                foreach (var name in new[] { "repodb_schema_source", "repodb_schema_target" })
                {
                    var exists = connection.ExecuteScalar<int>("SELECT COUNT(*) FROM pg_database WHERE datname = @Name;", new { Name = name });
                    if (exists == 0)
                    {
                        connection.ExecuteNonQuery($"CREATE DATABASE {name};");
                    }
                }
            }
        }

        private static void CreateSourceTables()
        {
            using (var connection = new AuroraDbConnection(ConnectionStringForSource))
            {
                ResetSchemas(connection);

                // The table names with an upper-case letter are quoted, so they are case-sensitive
                connection.ExecuteNonQuery(@"CREATE TABLE country (
                        id integer NOT NULL,
                        name varchar(100) NOT NULL,
                        CONSTRAINT pk_country PRIMARY KEY (id),
                        CONSTRAINT uq_country_name UNIQUE (name)
                    );

                    CREATE TABLE ""Person"" (
                        ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 10 INCREMENT BY 5) NOT NULL,
                        ""Name"" varchar(50) NOT NULL,
                        ""Age"" integer NULL,
                        ""Salary"" numeric(12,2) NULL DEFAULT 0,
                        ""CreatedAt"" timestamp(3) NOT NULL DEFAULT now(),
                        ""CountryId"" integer NULL,
                        ""Double"" integer GENERATED ALWAYS AS (""Age"" * 2) STORED,
                        ""Token"" uuid NULL,
                        ""Photo"" bytea NULL,
                        ""Active"" boolean NOT NULL DEFAULT true,
                        CONSTRAINT pk_person PRIMARY KEY (""Id""),
                        CONSTRAINT ck_person_age CHECK (""Age"" >= 0),
                        CONSTRAINT fk_person_country FOREIGN KEY (""CountryId"") REFERENCES country (id) ON DELETE CASCADE ON UPDATE SET NULL
                    );
                    CREATE INDEX ix_person_name ON ""Person"" (""Name"" DESC, ""Age"") INCLUDE (""Salary"") WHERE ""Active"";
                    CREATE UNIQUE INDEX ux_person_token ON ""Person"" (""Token"") WHERE ""Token"" IS NOT NULL;

                    CREATE TABLE ticket (
                        id serial PRIMARY KEY,
                        note text
                    );

                    CREATE TABLE no_key (
                        value integer
                    );

                    CREATE TABLE node_a (
                        id integer PRIMARY KEY,
                        b_id integer
                    );
                    CREATE TABLE node_b (
                        id integer PRIMARY KEY,
                        a_id integer REFERENCES node_a (id)
                    );
                    ALTER TABLE node_a ADD CONSTRAINT fk_node_a_b FOREIGN KEY (b_id) REFERENCES node_b (id);

                    CREATE TABLE sales.order_line (
                        id integer PRIMARY KEY,
                        person_id bigint NOT NULL REFERENCES ""Person"" (""Id"")
                    );");

                CreateRelationshipTables(connection);
                CreateIndexAndTypeTables(connection);
            }
        }

        private static void CreateRelationshipTables(AuroraDbConnection connection) =>
            connection.ExecuteNonQuery(@"-- A dependency chain
                CREATE TABLE chain_a (id integer PRIMARY KEY, name text);
                CREATE TABLE chain_b (id integer PRIMARY KEY, a_id integer NOT NULL REFERENCES chain_a (id));
                CREATE TABLE chain_c (id integer PRIMARY KEY, b_id integer NOT NULL REFERENCES chain_b (id));

                -- A diamond
                CREATE TABLE d_root (id integer PRIMARY KEY);
                CREATE TABLE d_left (id integer PRIMARY KEY, root_id integer REFERENCES d_root (id));
                CREATE TABLE d_right (id integer PRIMARY KEY, root_id integer REFERENCES d_root (id));
                CREATE TABLE d_leaf (id integer PRIMARY KEY, left_id integer REFERENCES d_left (id), right_id integer REFERENCES d_right (id));

                -- A self reference
                CREATE TABLE employee (id integer PRIMARY KEY, manager_id integer REFERENCES employee (id));

                -- A composite key that is referenced by a composite foreign key
                CREATE TABLE region_code (country_code char(2) NOT NULL, code integer NOT NULL, PRIMARY KEY (country_code, code));
                CREATE TABLE shipment (
                    id integer PRIMARY KEY,
                    country_code char(2),
                    region integer,
                    CONSTRAINT fk_shipment_region FOREIGN KEY (country_code, region) REFERENCES region_code (country_code, code)
                );

                -- Two foreign keys to the same table
                CREATE TABLE account (id integer PRIMARY KEY);
                CREATE TABLE transfer (
                    id integer PRIMARY KEY,
                    from_id integer REFERENCES account (id),
                    to_id integer REFERENCES account (id)
                );

                -- A cycle of three tables
                CREATE TABLE ring_1 (id integer PRIMARY KEY, next_id integer);
                CREATE TABLE ring_2 (id integer PRIMARY KEY, next_id integer);
                CREATE TABLE ring_3 (id integer PRIMARY KEY, next_id integer);
                ALTER TABLE ring_1 ADD CONSTRAINT fk_ring_1 FOREIGN KEY (next_id) REFERENCES ring_2 (id);
                ALTER TABLE ring_2 ADD CONSTRAINT fk_ring_2 FOREIGN KEY (next_id) REFERENCES ring_3 (id);
                ALTER TABLE ring_3 ADD CONSTRAINT fk_ring_3 FOREIGN KEY (next_id) REFERENCES ring_1 (id);

                -- A cycle with a table that it depends on and a table that depends on it
                CREATE TABLE loop_base (id integer PRIMARY KEY);
                CREATE TABLE loop_a (id integer PRIMARY KEY, base_id integer REFERENCES loop_base (id), b_id integer);
                CREATE TABLE loop_b (id integer PRIMARY KEY, a_id integer REFERENCES loop_a (id));
                ALTER TABLE loop_a ADD CONSTRAINT fk_loop_a_b FOREIGN KEY (b_id) REFERENCES loop_b (id);
                CREATE TABLE loop_tail (id integer PRIMARY KEY, a_id integer REFERENCES loop_a (id));

                -- A table with many children
                CREATE TABLE fan_parent (id integer PRIMARY KEY);
                CREATE TABLE fan_1 (id integer PRIMARY KEY, parent_id integer REFERENCES fan_parent (id));
                CREATE TABLE fan_2 (id integer PRIMARY KEY, parent_id integer REFERENCES fan_parent (id));
                CREATE TABLE fan_3 (id integer PRIMARY KEY, parent_id integer REFERENCES fan_parent (id));

                -- The same table name in different schemas
                CREATE TABLE item (id integer PRIMARY KEY);
                CREATE TABLE sales.item (id integer PRIMARY KEY);
                CREATE TABLE item_ref (id integer PRIMARY KEY, item_id integer REFERENCES public.item (id), sales_item_id integer REFERENCES sales.item (id));

                -- The names that need quoting
                CREATE TABLE ""odd.name"" (id integer PRIMARY KEY);
                CREATE TABLE ""odd name"" (id integer PRIMARY KEY, parent_id integer REFERENCES ""odd.name"" (id));
                CREATE TABLE ""odd""""name"" (id integer PRIMARY KEY);

                -- The rules of the foreign keys
                CREATE TABLE color (id integer PRIMARY KEY);
                CREATE TABLE preference (
                    id integer PRIMARY KEY,
                    color_id integer NOT NULL DEFAULT 0,
                    other_id integer,
                    CONSTRAINT fk_preference_color FOREIGN KEY (color_id) REFERENCES color (id) ON DELETE SET DEFAULT ON UPDATE RESTRICT,
                    CONSTRAINT fk_preference_other FOREIGN KEY (other_id) REFERENCES color (id) ON DELETE SET NULL ON UPDATE CASCADE
                );");

        private static void CreateIndexAndTypeTables(AuroraDbConnection connection) =>
            connection.ExecuteNonQuery(@"CREATE TABLE product (
                    id integer PRIMARY KEY,
                    code varchar(20) NOT NULL,
                    name varchar(50),
                    price numeric(10,2),
                    active boolean NOT NULL DEFAULT true
                );
                CREATE INDEX ix_product_name ON product (name);
                CREATE UNIQUE INDEX ux_product_code ON product (code);
                CREATE INDEX ix_product_multi ON product (name DESC, price) INCLUDE (code);
                CREATE INDEX ix_product_active ON product (id) WHERE active;
                CREATE INDEX ix_product_all_desc ON product (name DESC, price DESC);

                CREATE TABLE all_types (
                    c_smallint smallint NOT NULL,
                    c_integer integer NOT NULL,
                    c_bigint bigint,
                    c_real real,
                    c_double double precision,
                    c_numeric numeric(10,3),
                    c_numeric_free numeric,
                    c_boolean boolean,
                    c_char char(5),
                    c_varchar varchar(20),
                    c_varchar_free varchar,
                    c_text text,
                    c_bytea bytea,
                    c_uuid uuid,
                    c_date date,
                    c_time time(2),
                    c_timestamp timestamp(4),
                    c_timestamp_free timestamp,
                    c_timestamptz timestamptz(3),
                    c_jsonb jsonb
                );");

        #endregion
    }
}
