<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>RepoDb.Benchmarks.MySql</AssemblyName>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <LangVersion>preview</LangVersion>
    <Nullable>annotations</Nullable>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Dapper.Contrib" Version="2.0.78" />
    <PackageReference Include="linq2db" Version="6.4.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="MySql.EntityFrameworkCore" Version="10.0.9" />
    <PackageReference Include="NHibernate" Version="5.7.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Providers\RepoDb.MySql\RepoDb.MySql\RepoDb.MySql.csproj" />
    <ProjectReference Include="..\..\..\Providers\RepoDb.MySql.BulkOperations\RepoDb.MySql.BulkOperations\RepoDb.MySql.BulkOperations.csproj" />
    <ProjectReference Include="..\RepoDb.Benchmarks.Core\RepoDb.Benchmarks.Core.csproj" />
  </ItemGroup>
</Project>
