<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Title>RepoDb.Schema.ClickHouse</Title>
    <AssemblyName>RepoDb.Schema.ClickHouse</AssemblyName>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <Description>The ClickHouse schema reader and composer of RepoDB library.</Description>
    <LangVersion>preview</LangVersion>
    <Nullable>annotations</Nullable>
    <PackageTags>orm hybrid-orm micro-orm schema clickhouse</PackageTags>
    <PackageIcon>ClickHouse.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageProjectUrl>https://repodb.net/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/mikependon/RepoDB/tree/master/src/Schema/RepoDb.Schema.ClickHouse</RepositoryUrl>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\..\..\LICENSE.txt" Pack="True" PackagePath="\" />
    <None Include="..\README.md" Pack="True" PackagePath="\" />
    <None Include="..\ClickHouse.png" Pack="True" PackagePath="\" />
    <None Include="..\..\..\..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="RepoDb.Schema.ClickHouse.UnitTests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\RepoDb.Schema.Core\RepoDb.Schema.Core\RepoDb.Schema.Core.csproj" />
    <ProjectReference Include="..\..\..\Providers\RepoDb.ClickHouse\RepoDb.ClickHouse\RepoDb.ClickHouse.csproj" />
  </ItemGroup>
</Project>
