name: Build & Run Tests - RepoDb.PostgreSql (Push)

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/Providers/RepoDb.Core/**'
      - 'src/Providers/RepoDb.PostgreSql/**'
      - '.github/workflows/build-base.yml'
      - '.github/workflows/build-pgsql.yml'

jobs:
  build:
    uses: ./.github/workflows/build-base.yml
    with:
      solution-dir: src/Providers/RepoDb.PostgreSql
      solution-file: RepoDb.PostgreSql.sln
      artifact-name: release-pgsql
      db-engine: postgresql
