name: Build & Run Tests - RepoDb.MySqlConnector (Push)

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/Providers/RepoDb.Core/**'
      - 'src/Providers/RepoDb.MySqlConnector/**'
      - '.github/workflows/build-base.yml'
      - '.github/workflows/build-mysqlconnector.yml'

jobs:
  build:
    uses: ./.github/workflows/build-base.yml
    with:
      solution-dir: src/Providers/RepoDb.MySqlConnector
      solution-file: RepoDb.MySqlConnector.sln
      artifact-name: release-mysqlconnector
      db-engine: mysql
