name: Build & Run Tests - RepoDb.SqlServer (Pull Request)

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'RepoDb.Core/**'
      - 'RepoDb.SqlServer/**'
      - '.github/workflows/build-base.yml'
      - '.github/workflows/build-pr-sqlsvr.yml'

jobs:
  build:
    uses: ./.github/workflows/build-base.yml
    with:
      solution-dir: RepoDb.SqlServer
      solution-file: RepoDb.SqlServer.sln
      artifact-name: release-pr
