name: Build & Run Tests - RepoDb.MariaDb.BulkOperations (Push)

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/Providers/RepoDb.Core/**'
      - 'src/Providers/RepoDb.MariaDb/**'
      - 'src/Providers/RepoDb.MariaDb.BulkOperations/**'
      - '.github/workflows/build-base.yml'
      - '.github/workflows/build-mariadb-bulk.yml'

jobs:
  build:
    uses: ./.github/workflows/build-base.yml
    with:
      solution-dir: src/Providers/RepoDb.MariaDb.BulkOperations
      solution-file: RepoDb.MariaDb.BulkOperations.sln
      artifact-name: release-mariadb-bulk
      db-engine: mariadb
