name: PR -  Build & Run Tests - RepoDb.CockroachDB

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/Providers/RepoDb.Core/**'
      - 'src/Providers/RepoDb.CockroachDB/**'
      - '.github/workflows/build-base.yml'
      - '.github/workflows/build-pr-cockroachdb.yml'

jobs:
  build:
    uses: ./.github/workflows/build-base.yml
    with:
      solution-dir: src/Providers/RepoDb.CockroachDB
      solution-file: RepoDb.CockroachDB.sln
      artifact-name: release-pr
      db-engine: cockroachdb
