name: PR - Build & Run Tests - RepoDb.MySql.BulkOperations

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/Providers/RepoDb.Core/**'
      - 'src/Providers/RepoDb.MySql/**'
      - 'src/Providers/RepoDb.MySql.BulkOperations/**'
      - '.github/workflows/build-base.yml'
      - '.github/workflows/build-pr-mysql-bulk.yml'

jobs:
  build:
    uses: ./.github/workflows/build-base.yml
    with:
      solution-dir: src/Providers/RepoDb.MySql.BulkOperations
      solution-file: RepoDb.MySql.BulkOperations.sln
      artifact-name: release-pr
      db-engine: mysql
