name: Build & Run Tests - RepoDb.PostgreSql (Push)

on:
  push

jobs:
  build:
    uses: ./.github/workflows/_base.yml
    with:
      solution-dir: RepoDb.PostgreSql
      solution-file: RepoDb.PostgreSql.sln
      artifact-name: release-pgsql
