name: Build & Run Tests - RepoDb.MySqlConnector (Push)

on:
  push

jobs:
  build:
    uses: ./.github/workflows/_base.yml
    with:
      solution-dir: RepoDb.MySqlConnector
      solution-file: RepoDb.MySqlConnector.sln
      artifact-name: release-mysqlconnector
