name: Build & Run Tests - RepoDb.SqlServer.BulkOperations (Push)

on:
  push

jobs:
  build:
    uses: ./.github/workflows/_base.yml
    with:
      solution-dir: RepoDb.Extensions/RepoDb.SqlServer.BulkOperations
      solution-file: RepoDb.SqlServer.BulkOperations.sln
      artifact-name: release-sqlsvr-bulk
