name: Build & Run Tests - RepoDb.MariaDbConnector (Push)

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/Providers/RepoDb.Core/**'
      - 'src/Providers/RepoDb.MariaDbConnector/**'
      - '.github/workflows/build-base.yml'
      - '.github/workflows/build-mariadbconnector.yml'

jobs:
  build:
    uses: ./.github/workflows/build-base.yml
    with:
      solution-dir: src/Providers/RepoDb.MariaDbConnector
      solution-file: RepoDb.MariaDbConnector.sln
      artifact-name: release-mariadbconnector
      db-engine: mariadb
