name: Build & Run Tests - RepoDb.SQLite.System (Push)

on:
  push

jobs:
  build:
    uses: ./.github/workflows/_base.yml
    with:
      solution-dir: RepoDb.SQLite.System
      solution-file: RepoDb.SQLite.System.sln
      artifact-name: release-sqlite-system
