name: Build & Run Tests - RepoDb.Sqlite.Microsoft (Pull Request)

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'RepoDb.Core/**'
      - 'RepoDb.Sqlite.Microsoft/**'
      - '.github/workflows/build-base.yml'
      - '.github/workflows/build-pr-sqlite-microsoft.yml'

jobs:
  build:
    uses: ./.github/workflows/build-base.yml
    with:
      solution-dir: RepoDb.Sqlite.Microsoft
      solution-file: RepoDb.Sqlite.Microsoft.sln
      artifact-name: release-pr
