name: Build & Run Tests - RepoDb.SQLite.System (Push)

on:
  workflow_dispatch:
  push:
    paths:
      - 'RepoDb.Core/**'
      - 'RepoDb.SQLite.System/**'
      - '.github/workflows/build-base.yml'
      - '.github/workflows/build-sqlite-system.yml'

jobs:
  build:
    uses: ./.github/workflows/build-base.yml
    with:
      solution-dir: RepoDb.SQLite.System
      solution-file: RepoDb.SQLite.System.sln
      artifact-name: release-sqlite-system
