name: PR -  Build & Run Tests - RepoDb.Vertica

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'RepoDb.Core/**'
      - 'RepoDb.Vertica/**'
      - '.github/workflows/build-base.yml'
      - '.github/workflows/build-pr-vertica.yml'

jobs:
  build:
    uses: ./.github/workflows/build-base.yml
    with:
      solution-dir: RepoDb.Vertica
      solution-file: RepoDb.Vertica.sln
      artifact-name: release-pr
      db-engine: vertica
