name: PR - Build & Run Tests - RepoDb.MariaDbConnector

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'RepoDb.Core/**'
      - 'RepoDb.MariaDbConnector/**'
      - '.github/workflows/build-base.yml'
      - '.github/workflows/build-pr-mariadbconnector.yml'

jobs:
  build:
    uses: ./.github/workflows/build-base.yml
    with:
      solution-dir: RepoDb.MariaDbConnector
      solution-file: RepoDb.MariaDbConnector.sln
      artifact-name: release-pr
      db-engine: mariadb
