name: Build & Run Tests - RepoDb.Db2 (Push)

on:
  workflow_dispatch:
  push:
    paths:
      - 'RepoDb.Core/**'
      - 'RepoDb.Db2/**'
      - '.github/workflows/build-base.yml'
      - '.github/workflows/build-db2.yml'

jobs:
  build:
    uses: ./.github/workflows/build-base.yml
    with:
      solution-dir: RepoDb.Db2
      solution-file: RepoDb.Db2.sln
      artifact-name: release-db2
      db-engine: db2
