name: Build & Run Tests - RepoDb.MySql.BulkOperations (Push)

on:
  workflow_dispatch:
  push:
    paths:
      - 'RepoDb.Core/**'
      - 'RepoDb.MySql/**'
      - 'RepoDb.Extensions/RepoDb.MySql.BulkOperations/**'
      - '.github/workflows/build-base.yml'
      - '.github/workflows/build-mysql-bulk.yml'

jobs:
  build:
    uses: ./.github/workflows/build-base.yml
    with:
      solution-dir: RepoDb.Extensions/RepoDb.MySql.BulkOperations
      solution-file: RepoDb.MySql.BulkOperations.sln
      artifact-name: release-mysql-bulk
      db-engine: mysql
