name: PR -  Build & Run Tests - RepoDb.EnterpriseDb

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'RepoDb.Core/**'
      - 'RepoDb.EnterpriseDb/**'
      - '.github/workflows/build-base.yml'
      - '.github/workflows/build-pr-enterprisedb.yml'

jobs:
  build:
    uses: ./.github/workflows/build-base.yml
    with:
      solution-dir: RepoDb.EnterpriseDb
      solution-file: RepoDb.EnterpriseDb.sln
      artifact-name: release-pr
      db-engine: enterprisedb
