name: Build & Run Tests for PR

on:
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/_base.yml
    with:
      solution-dir: .
      solution-file: RepoDb.Solutions.sln
      artifact-name: release-pr
