name: PR - Build & Run Tests - RepoDb.MySqlConnector

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'RepoDb.Core/**'
      - 'RepoDb.MySqlConnector/**'
      - '.github/workflows/build-base.yml'
      - '.github/workflows/build-pr-mysqlconnector.yml'

jobs:
  build:
    uses: ./.github/workflows/build-base.yml
    with:
      solution-dir: RepoDb.MySqlConnector
      solution-file: RepoDb.MySqlConnector.sln
      artifact-name: release-pr
