name: Build & Run Tests - RepoDb.Vertica.BulkOperations (Push)

on:
  workflow_dispatch:
  push:
    paths:
      - 'RepoDb.Core/**'
      - 'RepoDb.Vertica/**'
      - 'RepoDb.Extensions/RepoDb.Vertica.BulkOperations/**'
      - '.github/workflows/build-base.yml'
      - '.github/workflows/build-vertica-bulk.yml'

jobs:
  build:
    uses: ./.github/workflows/build-base.yml
    with:
      solution-dir: RepoDb.Extensions/RepoDb.Vertica.BulkOperations
      solution-file: RepoDb.Vertica.BulkOperations.sln
      artifact-name: release-vertica-bulk
      db-engine: vertica
