name: Build & Run Tests - RepoDb.SqlServer (Push)

on:
  push

jobs:
  build:
    uses: ./.github/workflows/_base.yml
    with:
      solution-dir: RepoDb.SqlServer
      solution-file: RepoDb.SqlServer.sln
      artifact-name: release-sqlsvr
