name: PR - Build & Run Tests - RepoDb.AuroraDb.MySqlConnector.BulkOperations

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/Providers/RepoDb.Core/**'
      - 'src/Providers/RepoDb.AuroraDb.MySqlConnector/**'
      - 'src/Providers/RepoDb.AuroraDb.MySqlConnector.BulkOperations/**'
      - '.github/workflows/build-base.yml'
      - '.github/workflows/build-pr-auroradb-mysqlconnector-bulk.yml'

jobs:
  build:
    uses: ./.github/workflows/build-base.yml
    with:
      solution-dir: src/Providers/RepoDb.AuroraDb.MySqlConnector.BulkOperations
      solution-file: RepoDb.AuroraDb.MySqlConnector.BulkOperations.sln
      artifact-name: release-pr
      db-engine: auroradbmysql
