name: Build & Run Tests - RepoDb.MySql (Push)

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/Providers/RepoDb.Core/**'
      - 'src/Providers/RepoDb.MySql/**'
      - '.github/workflows/build-base.yml'
      - '.github/workflows/build-mysql.yml'

jobs:
  build:
    uses: ./.github/workflows/build-base.yml
    with:
      solution-dir: src/Providers/RepoDb.MySql
      solution-file: RepoDb.MySql.sln
      artifact-name: release-mysql
      db-engine: mysql
