name: Build & Run Tests - RepoDb.MySql (Push)

on:
  push:
    paths:
      - 'RepoDb.Core/**'
      - 'RepoDb.MySql/**'
      - '.github/workflows/build-base.yml'
      - '.github/workflows/build-mysql.yml'

jobs:
  build:
    uses: ./.github/workflows/build-base.yml
    with:
      solution-dir: RepoDb.MySql
      solution-file: RepoDb.MySql.sln
      artifact-name: release-mysql
