name: Build & Run Tests - RepoDb.Oracle (Push)

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/Providers/RepoDb.Core/**'
      - 'src/Providers/RepoDb.Oracle/**'
      - '.github/workflows/build-base.yml'
      - '.github/workflows/build-oracle.yml'

jobs:
  build:
    uses: ./.github/workflows/build-base.yml
    with:
      solution-dir: src/Providers/RepoDb.Oracle
      solution-file: RepoDb.Oracle.sln
      artifact-name: release-oracle
      db-engine: oracle
