name: Build & Run Tests - RepoDb.Oracle.BulkOperations (Push)

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/Providers/RepoDb.Core/**'
      - 'src/Providers/RepoDb.Oracle/**'
      - 'src/Providers/RepoDb.Oracle.BulkOperations/**'
      - '.github/workflows/build-base.yml'
      - '.github/workflows/build-oracle-bulk.yml'

jobs:
  build:
    uses: ./.github/workflows/build-base.yml
    with:
      solution-dir: src/Providers/RepoDb.Oracle.BulkOperations
      solution-file: RepoDb.Oracle.BulkOperations.sln
      artifact-name: release-oracle-bulk
      db-engine: oracle
