name: PR -  Build & Run Tests - RepoDb.Db2

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'RepoDb.Core/**'
      - 'RepoDb.Db2/**'
      - '.github/workflows/build-base.yml'
      - '.github/workflows/build-pr-db2.yml'

jobs:
  build:
    uses: ./.github/workflows/build-base.yml
    with:
      solution-dir: RepoDb.Db2
      solution-file: RepoDb.Db2.sln
      artifact-name: release-pr
      db-engine: db2
