name: Build & Run Tests - RepoDb.EnterpriseDb.BulkOperations (Push)

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/Providers/RepoDb.Core/**'
      - 'src/Providers/RepoDb.EnterpriseDb/**'
      - 'src/Providers/RepoDb.EnterpriseDb.BulkOperations/**'
      - 'src/Docker/EnterpriseDB/**'
      - '.github/workflows/build-base.yml'
      - '.github/workflows/build-enterprisedb-bulk.yml'

jobs:
  build:
    uses: ./.github/workflows/build-base.yml
    secrets: inherit
    with:
      solution-dir: src/Providers/RepoDb.EnterpriseDb.BulkOperations
      solution-file: RepoDb.EnterpriseDb.BulkOperations.sln
      artifact-name: release-enterprisedb-bulk
      db-engine: enterprisedb
