name: Release - RepoDb (Manual)

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    uses: ./.github/workflows/release-base.yml
    with:
      project-name: RepoDb
      project-path: RepoDb.Core/RepoDb/RepoDb.csproj
