name: Release - RepoDb.MySqlConnector (Manual)

on:
  release:
    types: [published]

jobs:
  publish:
    uses: ./.github/workflows/release-base.yml
    with:
      project-name: RepoDb.MySqlConnector
      project-path: RepoDb.MySqlConnector/RepoDb.MySqlConnector/RepoDb.MySqlConnector.csproj
