name: Release - RepoDb.Sqlite.Microsoft (Manual)

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    uses: ./.github/workflows/release-base.yml
    with:
      project-name: RepoDb.Sqlite.Microsoft
      project-path: RepoDb.Sqlite.Microsoft/RepoDb.Sqlite.Microsoft/RepoDb.Sqlite.Microsoft.csproj
