name: Release - RepoDb.SQLite.System (Manual)

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    uses: ./.github/workflows/release-base.yml
    with:
      project-name: RepoDb.SQLite.System
      project-path: RepoDb.SQLite.System/RepoDb.SQLite.System/RepoDb.SQLite.System.csproj
